# Generated by Django 5.2.6 on 2025-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='original_ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
