# Generated by Django 5.2.6 on 2025-11-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this API key (e.g., 'Production CRM', 'Sales CRM')", max_length=255)),
                ('api_key', models.CharField(help_text='The API key for accessing the CRM API', max_length=500)),
                ('api_base_url', models.URLField(default='http://api.inclufy.com', help_text='Base URL for the CRM API')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is currently active')),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='Last time CRM users were successfully fetched using this key', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_api_keys', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='accounts_cr_company_110c76_idx')],
            },
        ),
    ]
