# Generated by Django 5.2.6 on 2026-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_biometriccredential'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometriccredential',
            new_name='biometric_c_user_id_481b54_idx',
            old_name='bio_cred_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='biometriccredential',
            new_name='biometric_c_credent_3ea099_idx',
            old_name='bio_cred_credid_idx',
        ),
        migrations.AlterField(
            model_name='biometriccredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
