# Generated by Django 5.2.6 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_company_export_preference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyaikey',
            new_name='accounts_co_company_efbce1_idx',
            old_name='accounts_co_company_active_idx',
        ),
        migrations.AlterField(
            model_name='companyaikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyexportpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
