# Generated by Django 5.2.6 on 2026-06-09 16:29
# New table — no drift guard needed (it has never existed in any environment).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMethodologyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_experience', models.CharField(choices=[('beginner', 'Beginner'), ('gevorderd', 'Gevorderd'), ('pro', 'Professional')], default='gevorderd', max_length=12)),
                ('methodology_competence', models.JSONField(blank=True, default=dict)),
                ('preferred_methodology', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
