# Generated by Django 5.2.6 on 2025-09-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Approval', 'Approval'), ('Resource', 'Resource'), ('External', 'External')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Not Started', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description provided')),
                ('version', models.PositiveIntegerField(default=1)),
                ('project_orchestrator', models.CharField(default='Unknown Orchestrator', max_length=255)),
                ('project_manager', models.CharField(default='Unknown Manager', max_length=255)),
                ('goal_objective', models.TextField(default='No goal provided')),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charters', to='projects.project')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='KeyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='charater.programcharter')),
            ],
            options={
                'verbose_name': 'Key Risk',
                'verbose_name_plural': 'Key Risks',
            },
        ),
        migrations.CreateModel(
            name='KeyDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='charater.programcharter')),
            ],
            options={
                'verbose_name': 'Key Deliverable',
                'verbose_name_plural': 'Key Deliverables',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CriticalInterdependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interdependencies', to='charater.programcharter')),
            ],
            options={
                'verbose_name': 'Critical Interdependency',
                'verbose_name_plural': 'Critical Interdependencies',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('required', models.CharField(max_length=50)),
                ('fte', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='charater.programcharter')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ScopeCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('end_game', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='charater.programcharter')),
            ],
            options={
                'verbose_name': 'Scope / Capability',
                'verbose_name_plural': 'Scopes / Capabilities',
            },
        ),
    ]
