# Generated by Django 4.2.28 on 2026-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0010_courselesson_visual_data_courselesson_visual_type_and_more"),
    ]

    operations = [
        # Fields already added in 0010 (was a parallel migration branch, now linearized)
    ]
