# Generated by Django 4.2.28 on 2026-02-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0011_lessonvisual_preview_image_url"),
    ]

    operations = [
    ]
