# Generated by Django 5.2.6 on 2026-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_extend_lesson_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text="Frontend lesson id (e.g. 'safe-l5'); maps static-course submissions to this DB row for cert-eligibility tracking.", max_length=64),
        ),
    ]
