# Generated by Django 5.2.6 on 2026-06-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_courselesson_external_id'),
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'Specific user'), ('entire_org', 'Entire organization')], default='user', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academy.course')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_course_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantCourseEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('seats', models.PositiveIntegerField(blank=True, help_text='Max seats; null = unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_entitlements', to='accounts.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_entitlements', to='academy.course')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_tenant_course_entitlements',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'course')},
            },
        ),
    ]
