# Generated by Django 5.2.6 on 2026-06-07 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_courseassignment_tenantcourseentitlement'),
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_nl', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_nl', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('leads_to_certificate', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='null = global template visible to every tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_paths', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='learning_paths', to='academy.skill')),
            ],
            options={
                'db_table': 'academy_learning_paths',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('microlearning', 'Microlearning'), ('module', 'Module'), ('lesson', 'Lesson'), ('exam', 'Exam')], default='course', max_length=20)),
                ('ref_id', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_items', to='academy.course')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academy.learningpath')),
            ],
            options={
                'db_table': 'academy_learning_path_items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
