# Generated by Django 4.2.28 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='methodology',
            field=models.CharField(choices=[('safe', 'SAFe (Scaled Agile Framework)'), ('msp', 'MSP (Managing Successful Programmes)'), ('pmi', 'PMI Program Management'), ('prince2_programme', 'PRINCE2 Programme'), ('p2_programme', 'P2 Programme (PRINCE2-based blueprint)'), ('hybrid', 'Hybrid'), ('hybrid_programme', 'Hybrid Programme')], default='hybrid', max_length=50),
        ),
        migrations.AlterField(
            model_name='programteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
