# Generated by Django 5.2.6 on 2026-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='methodology',
            field=models.CharField(choices=[('inclufy', 'Inclufy Best Practice'), ('safe', 'SAFe (Scaled Agile Framework)'), ('msp', 'MSP (Managing Successful Programmes)'), ('pmi', 'PMI Program Management'), ('prince2_programme', 'PRINCE2 Programme'), ('p2_programme', 'P2 Programme (PRINCE2-based blueprint)'), ('hybrid', 'Hybrid'), ('hybrid_programme', 'Hybrid Programme')], default='hybrid', max_length=50),
        ),
    ]
