# Generated by Django 5.2.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTailoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, default='', max_length=40)),
                ('dim_scope', models.PositiveSmallIntegerField(default=3)),
                ('dim_budget', models.PositiveSmallIntegerField(default=2)),
                ('dim_duur', models.PositiveSmallIntegerField(default=3)),
                ('dim_politiek', models.PositiveSmallIntegerField(default=2)),
                ('dim_risico', models.PositiveSmallIntegerField(default=2)),
                ('dim_regel', models.PositiveSmallIntegerField(default=1)),
                ('team_size', models.CharField(blank=True, default='l', max_length=4)),
                ('departments', models.PositiveSmallIntegerField(default=2)),
                ('gov_authority', models.CharField(choices=[('owner', 'Alleen programmabestuur'), ('owner_pm', 'Bestuur + programmamanager')], default='owner', max_length=12)),
                ('gov_board', models.CharField(choices=[('auto', 'AI bepaalt'), ('light', 'Lichte review'), ('formal', 'Formele board')], default='auto', max_length=8)),
                ('gov_portfolio', models.BooleanField(default=False)),
                ('gov_stakeholder_matrix', models.BooleanField(default=False)),
                ('gov_periodic_cadence', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='heavy', max_length=8)),
                ('score', models.PositiveSmallIntegerField(default=14)),
                ('recommended_modules', models.JSONField(blank=True, default=list)),
                ('coach_mode', models.BooleanField(default=False)),
                ('ai_rationale', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('scenario', 'Scenario')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring', to='programs.program')),
            ],
        ),
    ]
