# Generated by Django 5.2.6 on 2026-06-08 21:15
#
# Idempotent for the production migration-state-drift pattern in this env
# (a table can already exist physically while the migration is unrecorded).
# Guarded RunPython skips creation when the table already exists; ORM state is
# registered via state_operations either way.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, name):
    conn = schema_editor.connection
    with conn.cursor() as c:
        return name in conn.introspection.table_names(c)


def create_devicetoken(apps, schema_editor):
    if _table_exists(schema_editor, "notifications_devicetoken"):
        return
    from notifications.models import DeviceToken
    schema_editor.create_model(DeviceToken)


def drop_devicetoken(apps, schema_editor):
    if not _table_exists(schema_editor, "notifications_devicetoken"):
        return
    from notifications.models import DeviceToken
    schema_editor.delete_model(DeviceToken)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_devicetoken, drop_devicetoken)],
            state_operations=[
                migrations.CreateModel(
                    name='DeviceToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(max_length=255, unique=True)),
                        ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='ios', max_length=10)),
                        ('active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-updated_at'],
                    },
                ),
            ],
        ),
    ]
