# Generated by Django 5.2.6 on 2026-06-09 06:04
#
# Idempotent for the production migration-state-drift pattern (table may exist
# physically while the migration is unrecorded). Guarded RunPython skips
# creation when the table already exists; ORM state registered either way.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, name):
    conn = schema_editor.connection
    with conn.cursor() as c:
        return name in conn.introspection.table_names(c)


def create_pref(apps, schema_editor):
    if _table_exists(schema_editor, "notifications_notificationpreference"):
        return
    from notifications.models import NotificationPreference
    schema_editor.create_model(NotificationPreference)


def drop_pref(apps, schema_editor):
    if not _table_exists(schema_editor, "notifications_notificationpreference"):
        return
    from notifications.models import NotificationPreference
    schema_editor.delete_model(NotificationPreference)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_pref, drop_pref)],
            state_operations=[
                migrations.CreateModel(
                    name='NotificationPreference',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email_enabled', models.BooleanField(default=True)),
                        ('push_enabled', models.BooleanField(default=True)),
                        ('task_assigned', models.BooleanField(default=True)),
                        ('mention', models.BooleanField(default=True)),
                        ('message', models.BooleanField(default=True)),
                        ('approval', models.BooleanField(default=True)),
                        ('deadline', models.BooleanField(default=True)),
                        ('status_digest', models.BooleanField(default=True)),
                        ('programme_update', models.BooleanField(default=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
    ]
