# Generated by Django 5.2.6 on 2025-10-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('planning', 'Planning'), ('requirements', 'Requirements'), ('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('training', 'Training'), ('general', 'General')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('linked_stages', models.JSONField(default=list, help_text='List of stage names this document is linked to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.upload')),
                ('linked_milestones', models.ManyToManyField(blank=True, related_name='linked_documents', to='projects.milestone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'category'], name='projects_do_project_ef2132_idx'), models.Index(fields=['project', 'status'], name='projects_do_project_624c06_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('end_users', 'End Users'), ('administrators', 'Administrators'), ('developers', 'Developers'), ('managers', 'Managers'), ('all', 'All')], default='end_users', max_length=50)),
                ('format_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('other', 'Other')], default='pdf', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('in_review', 'In Review'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_materials', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_materials', to='projects.upload')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_materials', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'audience'], name='projects_tr_project_5734f9_idx'), models.Index(fields=['project', 'status'], name='projects_tr_project_38f3e5_idx')],
            },
        ),
    ]
