# Generated by Django 5.2.6 on 2025-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_document_trainingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='health_cash_flow',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_cost',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_quality',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_risk',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_safety',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_scope',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='health_time',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='last_analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
