# Generated by Django 5.2.6 on 2025-12-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_health_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for this team member on this project', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=models.CharField(blank=True, choices=[('prince2', 'PRINCE2'), ('agile', 'Agile'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('waterfall', 'Waterfall'), ('lean_six_sigma_green', 'Lean Six Sigma (Green Belt)'), ('lean_six_sigma_black', 'Lean Six Sigma (Black Belt)'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Number of hours worked', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Description of work performed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate at the time of entry (for historical accuracy)', max_digits=10)),
                ('billable', models.BooleanField(default=True, help_text='Whether this time entry is billable')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, help_text='Optional: Link to a specific milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Optional: Link to a specific task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'date'], name='projects_ti_project_931a2e_idx'), models.Index(fields=['user', 'date'], name='projects_ti_user_id_b5bb9d_idx'), models.Index(fields=['project', 'user', 'date'], name='projects_ti_project_691a27_idx'), models.Index(fields=['project', 'status'], name='projects_ti_project_ac0b1c_idx')],
            },
        ),
    ]
