# Generated by Django 5.2.6 on 2025-12-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectteam_hourly_rate_alter_project_methodology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=models.CharField(blank=True, choices=[('prince2', 'PRINCE2'), ('agile', 'Agile'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('waterfall', 'Waterfall'), ('lean_six_sigma_green', 'Lean Six Sigma (Green Belt)'), ('lean_six_sigma_black', 'Lean Six Sigma (Black Belt)'), ('program', 'Program Management'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
    ]
