# Generated by Django 5.2.6 on 2026-05-04 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_code_expense_invoice_vendor_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmitigation',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='+', to='projects.upload'),
        ),
        migrations.AddField(
            model_name='risk',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='+', to='projects.upload'),
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('validation_status', models.CharField(choices=[('Unvalidated', 'Unvalidated'), ('Validated', 'Validated'), ('Invalidated', 'Invalidated')], default='Unvalidated', max_length=20)),
                ('validation_target_date', models.DateField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='projects.upload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assumptions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assumptions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='projects.project')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_assumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefinitionOfDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('project', 'Project-wide'), ('sprint', 'Sprint-specific'), ('feature', 'Feature-specific'), ('epic', 'Epic-specific')], default='project', max_length=20)),
                ('scope_reference', models.CharField(blank=True, help_text='Free-form ID/name of the sprint/feature/epic this DoD applies to', max_length=255)),
                ('title', models.CharField(default='Definition of Done', max_length=255)),
                ('criteria', models.JSONField(default=list, help_text='List of acceptance criteria strings; checked off per increment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='projects.upload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_definitions_of_done', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions_of_done', to='projects.project')),
            ],
            options={
                'ordering': ['-is_active', 'scope', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Blocker', 'Blocker'), ('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('raised_date', models.DateField(default=django.utils.timezone.now)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='projects.upload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('related_risk', models.ForeignKey(blank=True, help_text='If this issue is a risk that materialised, link the original Risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialised_issues', to='projects.risk')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Process', 'Process'), ('Technical', 'Technical'), ('Stakeholder', 'Stakeholder'), ('Resource', 'Resource'), ('Communication', 'Communication'), ('Risk', 'Risk'), ('Quality', 'Quality'), ('Schedule', 'Schedule'), ('Cost', 'Cost'), ('Other', 'Other')], max_length=50)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive (what worked)'), ('negative', "Negative (what didn't)"), ('neutral', 'Neutral (observation)')], default='neutral', max_length=20)),
                ('recommended_action', models.TextField(blank=True, help_text='What to do (or not do) next time based on this lesson')),
                ('applicable_to', models.CharField(choices=[('project', 'This project only'), ('portfolio', 'Portfolio-wide'), ('organisation', 'Organisation-wide')], default='project', max_length=20)),
                ('captured_during_phase', models.CharField(blank=True, help_text="Methodology phase: e.g. 'Sprint 5 retro', 'Stage 2 closure', 'DMAIC Control'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='projects.upload')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_lessons', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_learned', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
