# Generated by Django 5.2.6 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_communicationplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='planevent',
            new_name='projects_pl_plan_id_a35e4f_idx',
            old_name='projects_pl_plan_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='planevent',
            new_name='projects_pl_plan_id_6854ed_idx',
            old_name='projects_pl_plan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='projects_pr_project_33946c_idx',
            old_name='projects_pr_proj_role_idx',
        ),
        migrations.RenameIndex(
            model_name='taskduedatechangerequest',
            new_name='projects_ta_task_id_55a675_idx',
            old_name='projects_ta_task_id_status_idx',
        ),
        migrations.AlterField(
            model_name='communicationplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectsignoff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskduedatechangerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
