# Generated by Django 5.2.6 on 2026-06-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0012_prince2issue_change_authority_and_more'),
        ('projects', '0020_yanmar_bigautofield_index_normalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='prince2.product'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='prince2.workpackage'),
        ),
    ]
