# Generated by Django 5.2.6 on 2026-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_task_product_task_work_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=models.CharField(blank=True, choices=[('inclufy', 'Inclufy Best Practice'), ('prince2', 'PRINCE2'), ('agile', 'Agile'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('waterfall', 'Waterfall'), ('lean_six_sigma_green', 'Lean Six Sigma (Green Belt)'), ('lean_six_sigma_black', 'Lean Six Sigma (Black Belt)'), ('program', 'Program Management'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
    ]
