# Generated by Django 5.2.6 on 2026-06-05 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_methodology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('current_exposure', models.IntegerField(default=0)),
                ('forecast_exposure', models.IntegerField(default=0)),
                ('exposure_trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], default='stable', max_length=8)),
                ('risk_velocity', models.FloatField(default=0.0)),
                ('predicted_high_risks', models.IntegerField(default=0)),
                ('outlook', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('drivers', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True, default='')),
                ('model_used', models.CharField(default='deterministic', max_length=64)),
                ('original_ai_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_forecasts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_forecasts', to='projects.project')),
            ],
            options={
                'db_table': 'risk_forecasts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='risk_foreca_project_f93f1a_idx')],
            },
        ),
    ]
