# Generated by Django 5.2.6 on 2026-06-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_riskforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='affected_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
