# Generated by Django 5.2.6 on 2026-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_risk_affected_milestone_risk_impact_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must complete before this task can start.', related_name='dependents', to='projects.task'),
        ),
    ]
