# Generated by Django 5.2.6 on 2026-06-08 19:38
#
# NOTE: the Task.custom_fields AddField is made idempotent for the production
# migration-state-drift pattern in this environment (the column can already
# exist physically while the migration is unrecorded — that is exactly the
# "column custom_fields already exists" crash this migration originally hit).
# It is vendor-guarded: PostgreSQL uses ADD COLUMN IF NOT EXISTS; other backends
# add it only when introspection shows it is missing. The CustomFieldDefinition
# table is created with a normal CreateModel — on production it does not exist
# yet (the first run rolled back before reaching it), and it is fresh elsewhere.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_custom_fields(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE projects_task ADD COLUMN IF NOT EXISTS "
            "custom_fields jsonb NOT NULL DEFAULT '{}'::jsonb;"
        )
        return
    with conn.cursor() as c:
        cols = [col.name for col in conn.introspection.get_table_description(c, "projects_task")]
    if "custom_fields" in cols:
        return
    Task = apps.get_model("projects", "Task")
    field = models.JSONField(blank=True, default=dict)
    field.set_attributes_from_name("custom_fields")
    schema_editor.add_field(Task, field)


def drop_custom_fields(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE projects_task DROP COLUMN IF EXISTS custom_fields;")
        return
    Task = apps.get_model("projects", "Task")
    try:
        schema_editor.remove_field(Task, Task._meta.get_field("custom_fields"))
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
        ('projects', '0028_savedview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_custom_fields, drop_custom_fields)],
            state_operations=[
                migrations.AddField(
                    model_name='task',
                    name='custom_fields',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('task', 'Task / Action'), ('risk', 'Risk'), ('issue', 'Issue')], db_index=True, default='task', max_length=16)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Single select'), ('checkbox', 'Checkbox'), ('url', 'URL')], default='text', max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('show_in_table', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_defs', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity', 'order_index', 'label'],
                'unique_together': {('company', 'entity', 'key')},
            },
        ),
    ]
