# Generated by Django 5.2.6 on 2026-06-08 20:21
#
# Made idempotent for the production migration-state-drift pattern in this
# environment (the table can already exist physically while the migration is
# unrecorded — the "relation projects_recurringtaskrule already exists" crash).
# The DB op is a guarded RunPython: it skips creation when introspection shows
# the table already exists, otherwise builds it via schema_editor.create_model.
# The ORM state is registered unconditionally via state_operations.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, name):
    conn = schema_editor.connection
    with conn.cursor() as c:
        return name in conn.introspection.table_names(c)


def create_recurring(apps, schema_editor):
    if _table_exists(schema_editor, "projects_recurringtaskrule"):
        return  # drift: table already present, leave it as-is
    # NOTE: the model is not yet in from_state here (SeparateDatabaseAndState),
    # so use the live model — it matches this migration's state (latest one to
    # touch RecurringTaskRule).
    from projects.models import RecurringTaskRule
    schema_editor.create_model(RecurringTaskRule)


def drop_recurring(apps, schema_editor):
    if not _table_exists(schema_editor, "projects_recurringtaskrule"):
        return
    from projects.models import RecurringTaskRule
    schema_editor.delete_model(RecurringTaskRule)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
        ('projects', '0029_task_custom_fields_customfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_recurring, drop_recurring)],
            state_operations=[
                migrations.CreateModel(
                    name='RecurringTaskRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('description', models.TextField(blank=True, default='')),
                        ('category', models.CharField(blank=True, default='', max_length=100)),
                        ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                        ('custom_fields', models.JSONField(blank=True, default=dict)),
                        ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                        ('interval', models.PositiveIntegerField(default=1)),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('next_run_date', models.DateField(db_index=True)),
                        ('last_generated_date', models.DateField(blank=True, null=True)),
                        ('due_offset_days', models.PositiveIntegerField(default=0)),
                        ('active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_rules', to='accounts.company')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                        ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='projects.milestone')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_rules', to='projects.project')),
                    ],
                    options={
                        'ordering': ['next_run_date', 'title'],
                    },
                ),
            ],
        ),
    ]
