# Generated by Django 5.2.6 on 2026-06-09 09:06
#
# Idempotent for the production migration-state-drift pattern (column may exist
# physically while the migration is unrecorded). PostgreSQL uses ADD COLUMN IF
# NOT EXISTS; other backends add only when introspection shows it missing.

from django.db import migrations, models


def add_col(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE projects_project ADD COLUMN IF NOT EXISTS "
            "pm_can_authorize boolean NOT NULL DEFAULT false;"
        )
        return
    with conn.cursor() as c:
        cols = [col.name for col in conn.introspection.get_table_description(c, "projects_project")]
    if "pm_can_authorize" in cols:
        return
    from django.db import models as m
    Project = apps.get_model("projects", "Project")
    field = m.BooleanField(default=False)
    field.set_attributes_from_name("pm_can_authorize")
    schema_editor.add_field(Project, field)


def drop_col(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE projects_project DROP COLUMN IF EXISTS pm_can_authorize;")


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_recurringtaskrule'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_col, drop_col)],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='pm_can_authorize',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
