# Generated by Django 5.2.6 on 2025-09-30 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Monthly or Yearly billing', max_length=10)),
                ('plan_level', models.CharField(choices=[('basic', 'Basic'), ('starter', 'Starter'), ('business', 'Business'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Plan tier/level', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID for checkout', max_length=200, unique=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID', max_length=200, null=True)),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/recommended plan')),
                ('max_projects', models.PositiveIntegerField(blank=True, help_text='Maximum number of projects allowed (null = unlimited)', null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Maximum number of users allowed (null = unlimited)', null=True)),
                ('storage_limit_gb', models.PositiveIntegerField(blank=True, help_text='Storage limit in GB (null = unlimited)', null=True)),
                ('priority_support', models.BooleanField(default=False, help_text='Includes priority support')),
                ('advanced_analytics', models.BooleanField(default=False, help_text='Includes advanced analytics')),
                ('custom_integrations', models.BooleanField(default=False, help_text='Includes custom integrations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan_type', 'price'],
                'unique_together': {('name', 'plan_type')},
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(help_text='Stripe Subscription ID', max_length=200, unique=True)),
                ('stripe_customer_id', models.CharField(help_text='Stripe Customer ID', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('paused', 'Paused')], default='incomplete', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.company')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trialing', 'past_due'])), fields=('company',), name='unique_active_company_subscription')],
            },
        ),
    ]
