# Generated by Django 5.2.6 on 2026-01-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle for this subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('invoice', 'Invoice')], default='stripe', help_text='Payment method for this subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (optional for invoice)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID (optional for invoice)', max_length=200, null=True, unique=True),
        ),
    ]
