# Data migration: seed default SubscriptionPlan rows.
#
# Mirrors the pricing tiers shown on the public pricing page and in the
# Inclufy_Yanmar_DeepDive_v6 deck (slide 16):
#   - Starter:    €25 / seat / month  (basic features)
#   - Pro:        €60 / seat / month  (AI Coach + 8 methodologies + Academy)
#   - Enterprise: €120 / seat / month (full + governance + audit)
#
# Idempotent: uses update_or_create keyed by (name, plan_type).
# NOT auto-applied — generated by Fix 5 of the 2026-04-28 admin portal audit.

from django.db import migrations
from decimal import Decimal


PLANS = [
    {
        "name": "Starter",
        "plan_level": "starter",
        "price": Decimal("25.00"),
        "stripe_price_id": "price_starter_monthly_eur_seed",
        "stripe_product_id": "prod_starter_seed",
        "is_popular": False,
        "max_projects": 10,
        "max_users": 10,
        "storage_limit_gb": 5,
        "priority_support": False,
        "advanced_analytics": False,
        "custom_integrations": False,
        "features": [
            "Up to 10 projects",
            "Up to 10 users",
            "Basic project management",
            "Email support",
            "5 GB storage",
        ],
    },
    {
        "name": "Pro",
        "plan_level": "premium",
        "price": Decimal("60.00"),
        "stripe_price_id": "price_pro_monthly_eur_seed",
        "stripe_product_id": "prod_pro_seed",
        "is_popular": True,
        "max_projects": None,  # unlimited
        "max_users": 100,
        "storage_limit_gb": 100,
        "priority_support": True,
        "advanced_analytics": True,
        "custom_integrations": False,
        "features": [
            "Unlimited projects",
            "Up to 100 users",
            "AI Coach",
            "8 methodologies (Prince2, Agile, Scrum, Kanban, Waterfall, LSS Green, LSS Black, Hybrid)",
            "Academy access",
            "Advanced analytics",
            "Priority support",
            "100 GB storage",
        ],
    },
    {
        "name": "Enterprise",
        "plan_level": "enterprise",
        "price": Decimal("120.00"),
        "stripe_price_id": "price_enterprise_monthly_eur_seed",
        "stripe_product_id": "prod_enterprise_seed",
        "is_popular": False,
        "max_projects": None,
        "max_users": None,
        "storage_limit_gb": None,
        "priority_support": True,
        "advanced_analytics": True,
        "custom_integrations": True,
        "features": [
            "Everything in Pro",
            "Unlimited users",
            "Unlimited storage",
            "Governance module",
            "Full audit log access",
            "Custom integrations",
            "SSO / SAML",
            "Dedicated success manager",
        ],
    },
]


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    for plan in PLANS:
        SubscriptionPlan.objects.update_or_create(
            name=plan["name"],
            plan_type="monthly",
            defaults={
                "plan_level": plan["plan_level"],
                "price": plan["price"],
                "stripe_price_id": plan["stripe_price_id"],
                "stripe_product_id": plan["stripe_product_id"],
                "is_active": True,
                "is_popular": plan["is_popular"],
                "max_projects": plan["max_projects"],
                "max_users": plan["max_users"],
                "storage_limit_gb": plan["storage_limit_gb"],
                "priority_support": plan["priority_support"],
                "advanced_analytics": plan["advanced_analytics"],
                "custom_integrations": plan["custom_integrations"],
                "features": plan["features"],
            },
        )


def unseed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(
        name__in=[p["name"] for p in PLANS],
        plan_type="monthly",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_demorequest_quoterequest_invoicerequest"),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_code=unseed_plans),
    ]
