# Generated by Django 5.2.6 on 2026-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_seed_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_level',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('basic', 'Basic (legacy)'), ('premium', 'Premium (legacy)')], help_text='Plan tier/level', max_length=20),
        ),
    ]
