# Generated by Django 5.2.6 on 2026-06-05 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aikey_bigautofield_index_normalize'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('task.status_changed', 'Task status changed'), ('task.created', 'Task created'), ('backlog_item.status_changed', 'Backlog item status changed'), ('iteration.completed', 'Iteration completed'), ('risk.created', 'Risk created'), ('risk.exposure_changed', 'Risk exposure changed'), ('milestone.due', 'Milestone due'), ('phase.gate_requested', 'Phase gate requested'), ('custom', 'Custom event')], max_length=40)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='match (all/any) + clauses. Empty = always matches.')),
                ('action_type', models.CharField(choices=[('notify', 'Send notification'), ('field_update', 'Update a field'), ('webhook', 'Call a webhook'), ('gate_transition', 'Request a gate transition')], max_length=30)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Action params (notify: recipients/message; webhook: url; field_update: target/field/value; gate_transition: target/to).')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('matched', 'Matched — action dispatched'), ('skipped', 'Skipped — condition not met'), ('failed', 'Failed — dispatch error')], max_length=10)),
                ('action_type', models.CharField(blank=True, max_length=30)),
                ('action_result', models.JSONField(blank=True, default=dict, help_text='Resolved action (templated config) + dispatch outcome.')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['tenant', 'trigger', 'is_active'], name='integration_tenant__bade1e_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['rule', 'status'], name='integration_rule_id_85a26a_idx'),
        ),
    ]
