# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_alter_customuser_role_alter_teaminvitation_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodologyComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "methodologies",
                    models.JSONField(
                        default=list, help_text="List of methodologies being compared"
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(default=list, help_text="Comparison criteria"),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methodology_comparisons",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Methodology Comparison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MethodologyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("methodology", models.CharField(max_length=50)),
                (
                    "period",
                    models.CharField(help_text="e.g., 2026-Q1, 2026-02", max_length=20),
                ),
                ("project_count", models.IntegerField(default=0)),
                ("completed_count", models.IntegerField(default=0)),
                ("on_time_percentage", models.FloatField(blank=True, null=True)),
                ("on_budget_percentage", models.FloatField(blank=True, null=True)),
                ("average_duration_days", models.FloatField(blank=True, null=True)),
                ("team_satisfaction", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methodology_metrics",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Methodology Metrics",
                "verbose_name_plural": "Methodology Metrics",
                "ordering": ["-period", "methodology"],
                "unique_together": {("company", "methodology", "period")},
            },
        ),
    ]
