import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Loader2, Activity, AlertTriangle, RefreshCw } from "lucide-react";
const BASE = (id: string) => `/api/v1/projects/${id}/sixsigma`;
const SixSigmaSPC = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [charts, setCharts] = useState<any[]>([]); const [violations, setViolations] = useState<Record<number, any[]>>({}); const [loading, setLoading] = useState(true); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` };
  const fetchData = async () => { try { const cRes = await fetch(`${BASE(id!)}/control-charts/`, { headers }); if (cRes.ok) { const d = await cRes.json(); const chartList = Array.isArray(d) ? d : d.results || []; setCharts(chartList); const vMap: Record<number, any[]> = {}; for (const c of chartList) { try { const vRes = await fetch(`${BASE(id!)}/control-charts/${c.id}/violations/`, { headers }); if (vRes.ok) { const vd = await vRes.json(); vMap[c.id] = Array.isArray(vd) ? vd : vd.results || vd.violations || []; } } catch {} } setViolations(vMap); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const totalViolations = Object.values(violations).reduce((s, v) => s + v.length, 0);
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><Activity className="h-6 w-6 text-purple-500" /><h1 className="text-2xl font-bold">Statistical Process Control</h1></div><Button variant="outline" onClick={fetchData} className="gap-2"><RefreshCw className="h-4 w-4" /> {pt("Refresh")}</Button></div>
    <div className="grid grid-cols-3 gap-4"><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Control Charts</p><p className="text-2xl font-bold">{charts.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Total Violations</p><p className={`text-2xl font-bold ${totalViolations > 0 ? "text-red-600" : "text-green-600"}`}>{totalViolations}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">In Control</p><p className="text-2xl font-bold text-green-600">{charts.filter(c => !(violations[c.id]?.length)).length}/{charts.length}</p></CardContent></Card></div>
    {charts.length === 0 ? <Card className="p-8 text-center text-muted-foreground">No control charts. Create charts first.</Card> : charts.map(c => { const v = violations[c.id] || []; return (<Card key={c.id} className={v.length > 0 ? "border-red-200" : ""}><CardHeader className="pb-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><CardTitle className="text-base">{c.title}</CardTitle><Badge variant="outline" className="text-xs">{c.chart_type?.replace("_", " ")}</Badge>{v.length > 0 ? <Badge variant="destructive" className="text-xs">{v.length} violations</Badge> : <Badge className="text-xs bg-green-100 text-green-700">In Control</Badge>}</div></div></CardHeader><CardContent>{v.length === 0 ? <p className="text-sm text-green-600">Process is stable and in control</p> : (<div className="space-y-1">{v.map((vi: any, i: number) => (<div key={i} className="flex items-center gap-2 text-sm p-2 bg-red-50 rounded"><AlertTriangle className="h-3.5 w-3.5 text-red-500 flex-shrink-0" /><span>{vi.description || vi.rule || vi.type || `Violation at value ${vi.value}`}</span>{vi.timestamp && <span className="text-xs text-muted-foreground ml-auto">{vi.timestamp}</span>}</div>))}</div>)}</CardContent></Card>); })}
  </div></div>);
};
export default SixSigmaSPC;
