import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Loader2, Plus, LineChart, Pencil, Trash2, RefreshCw, Gauge, AlertTriangle } from "lucide-react"; import { toast } from "sonner";
const BASE = (id: string) => `/api/v1/projects/${id}/sixsigma`;
const SixSigmaControlChart = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [charts, setCharts] = useState<any[]>([]); const [dataPoints, setDataPoints] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [dialogOpen, setDialogOpen] = useState(false); const [dialogType, setDialogType] = useState<"chart"|"data">("chart"); const [editing, setEditing] = useState<any>(null); const [submitting, setSubmitting] = useState(false); const [cForm, setCForm] = useState({ name: "", chart_type: "xbar_r", metric_name: "", ucl: "", lcl: "", center_line: "" }); const [dForm, setDForm] = useState({ chart: "", value: "", date: new Date().toISOString().split("T")[0] }); const [capability, setCapability] = useState<Record<number, any>>({}); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` }; const jsonHeaders = { ...headers, "Content-Type": "application/json" };
  const fetchData = async () => { try { const [cRes, dRes] = await Promise.all([fetch(`${BASE(id!)}/control-charts/`, { headers }), fetch(`${BASE(id!)}/chart-data/`, { headers })]); if (cRes.ok) { const d = await cRes.json(); setCharts(Array.isArray(d) ? d : d.results || []); } if (dRes.ok) { const d = await dRes.json(); setDataPoints(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const openCreateChart = () => { setDialogType("chart"); setEditing(null); setCForm({ name: "", chart_type: "xbar_r", metric_name: "", ucl: "", lcl: "", center_line: "" }); setDialogOpen(true); };
  const openAddData = (chartId: number) => { setDialogType("data"); setEditing(null); setDForm({ chart: String(chartId), value: "", date: new Date().toISOString().split("T")[0] }); setDialogOpen(true); };
  const saveChart = async () => { if (!cForm.name) { toast.error("Naam verplicht"); return; } setSubmitting(true); try { const body: any = { name: cForm.name, chart_type: cForm.chart_type, metric_name: cForm.metric_name }; if (cForm.ucl) body.ucl = parseFloat(cForm.ucl); if (cForm.lcl) body.lcl = parseFloat(cForm.lcl); if (cForm.center_line) body.center_line = parseFloat(cForm.center_line); const url = editing ? `${BASE(id!)}/control-charts/${editing.id}/` : `${BASE(id!)}/control-charts/`; const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: jsonHeaders, body: JSON.stringify(body) }); if (r.ok) { toast.success(pt("Saved")); setDialogOpen(false); fetchData(); } else toast.error(pt("Save failed")); } catch { toast.error(pt("Save failed")); } finally { setSubmitting(false); } };
  const addDataPoint = async () => { if (!dForm.value) { toast.error("Waarde verplicht"); return; } setSubmitting(true); try { const r = await fetch(`${BASE(id!)}/control-charts/${dForm.chart}/add_data_point/`, { method: "POST", headers: jsonHeaders, body: JSON.stringify({ value: parseFloat(dForm.value), date: dForm.date }) }); if (r.ok) { toast.success("Data point toegevoegd"); setDialogOpen(false); fetchData(); } else toast.error("Toevoegen mislukt"); } catch { toast.error("Toevoegen mislukt"); } finally { setSubmitting(false); } };
  const recalculate = async (chartId: number) => { try { const r = await fetch(`${BASE(id!)}/control-charts/${chartId}/recalculate_limits/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Limieten herberekend"); fetchData(); } } catch {} };
  const computeCapability = async (chartId: number) => { try { const r = await fetch(`${BASE(id!)}/control-charts/${chartId}/capability/`, { method: "POST", headers: jsonHeaders }); const data = await r.json(); if (r.ok) { setCapability(prev => ({ ...prev, [chartId]: data })); toast.success(`Cpk ${data.cpk ?? "—"} · ${data.sigma_level ?? "—"}σ`); } else if (data.code === "insufficient_data") { toast.error(pt("Need ≥2 data points and a spec limit (USL/LSL) to compute capability")); } else toast.error(pt("Capability failed")); } catch { toast.error(pt("Capability failed")); } };
  const detectSpecialCauses = async (chartId: number) => { try { const r = await fetch(`${BASE(id!)}/control-charts/${chartId}/detect_special_causes/`, { method: "POST", headers: jsonHeaders }); const data = await r.json(); if (r.ok) { if (data.in_control) toast.success(pt("In control — no special causes")); else toast.warning(`${data.flagged_count} ${pt("special-cause signal(s)")}`); fetchData(); } else toast.error(pt("Detection failed")); } catch { toast.error(pt("Detection failed")); } };
  const deleteChart = async (cId: number) => { if (!confirm("Verwijderen?")) return; try { await fetch(`${BASE(id!)}/control-charts/${cId}/`, { method: "DELETE", headers }); fetchData(); } catch {} };
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><LineChart className="h-6 w-6 text-indigo-500" /><h1 className="text-2xl font-bold">Control Charts</h1><Badge variant="outline">{charts.length}</Badge></div><Button onClick={openCreateChart} className="gap-2"><Plus className="h-4 w-4" /> {pt("Add")}</Button></div>
    {charts.length === 0 ? <Card className="p-8 text-center"><LineChart className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><h3 className="text-lg font-semibold">No control charts yet</h3></Card> : charts.map(c => {
      const cData = dataPoints.filter(d => d.chart === c.id).sort((a: any, b: any) => new Date(a.date).getTime() - new Date(b.date).getTime());
      const ucl = c.ucl; const lcl = c.lcl; const cl = c.center_line;
      return (<Card key={c.id}><CardHeader className="pb-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><CardTitle>{c.name}</CardTitle><Badge variant="outline" className="text-xs">{c.chart_type_display || c.chart_type?.replace("_", " ")}</Badge></div><div className="flex gap-1"><Button variant="outline" size="sm" onClick={() => openAddData(c.id)} className="gap-1 text-xs"><Plus className="h-3 w-3" /> Data</Button><Button variant="outline" size="sm" onClick={() => computeCapability(c.id)} className="gap-1 text-xs"><Gauge className="h-3.5 w-3.5" /> Cpk</Button><Button variant="outline" size="sm" onClick={() => detectSpecialCauses(c.id)} className="gap-1 text-xs"><AlertTriangle className="h-3.5 w-3.5" /> Signals</Button><Button variant="ghost" size="sm" onClick={() => recalculate(c.id)}><RefreshCw className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => deleteChart(c.id)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></div></div></CardHeader>
        <CardContent>
          <div className="flex gap-4 text-sm mb-3">{ucl != null && <span>UCL: <strong className="text-red-500">{ucl}</strong></span>}{cl != null && <span>CL: <strong>{cl}</strong></span>}{lcl != null && <span>LCL: <strong className="text-blue-500">{lcl}</strong></span>}<span className="text-muted-foreground">{cData.length} data points</span></div>
          {capability[c.id] && (<div className="mb-3 grid grid-cols-3 md:grid-cols-6 gap-2 text-xs">
            {[["Cp", capability[c.id].cp], ["Cpk", capability[c.id].cpk], ["Pp", capability[c.id].pp], ["Ppk", capability[c.id].ppk], ["Sigma", capability[c.id].sigma_level], ["DPMO", capability[c.id].dpmo]].map(([k, v]) => (
              <div key={k as string} className={`p-2 rounded border ${k === "Cpk" && typeof v === "number" ? (v >= 1.33 ? "bg-green-50" : "bg-amber-50") : ""}`}><p className="text-muted-foreground">{k}</p><p className="font-bold">{v ?? "—"}</p></div>
            ))}
          </div>)}
          {cData.length > 0 && (<div className="relative h-32 border rounded p-2">
            {(() => { const vals = cData.map((d: any) => d.value); const min = Math.min(...vals, lcl || Infinity); const max = Math.max(...vals, ucl || -Infinity); const range = max - min || 1; const h = 120; const w = Math.max(cData.length * 20, 200); return (<div className="overflow-x-auto"><svg width={w} height={h} className="text-xs">
              {ucl != null && <line x1="0" y1={h - ((ucl - min) / range) * h} x2={w} y2={h - ((ucl - min) / range) * h} stroke="red" strokeDasharray="4" strokeWidth="1" />}
              {lcl != null && <line x1="0" y1={h - ((lcl - min) / range) * h} x2={w} y2={h - ((lcl - min) / range) * h} stroke="blue" strokeDasharray="4" strokeWidth="1" />}
              {cl != null && <line x1="0" y1={h - ((cl - min) / range) * h} x2={w} y2={h - ((cl - min) / range) * h} stroke="green" strokeDasharray="2" strokeWidth="1" />}
              <polyline fill="none" stroke="#6366f1" strokeWidth="1.5" points={cData.map((d: any, i: number) => `${i * 20 + 10},${h - ((d.value - min) / range) * h}`).join(" ")} />
              {cData.map((d: any, i: number) => { const y = h - ((d.value - min) / range) * h; const oob = d.is_violation || (ucl != null && d.value > ucl) || (lcl != null && d.value < lcl); return <circle key={i} cx={i * 20 + 10} cy={y} r={oob ? 4 : 2.5} fill={oob ? "red" : "#6366f1"}><title>{d.is_violation && d.violation_rule ? d.violation_rule : `${d.value}`}</title></circle>; })}
            </svg></div>); })()}
          </div>)}
        </CardContent>
      </Card>);
    })}
  </div>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>{dialogType === "chart" ? (editing ? "Edit" : "Add") + " Control Chart" : "Add Data Point"}</DialogTitle></DialogHeader>
    {dialogType === "chart" ? (<div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>{pt("Name")} *</Label><Input value={cForm.name} onChange={(e) => setCForm({ ...cForm, name: e.target.value })} /></div><div className="space-y-2"><Label>Chart Type</Label><Select value={cForm.chart_type} onValueChange={(v) => setCForm({ ...cForm, chart_type: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="i_mr">I-MR (Individuals)</SelectItem><SelectItem value="xbar_r">X-bar R</SelectItem><SelectItem value="xbar_s">X-bar S</SelectItem><SelectItem value="p">P Chart (Proportion)</SelectItem><SelectItem value="np">NP Chart</SelectItem><SelectItem value="c">C Chart (Count)</SelectItem><SelectItem value="u">U Chart</SelectItem></SelectContent></Select></div></div><div className="space-y-2"><Label>Metric Name</Label><Input value={cForm.metric_name} onChange={(e) => setCForm({ ...cForm, metric_name: e.target.value })} /></div><div className="grid grid-cols-3 gap-3"><div className="space-y-2"><Label>UCL</Label><Input type="number" value={cForm.ucl} onChange={(e) => setCForm({ ...cForm, ucl: e.target.value })} /></div><div className="space-y-2"><Label>Center Line</Label><Input type="number" value={cForm.center_line} onChange={(e) => setCForm({ ...cForm, center_line: e.target.value })} /></div><div className="space-y-2"><Label>LCL</Label><Input type="number" value={cForm.lcl} onChange={(e) => setCForm({ ...cForm, lcl: e.target.value })} /></div></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={saveChart} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Save")}</Button></div></div>) : (<div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Value *</Label><Input type="number" value={dForm.value} onChange={(e) => setDForm({ ...dForm, value: e.target.value })} /></div><div className="space-y-2"><Label>Date</Label><Input type="date" value={dForm.date} onChange={(e) => setDForm({ ...dForm, date: e.target.value })} /></div></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={addDataPoint} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Add")}</Button></div></div>)}
  </DialogContent></Dialog></div>);
};
export default SixSigmaControlChart;
