import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Loader2, Plus, FlagTriangleRight, Pencil, Trash2, CheckCircle2, BadgeEuro, ShieldCheck, XCircle } from "lucide-react"; import { toast } from "sonner";
const BASE = (id: string) => `/api/v1/projects/${id}/sixsigma`;
const blankForm = { initial_sigma: "", final_sigma: "", initial_defect_rate: "", final_defect_rate: "", projected_savings: "", realized_savings: "", total_project_cost: "", lessons_learned: "", best_practices: "", recommendations: "", closure_date: "", handover_completed: false, training_completed: false, documentation_completed: false };
const SixSigmaClosure = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [submitting, setSubmitting] = useState(false); const [form, setForm] = useState({ ...blankForm }); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` }; const jsonHeaders = { ...headers, "Content-Type": "application/json" };
  const [savings, setSavings] = useState<any[]>([]); const [savingsDialog, setSavingsDialog] = useState(false); const [sForm, setSForm] = useState({ title: "", category: "hard", claimed_amount: "", basis: "" });
  const fetchData = async () => { try { const [r, sRes] = await Promise.all([fetch(`${BASE(id!)}/closure/`, { headers }), fetch(`${BASE(id!)}/savings-validations/`, { headers })]); if (r.ok) { const d = await r.json(); setItems(Array.isArray(d) ? d : d.results || []); } if (sRes.ok) { const d = await sRes.json(); setSavings(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const createSaving = async () => { if (!sForm.title || !sForm.claimed_amount || isNaN(Number(sForm.claimed_amount))) { toast.error(pt("Title and claimed amount are required")); return; } try { const r = await fetch(`${BASE(id!)}/savings-validations/`, { method: "POST", headers: jsonHeaders, body: JSON.stringify({ title: sForm.title, category: sForm.category, claimed_amount: Number(sForm.claimed_amount), basis: sForm.basis }) }); if (r.ok) { toast.success(pt("Saved")); setSavingsDialog(false); setSForm({ title: "", category: "hard", claimed_amount: "", basis: "" }); fetchData(); } else toast.error(pt("Save failed")); } catch { toast.error(pt("Save failed")); } };
  const signOffSaving = async (sId: number) => { try { const r = await fetch(`${BASE(id!)}/savings-validations/${sId}/sign_off/`, { method: "POST", headers: jsonHeaders, body: JSON.stringify({}) }); if (r.ok) { toast.success(pt("Champion signed off")); fetchData(); } else toast.error(pt("Sign-off failed")); } catch { toast.error(pt("Sign-off failed")); } };
  const validateSaving = async (sId: number) => { try { const r = await fetch(`${BASE(id!)}/savings-validations/${sId}/validate/`, { method: "POST", headers: jsonHeaders, body: JSON.stringify({}) }); const data = await r.json().catch(() => ({})); if (r.ok) { toast.success(pt("Benefit recognised")); fetchData(); } else if (data.code === "champion_signoff_required") { toast.error(pt("The Champion must sign off before this saving can be validated")); } else toast.error(pt("Validation failed")); } catch { toast.error(pt("Validation failed")); } };
  const rejectSaving = async (sId: number) => { const reason = prompt(pt("Rejection reason")) || ""; try { const r = await fetch(`${BASE(id!)}/savings-validations/${sId}/reject/`, { method: "POST", headers: jsonHeaders, body: JSON.stringify({ rejection_reason: reason }) }); if (r.ok) { toast.success(pt("Rejected")); fetchData(); } } catch {} };
  const openCreate = () => { setEditing(null); setForm({ ...blankForm }); setDialogOpen(true); };
  const openEdit = (i: any) => { setEditing(i); setForm({ initial_sigma: String(i.initial_sigma ?? ""), final_sigma: String(i.final_sigma ?? ""), initial_defect_rate: String(i.initial_defect_rate ?? ""), final_defect_rate: String(i.final_defect_rate ?? ""), projected_savings: String(i.projected_savings ?? ""), realized_savings: String(i.realized_savings ?? ""), total_project_cost: i.total_project_cost != null ? String(i.total_project_cost) : "", lessons_learned: i.lessons_learned || "", best_practices: i.best_practices || "", recommendations: i.recommendations || "", closure_date: i.closure_date?.split("T")[0] || "", handover_completed: i.handover_completed || false, training_completed: i.training_completed || false, documentation_completed: i.documentation_completed || false }); setDialogOpen(true); };
  const handleSave = async () => {
    const required: [string, string][] = [["initial_sigma", form.initial_sigma], ["final_sigma", form.final_sigma], ["initial_defect_rate", form.initial_defect_rate], ["final_defect_rate", form.final_defect_rate], ["projected_savings", form.projected_savings], ["realized_savings", form.realized_savings]];
    for (const [name, val] of required) { if (val === "" || isNaN(Number(val))) { toast.error(`${name} ${pt("is required")}`); return; } }
    if (!form.lessons_learned) { toast.error(pt("Lessons learned is required")); return; }
    if (!form.closure_date) { toast.error(pt("Closure date is required")); return; }
    setSubmitting(true);
    try {
      const body: any = {
        initial_sigma: Number(form.initial_sigma), final_sigma: Number(form.final_sigma),
        initial_defect_rate: Number(form.initial_defect_rate), final_defect_rate: Number(form.final_defect_rate),
        projected_savings: Number(form.projected_savings), realized_savings: Number(form.realized_savings),
        lessons_learned: form.lessons_learned, best_practices: form.best_practices, recommendations: form.recommendations,
        closure_date: form.closure_date, handover_completed: form.handover_completed,
        training_completed: form.training_completed, documentation_completed: form.documentation_completed,
      };
      if (form.total_project_cost !== "" && !isNaN(Number(form.total_project_cost))) body.total_project_cost = Number(form.total_project_cost);
      const url = editing ? `${BASE(id!)}/closure/${editing.id}/` : `${BASE(id!)}/closure/`;
      const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: jsonHeaders, body: JSON.stringify(body) });
      if (r.ok) { toast.success(pt("Saved")); setDialogOpen(false); fetchData(); } else toast.error(pt("Save failed"));
    } catch { toast.error(pt("Save failed")); } finally { setSubmitting(false); }
  };
  const approve = async (cId: number) => { try { const r = await fetch(`${BASE(id!)}/closure/${cId}/approve/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success(pt("Project closed")); fetchData(); } } catch {} };
  const handleDelete = async (cId: number) => { if (!confirm(pt("Are you sure you want to delete this?"))) return; try { await fetch(`${BASE(id!)}/closure/${cId}/`, { method: "DELETE", headers }); fetchData(); } catch {} };
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><FlagTriangleRight className="h-6 w-6 text-green-500" /><h1 className="text-2xl font-bold">Project Closure</h1></div><Button onClick={openCreate} className="gap-2"><Plus className="h-4 w-4" /> {pt("Add")}</Button></div>

    {/* Savings validation ledger — claimed savings only count once the Champion signs off */}
    <Card><CardContent className="p-5">
      <div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><BadgeEuro className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">{pt("Savings Validation")}</h2><Badge variant="outline">€{savings.filter(s => s.status === "validated").reduce((a, s) => a + Number(s.recognized_amount || 0), 0).toLocaleString()} {pt("recognised")}</Badge></div><Button variant="outline" size="sm" onClick={() => setSavingsDialog(true)} className="gap-1"><Plus className="h-3.5 w-3.5" /> {pt("Claim")}</Button></div>
      {savings.length === 0 ? <p className="text-sm text-muted-foreground">{pt("No savings claimed yet")}</p> : (<div className="space-y-2">{savings.map(s => (
        <div key={s.id} className="flex items-center justify-between p-2 border rounded text-sm">
          <div className="min-w-0"><p className="font-medium truncate">{s.title}</p><p className="text-xs text-muted-foreground capitalize">{s.category_display || s.category} · {pt("claimed")} €{Number(s.claimed_amount).toLocaleString()}{s.validated_amount != null && ` · ${pt("validated")} €${Number(s.validated_amount).toLocaleString()}`}</p></div>
          <div className="flex items-center gap-1">
            <Badge variant={s.status === "validated" ? "default" : s.status === "rejected" ? "destructive" : "secondary"} className="text-xs capitalize">{s.status_display || s.status}</Badge>
            {s.champion_signed_off ? <ShieldCheck className="h-4 w-4 text-emerald-600" /> : <Button variant="outline" size="sm" className="h-7 text-xs gap-1" onClick={() => signOffSaving(s.id)}><ShieldCheck className="h-3 w-3" /> {pt("Sign off")}</Button>}
            {s.status !== "validated" && s.status !== "rejected" && <><Button variant="outline" size="sm" className="h-7 text-xs gap-1 text-emerald-600" onClick={() => validateSaving(s.id)}><CheckCircle2 className="h-3 w-3" /> {pt("Validate")}</Button><Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => rejectSaving(s.id)}><XCircle className="h-3.5 w-3.5 text-destructive" /></Button></>}
          </div>
        </div>
      ))}</div>)}
    </CardContent></Card>
    {items.length === 0 ? <Card className="p-8 text-center"><FlagTriangleRight className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><h3 className="text-lg font-semibold">No closure reports yet</h3></Card> : (<div className="space-y-3">{items.map(i => (<Card key={i.id}><CardContent className="p-5"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><span className="font-semibold text-lg">{pt("Closure")} — {i.closure_date}</span>{i.approved_by_name && <Badge variant="default" className="text-xs">{pt("Approved")}</Badge>}</div><div className="flex gap-1"><Button variant="outline" size="sm" onClick={() => approve(i.id)} className="gap-1 text-green-600"><CheckCircle2 className="h-3.5 w-3.5" /> Approve Closure</Button><Button variant="ghost" size="sm" onClick={() => openEdit(i)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => handleDelete(i.id)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></div></div>
      <div className="grid grid-cols-3 gap-3 mb-3 text-sm"><div><p className="text-xs text-muted-foreground">Sigma</p><p>{i.initial_sigma} → {i.final_sigma}</p></div><div><p className="text-xs text-muted-foreground">Defect Rate</p><p>{i.initial_defect_rate} → {i.final_defect_rate}</p></div><div><p className="text-xs text-muted-foreground">Realized Savings</p><p>€{parseFloat(i.realized_savings || 0).toLocaleString()}</p></div></div>
      <div className="grid grid-cols-3 gap-3 mb-3">{[["documentation_completed", "Documentation"], ["training_completed", "Training"], ["handover_completed", "Handover"]].map(([k, label]) => (<div key={k} className="flex items-center gap-2"><div className={`h-5 w-5 rounded-full flex items-center justify-center ${i[k] ? "bg-green-500" : "bg-gray-300"}`}><CheckCircle2 className="h-3 w-3 text-white" /></div><span className="text-sm">{label}</span></div>))}</div>
      {i.lessons_learned && <div className="mb-2"><p className="text-xs font-semibold text-muted-foreground">Lessons Learned</p><p className="text-sm">{i.lessons_learned}</p></div>}
      {i.recommendations && <div><p className="text-xs font-semibold text-muted-foreground">Recommendations</p><p className="text-sm">{i.recommendations}</p></div>}
    </CardContent></Card>))}</div>)}
  </div>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-w-lg max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing ? pt("Edit") : pt("Add")} Closure Report</DialogTitle></DialogHeader><div className="space-y-4">
    <div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Initial Sigma *</Label><Input type="number" value={form.initial_sigma} onChange={(e) => setForm({ ...form, initial_sigma: e.target.value })} /></div><div className="space-y-2"><Label>Final Sigma *</Label><Input type="number" value={form.final_sigma} onChange={(e) => setForm({ ...form, final_sigma: e.target.value })} /></div></div>
    <div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Initial Defect Rate *</Label><Input type="number" value={form.initial_defect_rate} onChange={(e) => setForm({ ...form, initial_defect_rate: e.target.value })} /></div><div className="space-y-2"><Label>Final Defect Rate *</Label><Input type="number" value={form.final_defect_rate} onChange={(e) => setForm({ ...form, final_defect_rate: e.target.value })} /></div></div>
    <div className="grid grid-cols-3 gap-4"><div className="space-y-2"><Label>Projected Savings (€) *</Label><Input type="number" value={form.projected_savings} onChange={(e) => setForm({ ...form, projected_savings: e.target.value })} /></div><div className="space-y-2"><Label>Realized Savings (€) *</Label><Input type="number" value={form.realized_savings} onChange={(e) => setForm({ ...form, realized_savings: e.target.value })} /></div><div className="space-y-2"><Label>Project Cost (€)</Label><Input type="number" value={form.total_project_cost} onChange={(e) => setForm({ ...form, total_project_cost: e.target.value })} /></div></div>
    <div className="space-y-2"><Label>Closure Date *</Label><Input type="date" value={form.closure_date} onChange={(e) => setForm({ ...form, closure_date: e.target.value })} /></div>
    <div className="space-y-2"><Label>Lessons Learned *</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={form.lessons_learned} onChange={(e) => setForm({ ...form, lessons_learned: e.target.value })} /></div>
    <div className="space-y-2"><Label>Best Practices</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={form.best_practices} onChange={(e) => setForm({ ...form, best_practices: e.target.value })} /></div>
    <div className="space-y-2"><Label>Recommendations</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={form.recommendations} onChange={(e) => setForm({ ...form, recommendations: e.target.value })} /></div>
    <div className="flex gap-6 flex-wrap"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.documentation_completed} onChange={(e) => setForm({ ...form, documentation_completed: e.target.checked })} /> Documentation Complete</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.training_completed} onChange={(e) => setForm({ ...form, training_completed: e.target.checked })} /> Training Complete</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.handover_completed} onChange={(e) => setForm({ ...form, handover_completed: e.target.checked })} /> Handover Complete</label></div>
    <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={handleSave} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Save")}</Button></div>
  </div></DialogContent></Dialog>
  <Dialog open={savingsDialog} onOpenChange={setSavingsDialog}><DialogContent><DialogHeader><DialogTitle>{pt("Claim a Saving")}</DialogTitle></DialogHeader><div className="space-y-4">
    <div className="space-y-2"><Label>{pt("Title")} *</Label><Input value={sForm.title} onChange={(e) => setSForm({ ...sForm, title: e.target.value })} /></div>
    <div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>{pt("Category")}</Label><select className="w-full px-3 py-2 border rounded-md bg-background text-sm" value={sForm.category} onChange={(e) => setSForm({ ...sForm, category: e.target.value })}><option value="hard">Hard Savings (P&L)</option><option value="soft">Soft Savings</option><option value="cost_avoidance">Cost Avoidance</option><option value="revenue">Revenue Increase</option><option value="working_capital">Working Capital</option></select></div><div className="space-y-2"><Label>{pt("Claimed Amount")} (€) *</Label><Input type="number" value={sForm.claimed_amount} onChange={(e) => setSForm({ ...sForm, claimed_amount: e.target.value })} /></div></div>
    <div className="space-y-2"><Label>{pt("Basis")}</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={sForm.basis} onChange={(e) => setSForm({ ...sForm, basis: e.target.value })} /></div>
    <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setSavingsDialog(false)}>{pt("Cancel")}</Button><Button onClick={createSaving}>{pt("Save")}</Button></div>
  </div></DialogContent></Dialog></div>);
};
export default SixSigmaClosure;
