import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { Progress } from "@/components/ui/progress"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Loader2, Monitor, RefreshCw, TrendingUp, TrendingDown } from "lucide-react";
const BASE = (id: string) => `/api/v1/projects/${id}/sixsigma`;
const SixSigmaMonitoring = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [baselines, setBaselines] = useState<any[]>([]); const [charts, setCharts] = useState<any[]>([]); const [tollgates, setTollgates] = useState<any[]>([]); const [loading, setLoading] = useState(true); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` };
  const fetchData = async () => { try { const [bRes, cRes, tRes] = await Promise.all([fetch(`${BASE(id!)}/baseline/`, { headers }), fetch(`${BASE(id!)}/control-charts/`, { headers }), fetch(`${BASE(id!)}/tollgates/`, { headers })]); if (bRes.ok) { const d = await bRes.json(); setBaselines(Array.isArray(d) ? d : d.results || []); } if (cRes.ok) { const d = await cRes.json(); setCharts(Array.isArray(d) ? d : d.results || []); } if (tRes.ok) { const d = await tRes.json(); setTollgates(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const approvedPhases = tollgates.filter(t => t.status === "approved").length;
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><Monitor className="h-6 w-6 text-cyan-500" /><h1 className="text-2xl font-bold">Project Monitoring</h1></div><Button variant="outline" onClick={fetchData} className="gap-2"><RefreshCw className="h-4 w-4" /> {pt("Refresh")}</Button></div>
    <div className="grid grid-cols-3 gap-4"><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Tollgates Passed</p><p className="text-2xl font-bold">{approvedPhases}/{tollgates.length}</p><Progress value={tollgates.length > 0 ? (approvedPhases / tollgates.length) * 100 : 0} className="h-2 mt-2" /></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Metrics Tracked</p><p className="text-2xl font-bold">{baselines.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">Control Charts</p><p className="text-2xl font-bold">{charts.length}</p></CardContent></Card></div>

    <Card><CardHeader><CardTitle>Metric Performance</CardTitle></CardHeader><CardContent>{baselines.length === 0 ? <p className="text-muted-foreground text-sm">No metrics to monitor</p> : (<div className="space-y-3">{baselines.map(b => { const improving = b.current_value && b.baseline_value && b.target_value ? (Math.abs(b.current_value - b.target_value) < Math.abs(b.baseline_value - b.target_value)) : null; return (<div key={b.id} className="flex items-center justify-between p-3 border rounded"><div className="flex items-center gap-3"><span className="font-medium text-sm">{b.metric_name}</span>{improving != null && (improving ? <TrendingUp className="h-4 w-4 text-green-500" /> : <TrendingDown className="h-4 w-4 text-red-500" />)}</div><div className="flex items-center gap-4 text-sm"><span>Base: {b.baseline_value} {b.unit}</span><span className="font-bold text-blue-600">Now: {b.current_value || "—"} {b.unit}</span><span className="text-green-600">Target: {b.target_value} {b.unit}</span>{b.sigma_level && <Badge variant="outline" className="text-xs">σ {b.sigma_level}</Badge>}</div></div>); })}</div>)}</CardContent></Card>

    <Card><CardHeader><CardTitle>Phase Progress</CardTitle></CardHeader><CardContent>{tollgates.length === 0 ? <p className="text-muted-foreground text-sm">No tollgates. Initialize from DMAIC page.</p> : (<div className="flex gap-2">{tollgates.map(t => (<div key={t.id} className={`flex-1 p-3 rounded text-center border ${t.status === "approved" ? "bg-green-50 border-green-200" : t.status === "rejected" ? "bg-red-50 border-red-200" : "bg-muted"}`}><p className="font-semibold text-sm">{t.phase}</p><Badge variant={t.status === "approved" ? "default" : "secondary"} className="text-xs mt-1">{t.status}</Badge></div>))}</div>)}</CardContent></Card>
  </div></div>);
};
export default SixSigmaMonitoring;
