import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Loader2, Plus, ShieldCheck, CheckCircle2, XCircle, Pencil, Trash2 } from "lucide-react"; import { toast } from "sonner";
const BASE = (id: string) => `/api/v1/sixsigma/projects/${id}/sixsigma`;
const PHASES = ["define", "measure", "analyze", "improve", "control"];
const blankForm = { phase: "define", reviewer: "", scheduled_date: "", actual_date: "", status: "upcoming", deliverables_reviewed: "", findings: "", action_items: "", checklist_completed: false };
const SixSigmaTollgate = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [items, setItems] = useState<any[]>([]); const [users, setUsers] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [submitting, setSubmitting] = useState(false); const [form, setForm] = useState({ ...blankForm }); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` }; const jsonHeaders = { ...headers, "Content-Type": "application/json" };
  const fetchData = async () => { try { const [r, uR] = await Promise.all([fetch(`${BASE(id!)}/tollgates/`, { headers }), fetch(`/api/v1/auth/company-users/members/`, { headers })]); if (r.ok) { const d = await r.json(); setItems(Array.isArray(d) ? d : d.results || []); } if (uR.ok) { const d = await uR.json(); setUsers(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const initTollgates = async () => { try { const r = await fetch(`${BASE(id!)}/tollgates/initialize/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Tollgates geïnitialiseerd"); fetchData(); } } catch { toast.error("Initialiseren mislukt"); } };
  const openCreate = () => { setEditing(null); setForm({ ...blankForm }); setDialogOpen(true); };
  const openEdit = (i: any) => { setEditing(i); setForm({ phase: i.phase || "define", reviewer: i.reviewer != null ? String(i.reviewer) : "", scheduled_date: i.scheduled_date?.split("T")[0] || "", actual_date: i.actual_date?.split("T")[0] || "", status: i.status || "upcoming", deliverables_reviewed: i.deliverables_reviewed || "", findings: i.findings || "", action_items: i.action_items || "", checklist_completed: i.checklist_completed || false }); setDialogOpen(true); };
  const handleSave = async () => { if (!form.phase) { toast.error("Phase verplicht"); return; } setSubmitting(true); try {
    const body: any = { phase: form.phase, status: form.status, deliverables_reviewed: form.deliverables_reviewed, findings: form.findings, action_items: form.action_items, checklist_completed: form.checklist_completed };
    if (form.reviewer) body.reviewer = parseInt(form.reviewer); else body.reviewer = null;
    if (form.scheduled_date) body.scheduled_date = form.scheduled_date;
    if (form.actual_date) body.actual_date = form.actual_date;
    const url = editing ? `${BASE(id!)}/tollgates/${editing.id}/` : `${BASE(id!)}/tollgates/`;
    const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: jsonHeaders, body: JSON.stringify(body) });
    if (r.ok) { toast.success(pt("Saved")); setDialogOpen(false); fetchData(); } else toast.error(pt("Save failed"));
  } catch { toast.error(pt("Save failed")); } finally { setSubmitting(false); } };
  const approve = async (tId: number) => { try { const r = await fetch(`${BASE(id!)}/tollgates/${tId}/approve/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Goedgekeurd"); fetchData(); } } catch {} };
  const reject = async (tId: number) => { try { const r = await fetch(`${BASE(id!)}/tollgates/${tId}/reject/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Afgekeurd"); fetchData(); } } catch {} };
  const handleDelete = async (tId: number) => { if (!confirm(pt("Are you sure you want to delete this?"))) return; try { await fetch(`${BASE(id!)}/tollgates/${tId}/`, { method: "DELETE", headers }); fetchData(); } catch {} };
  const phaseColors: Record<string, string> = { define: "bg-blue-500", measure: "bg-green-500", analyze: "bg-yellow-500", improve: "bg-orange-500", control: "bg-red-500" };
  const statusColors: Record<string, string> = { upcoming: "bg-gray-100 text-gray-700", scheduled: "bg-blue-100 text-blue-700", in_review: "bg-amber-100 text-amber-700", passed: "bg-green-100 text-green-700", conditional: "bg-amber-100 text-amber-700", failed: "bg-red-100 text-red-700", rework: "bg-orange-100 text-orange-700" };
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-amber-500" /><h1 className="text-2xl font-bold">Tollgate Reviews</h1><Badge variant="outline">{items.length}</Badge></div><div className="flex gap-2">{items.length === 0 && <Button variant="outline" onClick={initTollgates}>Initialize DMAIC</Button>}<Button onClick={openCreate} className="gap-2"><Plus className="h-4 w-4" /> {pt("Add")}</Button></div></div>
    {items.length === 0 ? <Card className="p-8 text-center"><ShieldCheck className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><h3 className="text-lg font-semibold">No tollgate reviews yet</h3></Card> : (<div className="space-y-3">{items.map(i => (<Card key={i.id} className={i.status === "passed" ? "border-green-200" : i.status === "failed" ? "border-red-200" : ""}><CardContent className="p-4"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><div className={`h-6 w-6 rounded-full ${phaseColors[i.phase?.toLowerCase()] || "bg-gray-400"} flex items-center justify-center text-white text-xs font-bold`}>{i.phase?.charAt(0)?.toUpperCase()}</div><span className="font-semibold">{i.phase_display || i.phase}</span><Badge className={`text-xs ${statusColors[i.status] || ""}`}>{i.status_display || i.status}</Badge>{i.reviewer_name && <span className="text-xs text-muted-foreground">by {i.reviewer_name}</span>}</div><div className="flex gap-1">{!i.approved && <Button variant="outline" size="sm" onClick={() => approve(i.id)} className="gap-1 text-xs text-green-600"><CheckCircle2 className="h-3 w-3" /> Approve</Button>}<Button variant="outline" size="sm" onClick={() => reject(i.id)} className="gap-1 text-xs text-red-600"><XCircle className="h-3 w-3" /> Reject</Button><Button variant="ghost" size="sm" onClick={() => openEdit(i)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => handleDelete(i.id)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></div></div>{i.findings && <p className="text-sm"><strong>Findings:</strong> {i.findings}</p>}{i.action_items && <p className="text-sm text-muted-foreground"><strong>Action Items:</strong> {i.action_items}</p>}</CardContent></Card>))}</div>)}
  </div>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing ? pt("Edit") : pt("Add")} Tollgate Review</DialogTitle></DialogHeader><div className="space-y-4">
    <div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Phase *</Label><Select value={form.phase} onValueChange={(v) => setForm({ ...form, phase: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{PHASES.map(p => <SelectItem key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Reviewer</Label><Select value={form.reviewer || "none"} onValueChange={(v) => setForm({ ...form, reviewer: v === "none" ? "" : v })}><SelectTrigger><SelectValue placeholder={pt("Select reviewer")} /></SelectTrigger><SelectContent><SelectItem value="none">{pt("None")}</SelectItem>{users.map((u) => <SelectItem key={u.id} value={u.id.toString()}>{u.full_name || u.name || `${u.first_name || ""} ${u.last_name || ""}`.trim() || u.email}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={(v) => setForm({ ...form, status: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="upcoming">Upcoming</SelectItem><SelectItem value="scheduled">Scheduled</SelectItem><SelectItem value="in_review">In Review</SelectItem><SelectItem value="passed">Passed</SelectItem><SelectItem value="conditional">Conditional Pass</SelectItem><SelectItem value="failed">Failed</SelectItem><SelectItem value="rework">Rework Required</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Scheduled Date</Label><Input type="date" value={form.scheduled_date} onChange={(e) => setForm({ ...form, scheduled_date: e.target.value })} /></div></div>
    <div className="space-y-2"><Label>Actual Date</Label><Input type="date" value={form.actual_date} onChange={(e) => setForm({ ...form, actual_date: e.target.value })} /></div>
    <div className="space-y-2"><Label>Deliverables Reviewed</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.deliverables_reviewed} onChange={(e) => setForm({ ...form, deliverables_reviewed: e.target.value })} /></div>
    <div className="space-y-2"><Label>Findings</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.findings} onChange={(e) => setForm({ ...form, findings: e.target.value })} /></div>
    <div className="space-y-2"><Label>Action Items</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.action_items} onChange={(e) => setForm({ ...form, action_items: e.target.value })} /></div>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.checklist_completed} onChange={(e) => setForm({ ...form, checklist_completed: e.target.checked })} /> Checklist Completed</label>
    <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={handleSave} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Save")}</Button></div>
  </div></DialogContent></Dialog></div>);
};
export default SixSigmaTollgate;
