# Generated by Django 5.2.6 on 2026-06-04 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_workpolicy'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='When the card was last blocked (for aging/blocked-time tiles)', null=True),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='class_of_service',
            field=models.CharField(choices=[('standard', 'Standard'), ('expedite', 'Expedite'), ('fixed_date', 'Fixed Date'), ('intangible', 'Intangible')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='sle_days',
            field=models.IntegerField(blank=True, help_text='Service Level Expectation in days', null=True),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='kanban.kanbancolumn'),
        ),
        migrations.CreateModel(
            name='BlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_blocks_raised', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_events', to='kanban.kanbancard')),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='KaizenAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(choices=[('blocker', 'Recurring Blocker'), ('sle_breach', 'SLE Breach'), ('wip_breach', 'WIP Breach'), ('retro', 'Retrospective'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('dropped', 'Dropped')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kaizen_actions', to='kanban.kanbanboard')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_kaizen_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_kaizen_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_kaizen_actions', to='projects.project')),
                ('source_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaizen_actions', to='kanban.kanbancard')),
            ],
            options={
                'db_table': 'kanban_kaizen_action',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanCadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cadence_type', models.CharField(choices=[('replenishment', 'Replenishment'), ('standup', 'Daily Standup'), ('delivery_planning', 'Delivery Planning'), ('service_delivery_review', 'Service Delivery Review'), ('risk_review', 'Risk Review'), ('operations_review', 'Operations Review'), ('strategy_review', 'Strategy Review')], default='standup', max_length=40)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('on_demand', 'On Demand')], default='weekly', max_length=20)),
                ('day_of_week', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadences', to='kanban.kanbanboard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cadences', to='projects.project')),
            ],
            options={
                'db_table': 'kanban_cadence',
                'ordering': ['order', 'id'],
            },
        ),
    ]
