# Generated by Django 5.2.6 on 2026-06-04 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_programme', '0002_fix_programme_fk'),
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2ProgrammeBoardDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('authorize', 'Authorize'), ('start', 'Start'), ('stop', 'Stop'), ('defer', 'Defer')], max_length=12)),
                ('gate', models.CharField(blank=True, help_text='Programme gate / tranche this decision applies at.', max_length=100)),
                ('rationale', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_board_decisions', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_board_decisions', to='programs.program')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_decisions', to='p2_programme.p2programmeproject')),
            ],
            options={
                'verbose_name': 'P2 Programme Board Decision',
                'ordering': ['-decided_at'],
            },
        ),
    ]
