# Generated by Django 5.2.6 on 2026-06-04 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_task_product_task_work_package'),
        ('sixsigma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlchart',
            name='control_plan',
            field=models.ForeignKey(blank=True, help_text='The Control Plan this SPC chart monitors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_charts', to='sixsigma.controlplan'),
        ),
        migrations.AddField(
            model_name='hypothesistest',
            name='root_cause',
            field=models.ForeignKey(blank=True, help_text='The fishbone root cause this test sets out to verify', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypothesis_tests', to='sixsigma.fishbonecause'),
        ),
        migrations.CreateModel(
            name='SavingsValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hard', 'Hard Savings (P&L)'), ('soft', 'Soft Savings'), ('cost_avoidance', 'Cost Avoidance'), ('revenue', 'Revenue Increase'), ('working_capital', 'Working Capital')], default='hard', max_length=20)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('validated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount the Champion validated (may differ from claimed)', max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('basis', models.TextField(blank=True, help_text='How the saving was calculated')),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('under_review', 'Under Review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='claimed', max_length=20)),
                ('champion_signed_off', models.BooleanField(default=False)),
                ('champion_signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('finance_validated', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championed_savings', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_savings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_validations', to='projects.project')),
                ('solution', models.ForeignKey(blank=True, help_text='The improvement that produced this saving', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_validations', to='sixsigma.solution')),
            ],
            options={
                'verbose_name': 'Savings Validation',
                'verbose_name_plural': 'Savings Validations',
                'ordering': ['-created_at'],
            },
        ),
    ]
