# Generated by Django 5.2.6 on 2025-12-13 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agile_budget', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AgileEpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('must_have', 'Must Have'), ('should_have', 'Should Have'), ('could_have', 'Could Have'), ('wont_have', "Won't Have")], default='should_have', max_length=20)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_epics', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgileIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('velocity_committed', models.IntegerField(default=0)),
                ('velocity_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_iterations', to='projects.project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AgileBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('qa', 'QA'), ('infrastructure', 'Infrastructure'), ('tools', 'Tools'), ('training', 'Training'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agile.agilebudget')),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agile.agileiteration')),
            ],
            options={
                'ordering': ['-date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AgileBacklogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('story', 'User Story'), ('task', 'Task'), ('bug', 'Bug'), ('spike', 'Spike')], default='story', max_length=20)),
                ('priority', models.CharField(choices=[('must_have', 'Must Have'), ('should_have', 'Should Have'), ('could_have', 'Could Have'), ('wont_have', "Won't Have")], default='should_have', max_length=20)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='backlog', max_length=20)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_backlog', to='projects.project')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='agile.agileepic')),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='agile.agileiteration')),
            ],
            options={
                'ordering': ['order', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='AgileProductVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_statement', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('unique_value_proposition', models.TextField(blank=True)),
                ('success_criteria', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agile_vision', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AgileProductGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('deferred', 'Deferred')], default='planned', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='agile.agileproductvision')),
            ],
            options={
                'ordering': ['order', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='AgileRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iterations', models.ManyToManyField(blank=True, related_name='releases', to='agile.agileiteration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_releases', to='projects.project')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='AgileRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('iteration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='agile.agileiteration')),
            ],
        ),
        migrations.CreateModel(
            name='AgileRetroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('went_well', 'What Went Well'), ('to_improve', 'What to Improve'), ('action_item', 'Action Item')], max_length=20)),
                ('content', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_items_created', to=settings.AUTH_USER_MODEL)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agile.agileretrospective')),
            ],
            options={
                'ordering': ['-votes', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AgileUserPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('background', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('quote', models.TextField(blank=True)),
                ('avatar_color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_personas', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgileDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('yesterday', models.TextField(blank=True)),
                ('today', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_daily_updates', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='agile.agileiteration')),
            ],
            options={
                'ordering': ['-date', 'user__first_name'],
                'unique_together': {('iteration', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AgileTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('product_owner', 'Product Owner'), ('tech_lead', 'Tech Lead'), ('developer', 'Developer'), ('designer', 'Designer'), ('qa', 'QA Engineer'), ('devops', 'DevOps'), ('analyst', 'Business Analyst')], default='developer', max_length=50)),
                ('capacity_hours', models.IntegerField(default=40, help_text='Hours per week')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_team', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__first_name'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
