# Generated by Django 5.2.6 on 2026-02-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0001_initial'),
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionOfDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Definition of Done', max_length=200)),
                ('scope', models.CharField(choices=[('story', 'User Story'), ('iteration', 'Iteration'), ('release', 'Release'), ('project', 'Project')], default='story', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_dod', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Definitions of Done',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoDChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('backlog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dod_completions', to='agile.agilebacklogitem')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='agile.definitionofdone')),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dod_completions', to='agile.agileiteration')),
            ],
            options={
                'ordering': ['checklist_item'],
            },
        ),
        migrations.CreateModel(
            name='IterationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('stakeholders', models.TextField(blank=True, help_text='External stakeholders present')),
                ('demo_items', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('iteration_goal_achieved', models.BooleanField(default=False)),
                ('completed_story_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_reviews', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_reviews', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='agile.agileiteration')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('improvement', 'Improvement'), ('question', 'Question'), ('concern', 'Concern')], default='positive', max_length=20)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='agile.iterationreview')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
