# Generated by Django 5.2.6 on 2026-06-04 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_definitionofdone'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebacklogitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agilebacklogitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agileepic',
            name='product_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='agile.agileproductgoal'),
        ),
        migrations.CreateModel(
            name='AgileFlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip_limit', models.IntegerField(default=0, help_text='Max items in_progress at once. 0 = unlimited.')),
                ('target_cycle_time_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agile_flow_config', to='projects.project')),
            ],
            options={
                'db_table': 'agile_flow_config',
            },
        ),
        migrations.CreateModel(
            name='AgileDodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='agile.definitionofdone')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dod_entries', to='agile.agilebacklogitem')),
                ('met_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agile_dod_entry',
                'ordering': ['criterion__order', 'id'],
                'unique_together': {('item', 'criterion')},
            },
        ),
    ]
