# Generated by Django 5.2.6 on 2026-06-05 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_agilebacklogitem_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_name', models.CharField(max_length=150)),
                ('stakeholder_role', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-5 satisfaction score.', null=True)),
                ('feedback', models.TextField()),
                ('follow_up_action', models.TextField(blank=True, help_text='Optional action to feed back into the backlog.')),
                ('follow_up_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backlog_item', models.ForeignKey(blank=True, help_text='The shipped item this feedback is about (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_feedback', to='agile.agilebacklogitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_stakeholder_feedback', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_feedback', to='agile.agileiteration')),
            ],
            options={
                'db_table': 'agile_stakeholder_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
