# Generated by Django 5.2.6 on 2026-05-04 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_rename_bio_cred_user_active_idx_biometric_c_user_id_481b54_idx_and_more'),
        ('projects', '0012_manualmitigation_attachments_risk_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User report (AI Copilot / floating-button)'), ('auto-test-ci', 'Auto-test CI failure'), ('auto-test-runtime', 'Auto runtime exception'), ('agent-scan', 'Agent-detected (data-leak-hunter / pm-validator)')], default='user', max_length=32)),
                ('capture_method', models.CharField(choices=[('manual_form', 'Filled in form manually'), ('paste_clipboard', 'Pasted from clipboard'), ('upload', 'Uploaded file'), ('auto_browser', 'Browser auto-capture'), ('auto_mobile_shake', 'Mobile shake-to-report'), ('auto_ci', 'CI runner posted'), ('auto_runtime', 'Runtime exception handler')], default='manual_form', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reproduction_steps', models.TextField(blank=True, help_text='What did you do to make this happen?')),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True, help_text='Stack trace, console errors, HTTP response body, or test output')),
                ('environment', models.JSONField(blank=True, default=dict, help_text='Page URL, browser, OS, app-version, viewport, build-SHA, etc.')),
                ('category', models.CharField(choices=[('ui', 'UI / Frontend'), ('api', 'API / Backend'), ('mobile', 'Mobile App'), ('performance', 'Performance'), ('security', 'Security'), ('auth', 'Auth / Permissions'), ('data', 'Data / Database'), ('integration', 'Integration (Stripe / Tink / etc.)'), ('documentation', 'Documentation'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('classification', models.CharField(blank=True, choices=[('bug', 'Bug — code defect'), ('error', 'Error — runtime exception'), ('functionality', 'Functionality — works but wrong behaviour'), ('best-practice', 'Best-practice violation'), ('missing-feature', 'Missing feature / enhancement'), ('duplicate', 'Duplicate of another issue'), ('user-error', 'User error / not a bug'), ('not-applicable', 'Not applicable / out of scope')], db_index=True, max_length=32)),
                ('severity', models.CharField(blank=True, choices=[('blocker', 'Blocker'), ('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('trivial', 'Trivial')], db_index=True, max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('P0', 'P0 — fix immediately'), ('P1', 'P1 — next sprint'), ('P2', 'P2 — backlog'), ('P3', 'P3 — nice-to-have')], db_index=True, max_length=4)),
                ('agent_triage_result', models.JSONField(blank=True, default=dict, help_text='Full agent output: reasoning, confidence, suggested-fix-area, code-references, fingerprint for de-dup, etc.')),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('triaged_by', models.CharField(blank=True, help_text="'agent:issue-triage-validator' or auth.users.id of human triager", max_length=128)),
                ('reproduction_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('reproduction_result', models.CharField(choices=[('not-attempted', 'Not yet attempted'), ('reproduced', 'Reproduced consistently'), ('intermittent', 'Reproduced intermittently (flaky)'), ('cannot-reproduce', 'Cannot reproduce'), ('not-applicable', 'Reproduction not applicable'), ('already-fixed', 'Reproduces in older version, fixed in current'), ('needs-data', 'Needs production-like data sample')], default='not-attempted', max_length=32)),
                ('reproduction_log', models.JSONField(blank=True, default=list, help_text="List of {step, command, output, success} from agent's repro run; truncated to 4000 chars per output.")),
                ('status', models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging (agent running)'), ('needs-info', 'Needs more info from reporter'), ('accepted', 'Accepted'), ('in-progress', 'In progress'), ('resolved', 'Resolved'), ('wont-fix', "Won't fix"), ('duplicate', 'Duplicate'), ('closed', 'Closed')], db_index=True, default='new', max_length=24)),
                ('linked_pr_url', models.URLField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_product_issues', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(blank=True, help_text='Screenshots, HARs, recordings, log files', related_name='+', to='projects.upload')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_issues', to='accounts.company')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='product_issues.productissue')),
                ('project', models.ForeignKey(blank=True, help_text='Optional — set if reported from inside a project page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_issues', to='projects.project')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_product_issues', to=settings.AUTH_USER_MODEL)),
                ('reproduction_evidence', models.ManyToManyField(blank=True, help_text="Screenshots / HAR files / videos generated DURING the agent's repro run", related_name='+', to='projects.upload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductIssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text="auth.users.id, or 'agent:<name>' for an agent message", max_length=128)),
                ('body', models.TextField()),
                ('is_triage_step', models.BooleanField(default=False, help_text="True if this comment is part of the agent's triage trace")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_issues.productissue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productissue',
            index=models.Index(fields=['company', 'status', '-created_at'], name='product_iss_company_df70e9_idx'),
        ),
        migrations.AddIndex(
            model_name='productissue',
            index=models.Index(fields=['category', 'priority'], name='product_iss_categor_8f5dff_idx'),
        ),
        migrations.AddIndex(
            model_name='productissue',
            index=models.Index(fields=['source'], name='product_iss_source_6e1cca_idx'),
        ),
    ]
