# Generated by Django 5.2.6 on 2026-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productissuecomment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — reporter + all roles can see'), ('internal', 'Internal — admin + superadmin only')], default='public', help_text='public = visible to the reporter and everyone with issue access. internal = admin + superadmin only — for dev-jargon triage notes (API mismatch, SQL fixes, stack traces) that would be useless or confusing for an end-user reporter.', max_length=16),
        ),
    ]
