# Generated by Django 5.2.6 on 2026-06-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_issues', '0002_add_comment_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='productissuecomment',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Inline attachments posted with the comment — list of {name, mime_type, size_bytes, data_url} objects. Mirrors the IssueAttachment shape used by ProductIssue.environment.attachments_inline at issue-creation time, so the same fileToAttachment() helper on the frontend can serialise comments. Used by reporters to answer needs-info follow-up questions with screenshots / clipboard paste / screen capture — without it, the AI asks for a screenshot and the reporter has no way to send one through the chat thread.'),
        ),
    ]
