# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="HybridGovernanceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_framework", models.CharField(max_length=50)),
                ("secondary_frameworks", models.JSONField(default=list)),
                ("rationale", models.TextField(blank=True)),
                ("governance_structure", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_governance_configs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hybrid Governance Configuration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HybridAdaptation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("market_change", "Market Change"),
                            ("technology_shift", "Technology Shift"),
                            ("regulatory_change", "Regulatory Change"),
                            ("resource_change", "Resource Change"),
                            ("stakeholder_change", "Stakeholder Change"),
                            ("performance_issue", "Performance Issue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("increase_agility", "Increase Agility"),
                            ("increase_control", "Increase Control"),
                            ("rebalance", "Rebalance"),
                            ("pivot", "Pivot"),
                            ("scale_up", "Scale Up"),
                            ("scale_down", "Scale Down"),
                        ],
                        max_length=30,
                    ),
                ),
                ("methodology_adjustment", models.TextField(blank=True)),
                ("impact_assessment", models.TextField(blank=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_adaptations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hybrid Adaptation",
                "ordering": ["-created_at"],
            },
        ),
    ]
