# Generated by Django 5.2.6 on 2026-06-04 22:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid_programme', '0002_fix_programme_fk'),
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituentAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('governance_mode', models.CharField(choices=[('predictive', 'Predictive (stage-gate)'), ('adaptive', 'Adaptive (cadence checkpoint)'), ('blend', 'Blended (gate + cadence)')], default='predictive', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('authorized', 'Authorized'), ('paused', 'Paused'), ('closed', 'Closed')], default='proposed', max_length=20)),
                ('stage_gate_passed', models.BooleanField(default=False)),
                ('stage_gate_notes', models.TextField(blank=True)),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('cadence_days', models.PositiveIntegerField(default=14)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hybrid_programme_authorized', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituent_authorizations', to='programs.program')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_programme_authorizations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Constituent Authorization',
                'ordering': ['-created_at'],
            },
        ),
    ]
