# Generated by Django 5.2.6 on 2026-06-04 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_decision_risk_fk'),
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='authorized_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizing_decisions', to='governance.portfolio'),
        ),
        migrations.AddField(
            model_name='decision',
            name='authorized_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizing_decisions', to='programs.program'),
        ),
        migrations.AddField(
            model_name='decision',
            name='authorized_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizing_decisions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='decision',
            name='outcome',
            field=models.CharField(blank=True, choices=[('authorize', 'Authorize'), ('continue', 'Continue'), ('hold', 'Hold'), ('stop', 'Stop')], help_text='What this decision does to its target component when applied.', max_length=12),
        ),
        migrations.CreateModel(
            name='DecisionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_title', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=12)),
                ('target_kind', models.CharField(max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_decision_audits', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='governance.decision')),
            ],
            options={
                'verbose_name': 'Decision Audit Log',
                'verbose_name_plural': 'Decision Audit Logs',
                'ordering': ['-applied_at'],
            },
        ),
    ]
