# Generated by Django 5.2.6 on 2026-06-04 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_meetingaction'),
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['rank', '-created_at'], 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='governanceboard',
            name='quorum',
            field=models.PositiveIntegerField(default=0, help_text='Minimum approve votes required to pass a board decision (0 = no vote required)'),
        ),
        migrations.AddField(
            model_name='governancestakeholder',
            name='current_engagement',
            field=models.CharField(choices=[('unaware', 'Unaware'), ('resistant', 'Resistant'), ('neutral', 'Neutral'), ('supportive', 'Supportive'), ('leading', 'Leading')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='governancestakeholder',
            name='desired_engagement',
            field=models.CharField(choices=[('unaware', 'Unaware'), ('resistant', 'Resistant'), ('neutral', 'Neutral'), ('supportive', 'Supportive'), ('leading', 'Leading')], default='supportive', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Lower = higher priority in the funded queue'),
        ),
        migrations.CreateModel(
            name='ComponentFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('fiscal_period', models.CharField(blank=True, help_text='e.g. FY2026 or Q1-2026', max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fundings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fundings', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_allocations', to='governance.portfolio')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_funding', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_funding', to='projects.project')),
            ],
            options={
                'verbose_name': 'Component Funding',
                'verbose_name_plural': 'Component Fundings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=10)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.decision')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision Vote',
                'ordering': ['-created_at'],
                'unique_together': {('decision', 'voter')},
            },
        ),
    ]
