# Generated by Django 5.2.6 on 2026-06-07 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_decisioncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('escalated', 'Escalated up'), ('delegated', 'Delegated down'), ('assigned', 'Assigned to person'), ('voted', 'Voted'), ('applied', 'Applied')], max_length=16)),
                ('from_tier', models.CharField(blank=True, default='', max_length=40)),
                ('to_tier', models.CharField(blank=True, default='', max_length=80)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_events', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='governance.decision')),
            ],
            options={
                'verbose_name': 'Decision Event',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['decision', 'created_at'], name='governance__decisio_d8d357_idx')],
            },
        ),
    ]
