# Generated by Django 5.2.6 on 2025-12-16 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_crmapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('email', 'Email'), ('integrations', 'Integrations'), ('billing', 'Billing'), ('features', 'Features'), ('maintenance', 'Maintenance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Hide value in API responses')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Stored separately for historical record', max_length=254)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_invited', 'User Invited'), ('user_activated', 'User Activated'), ('user_suspended', 'User Suspended'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deleted', 'Company Deleted'), ('subscription_created', 'Subscription Created'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_downgraded', 'Subscription Downgraded'), ('subscription_cancelled', 'Subscription Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('program_created', 'Program Created'), ('program_updated', 'Program Updated'), ('program_deleted', 'Program Deleted'), ('settings_updated', 'Settings Updated'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('admin_impersonate', 'Admin Impersonated User'), ('data_exported', 'Data Exported'), ('data_imported', 'Data Imported')], max_length=50)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('user', 'User Management'), ('company', 'Company Management'), ('subscription', 'Subscription'), ('project', 'Project'), ('program', 'Program'), ('settings', 'Settings'), ('admin', 'Admin'), ('security', 'Security')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='admin_porta_company_635c4d_idx'), models.Index(fields=['user', '-created_at'], name='admin_porta_user_id_382331_idx'), models.Index(fields=['action', '-created_at'], name='admin_porta_action_05f3d1_idx'), models.Index(fields=['category', '-created_at'], name='admin_porta_categor_7aa868_idx')],
            },
        ),
    ]
