# Generated by Django 4.2.28 on 2026-03-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_portal", "0002_add_client_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("azure", "Microsoft Azure"),
                            ("gcp", "Google Cloud Platform"),
                            ("digitalocean", "DigitalOcean"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Enable this cloud provider"
                    ),
                ),
                ("storage_enabled", models.BooleanField(default=False)),
                ("storage_config", models.JSONField(blank=True, default=dict)),
                ("email_enabled", models.BooleanField(default=False)),
                ("email_config", models.JSONField(blank=True, default=dict)),
                ("database_enabled", models.BooleanField(default=False)),
                ("database_config", models.JSONField(blank=True, default=dict)),
                ("cdn_enabled", models.BooleanField(default=False)),
                ("cdn_config", models.JSONField(blank=True, default=dict)),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider credentials (access keys, secrets, service account JSON)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloud Provider Configuration",
                "verbose_name_plural": "Cloud Provider Configurations",
                "ordering": ["provider"],
            },
        ),
    ]
