# Generated migration for PRINCE2 models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        # ProjectBrief
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_definition', models.TextField(help_text='What the project needs to achieve')),
                ('project_approach', models.TextField(blank=True, help_text='The approach to be taken to deliver the project')),
                ('background', models.TextField(blank=True, help_text='Why the project is needed and how it came about')),
                ('outline_business_case', models.TextField(help_text='Initial business justification')),
                ('project_product_description', models.TextField(help_text='Description of the final product(s)')),
                ('quality_expectations', models.TextField(blank=True, help_text='Quality expectations for the project product')),
                ('acceptance_criteria', models.TextField(blank=True, help_text='Criteria for acceptance of the project product')),
                ('delivery_approach', models.TextField(blank=True, help_text='How the project will be delivered')),
                ('constraints', models.TextField(blank=True, help_text='Known constraints')),
                ('assumptions', models.TextField(blank=True, help_text='Assumptions made')),
                ('time_tolerance', models.CharField(blank=True, max_length=100)),
                ('cost_tolerance', models.CharField(blank=True, max_length=100)),
                ('scope_tolerance', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('version', models.CharField(default='0.1', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prince2_briefs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prince2_briefs', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_brief', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Brief',
                'verbose_name_plural': 'Project Briefs',
            },
        ),
        
        # BusinessCase
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(help_text='Brief summary of the business case')),
                ('reasons', models.TextField(help_text='Reasons for the project')),
                ('business_options', models.TextField(blank=True, help_text='Options considered and rationale for selection')),
                ('expected_benefits', models.TextField(help_text='Benefits the project will deliver')),
                ('expected_dis_benefits', models.TextField(blank=True, help_text='Negative outcomes or side effects')),
                ('timescale', models.TextField(blank=True, help_text='Summary timescale for investment and benefits')),
                ('development_costs', models.DecimalField(decimal_places=2, default=0, help_text='Total development/project costs', max_digits=15)),
                ('ongoing_costs', models.DecimalField(decimal_places=2, default=0, help_text='Annual operational/maintenance costs', max_digits=15)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Return on Investment %', max_digits=6, null=True)),
                ('payback_period_months', models.PositiveIntegerField(blank=True, help_text='Payback period in months', null=True)),
                ('net_present_value', models.DecimalField(blank=True, decimal_places=2, help_text='NPV of the investment', max_digits=15, null=True)),
                ('major_risks', models.TextField(blank=True, help_text='Summary of major risks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('updated', 'Updated')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_business_cases', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_business_case', to='projects.project')),
            ],
            options={
                'verbose_name': 'Business Case',
                'verbose_name_plural': 'Business Cases',
            },
        ),
        
        # BusinessCaseBenefit
        migrations.CreateModel(
            name='BusinessCaseBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('benefit_type', models.CharField(choices=[('financial', 'Financial'), ('non_financial', 'Non-Financial'), ('intangible', 'Intangible')], max_length=20)),
                ('value', models.CharField(help_text='Quantified value or description', max_length=100)),
                ('timing', models.CharField(help_text='When benefit will be realized', max_length=100)),
                ('business_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='prince2.businesscase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['benefit_type', '-id'],
            },
        ),
        
        # BusinessCaseRisk
        migrations.CreateModel(
            name='BusinessCaseRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('probability', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('impact', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('mitigation', models.TextField(blank=True)),
                ('business_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='prince2.businesscase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        
        # ProjectInitiationDocument
        migrations.CreateModel(
            name='ProjectInitiationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_definition', models.TextField()),
                ('project_objectives', models.TextField()),
                ('desired_outcomes', models.TextField(blank=True)),
                ('project_scope', models.TextField()),
                ('exclusions', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('project_approach', models.TextField(help_text='How the project will be delivered')),
                ('team_structure', models.TextField(blank=True, help_text='Description of project organization')),
                ('role_descriptions', models.JSONField(blank=True, default=dict)),
                ('quality_management_approach', models.TextField(blank=True)),
                ('change_control_approach', models.TextField(blank=True)),
                ('risk_management_approach', models.TextField(blank=True)),
                ('communication_management_approach', models.TextField(blank=True)),
                ('project_plan_summary', models.TextField(blank=True)),
                ('project_controls', models.TextField(blank=True, help_text='Controls to be used (reports, reviews, etc.)')),
                ('tailoring_decisions', models.TextField(blank=True, help_text='How PRINCE2 has been tailored for this project')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('baseline', 'Baselined'), ('updated', 'Updated')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pids', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_pid', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Initiation Document',
                'verbose_name_plural': 'Project Initiation Documents',
            },
        ),
        
        # Stage
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('time_tolerance_plus', models.PositiveIntegerField(default=0, help_text='Days')),
                ('time_tolerance_minus', models.PositiveIntegerField(default=0, help_text='Days')),
                ('cost_tolerance_plus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_tolerance_minus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scope_tolerance', models.TextField(blank=True)),
                ('quality_tolerance', models.TextField(blank=True)),
                ('risk_tolerance', models.TextField(blank=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('exception', 'Exception')], default='planned', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_stages', to='projects.project')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'order')},
            },
        ),
        
        # StageGate
        migrations.CreateModel(
            name='StageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('stage_performance_summary', models.TextField(blank=True)),
                ('products_completed', models.TextField(blank=True)),
                ('products_pending', models.TextField(blank=True)),
                ('issues_escalated', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('business_case_still_valid', models.BooleanField(default=True)),
                ('business_case_notes', models.TextField(blank=True)),
                ('next_stage_plan_approved', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('conditional', 'Conditional Approval'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True, help_text='Conditions if conditional approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_stage_gates', to=settings.AUTH_USER_MODEL)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_review', to='prince2.stage')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_stage_gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Gate',
                'verbose_name_plural': 'Stage Gates',
            },
        ),
        
        # StagePlan
        migrations.CreateModel(
            name='StagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_description', models.TextField()),
                ('prerequisites', models.TextField(blank=True)),
                ('external_dependencies', models.TextField(blank=True)),
                ('planning_assumptions', models.TextField(blank=True)),
                ('schedule_narrative', models.TextField(blank=True)),
                ('resource_requirements', models.TextField(blank=True)),
                ('budget_breakdown', models.JSONField(blank=True, default=dict)),
                ('tolerance_notes', models.TextField(blank=True)),
                ('monitoring_approach', models.TextField(blank=True)),
                ('reporting_frequency', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'Stage Plan',
                'verbose_name_plural': 'Stage Plans',
            },
        ),
        
        # WorkPackage
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_descriptions', models.TextField(help_text='Products to be delivered')),
                ('techniques_processes', models.TextField(blank=True)),
                ('development_interfaces', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('time_tolerance', models.CharField(blank=True, max_length=100)),
                ('cost_tolerance', models.CharField(blank=True, max_length=100)),
                ('reporting_requirements', models.TextField(blank=True)),
                ('checkpoint_frequency', models.CharField(blank=True, max_length=100)),
                ('problem_handling', models.TextField(blank=True)),
                ('escalation_process', models.TextField(blank=True)),
                ('approval_method', models.TextField(blank=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_work_packages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_work_packages', to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='prince2.stage')),
                ('team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Package',
                'verbose_name_plural': 'Work Packages',
                'ordering': ['stage', 'reference'],
            },
        ),
        
        # ProjectBoard
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_frequency', models.CharField(default='Monthly', help_text='How often the board meets', max_length=100)),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('budget_authority', models.DecimalField(blank=True, decimal_places=2, help_text='Budget decisions requiring board approval', max_digits=12, null=True)),
                ('governance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_board', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Board',
                'verbose_name_plural': 'Project Boards',
            },
        ),
        
        # ProjectBoardMember
        migrations.CreateModel(
            name='ProjectBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('executive', 'Executive'), ('senior_user', 'Senior User'), ('senior_supplier', 'Senior Supplier'), ('project_manager', 'Project Manager'), ('project_assurance', 'Project Assurance'), ('change_authority', 'Change Authority'), ('project_support', 'Project Support')], max_length=30)),
                ('responsibilities', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='prince2.projectboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'unique_together': {('board', 'user', 'role')},
            },
        ),
        
        # HighlightReport
        migrations.CreateModel(
            name='HighlightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_date', models.DateField()),
                ('overall_status', models.CharField(choices=[('green', 'Green - On Track'), ('amber', 'Amber - At Risk'), ('red', 'Red - Off Track')], max_length=10)),
                ('status_summary', models.TextField()),
                ('work_completed', models.TextField()),
                ('work_planned_next_period', models.TextField()),
                ('products_completed', models.TextField(blank=True)),
                ('products_planned', models.TextField(blank=True)),
                ('issues_summary', models.TextField(blank=True)),
                ('risks_summary', models.TextField(blank=True)),
                ('tolerance_status', models.TextField(blank=True)),
                ('budget_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lessons_this_period', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_highlight_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_highlight_reports', to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_reports', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'Highlight Report',
                'verbose_name_plural': 'Highlight Reports',
                'ordering': ['-report_date'],
            },
        ),
        
        # CheckpointReport
        migrations.CreateModel(
            name='CheckpointReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('follow_ups_from_previous', models.TextField(blank=True)),
                ('products_completed_this_period', models.TextField()),
                ('products_to_complete_next_period', models.TextField()),
                ('overall_status', models.CharField(choices=[('green', 'Green - On Track'), ('amber', 'Amber - At Risk'), ('red', 'Red - Off Track')], max_length=10)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_time_spent', models.PositiveIntegerField(blank=True, help_text='Hours', null=True)),
                ('issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkpoint_reports', to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_reports', to='prince2.workpackage')),
            ],
            options={
                'verbose_name': 'Checkpoint Report',
                'verbose_name_plural': 'Checkpoint Reports',
                'ordering': ['-report_date'],
            },
        ),
        
        # EndStageReport
        migrations.CreateModel(
            name='EndStageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('stage_objectives_achieved', models.TextField()),
                ('products_delivered', models.TextField()),
                ('products_not_delivered', models.TextField(blank=True)),
                ('planned_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('issues_summary', models.TextField(blank=True)),
                ('risks_summary', models.TextField(blank=True)),
                ('quality_activities', models.TextField(blank=True)),
                ('quality_issues', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('business_case_impact', models.TextField(blank=True)),
                ('next_stage_recommendation', models.TextField(blank=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_end_stage_reports', to=settings.AUTH_USER_MODEL)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_stage_report', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'End Stage Report',
                'verbose_name_plural': 'End Stage Reports',
            },
        ),
        
        # EndProjectReport
        migrations.CreateModel(
            name='EndProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('project_objectives_achieved', models.TextField()),
                ('planned_products', models.TextField()),
                ('delivered_products', models.TextField()),
                ('products_not_delivered', models.TextField(blank=True)),
                ('original_planned_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_planned_end', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('benefits_achieved', models.TextField(blank=True)),
                ('benefits_expected_later', models.TextField(blank=True)),
                ('quality_review', models.TextField(blank=True)),
                ('lessons_learned', models.TextField()),
                ('post_project_recommendations', models.TextField(blank=True)),
                ('follow_on_actions', models.TextField(blank=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_end_project_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_end_project_report', to='projects.project')),
            ],
            options={
                'verbose_name': 'End Project Report',
                'verbose_name_plural': 'End Project Reports',
            },
        ),
        
        # IssueRegister
        migrations.CreateModel(
            name='IssueRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('issue_type', models.CharField(choices=[('issue', 'Issue'), ('change_request', 'Change Request'), ('off_specification', 'Off-Specification')], max_length=20)),
                ('date_raised', models.DateField()),
                ('description', models.TextField()),
                ('impact_analysis', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('time_impact_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('captured', 'Captured'), ('examining', 'Examining'), ('pending_decision', 'Pending Decision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='captured', max_length=20)),
                ('decision', models.TextField(blank=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_prince2_issues', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_prince2_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_issues', to='projects.project')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_prince2_issues', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-date_raised'],
            },
        ),
        
        # RiskRegister
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date_identified', models.DateField()),
                ('description', models.TextField()),
                ('cause', models.TextField(blank=True)),
                ('event', models.TextField(blank=True, help_text='What could happen')),
                ('effect', models.TextField(blank=True, help_text='Impact if it happens')),
                ('probability', models.CharField(choices=[('very_low', 'Very Low (< 10%)'), ('low', 'Low (10-30%)'), ('medium', 'Medium (30-50%)'), ('high', 'High (50-70%)'), ('very_high', 'Very High (> 70%)')], max_length=20)),
                ('impact', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('proximity', models.CharField(blank=True, help_text='When might it occur', max_length=100)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('response_type', models.CharField(blank=True, choices=[('avoid', 'Avoid'), ('reduce', 'Reduce'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('prepare', 'Prepare contingency'), ('share', 'Share'), ('exploit', 'Exploit (opportunity)'), ('enhance', 'Enhance (opportunity)')], max_length=20)),
                ('response_actions', models.TextField(blank=True)),
                ('contingency_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('active', 'Active'), ('reducing', 'Reducing'), ('closed', 'Closed'), ('occurred', 'Occurred')], default='identified', max_length=20)),
                ('residual_probability', models.CharField(blank=True, choices=[('very_low', 'Very Low (< 10%)'), ('low', 'Low (10-30%)'), ('medium', 'Medium (30-50%)'), ('high', 'High (50-70%)'), ('very_high', 'Very High (> 70%)')], max_length=20)),
                ('residual_impact', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_prince2_risks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_prince2_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_risks', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'ordering': ['-date_identified'],
            },
        ),
        
        # LessonsLog
        migrations.CreateModel(
            name='LessonsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField()),
                ('lesson_type', models.CharField(choices=[('what_went_well', 'What Went Well'), ('what_went_wrong', 'What Went Wrong'), ('improvement', 'Improvement Suggestion')], max_length=20)),
                ('category', models.CharField(choices=[('process', 'Process'), ('technology', 'Technology'), ('people', 'People'), ('supplier', 'Supplier'), ('communication', 'Communication'), ('quality', 'Quality'), ('risk', 'Risk Management'), ('other', 'Other')], max_length=20)),
                ('event', models.TextField(help_text='What happened')),
                ('effect', models.TextField(help_text='What was the effect')),
                ('cause', models.TextField(blank=True, help_text='Why did it happen')),
                ('recommendation', models.TextField(help_text='What should be done differently')),
                ('actionable', models.BooleanField(default=True)),
                ('action_taken', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_prince2_lessons', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_lessons', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='prince2.stage')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-date_logged'],
            },
        ),
        
        # QualityRegister
        migrations.CreateModel(
            name='QualityRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('quality_method', models.CharField(choices=[('quality_review', 'Quality Review'), ('audit', 'Audit'), ('inspection', 'Inspection'), ('test', 'Test'), ('walkthrough', 'Walkthrough')], max_length=20)),
                ('quality_criteria', models.TextField()),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('conditional_pass', 'Conditional Pass'), ('fail', 'Fail')], default='pending', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('actions_required', models.TextField(blank=True)),
                ('signed_off', models.BooleanField(default=False)),
                ('signed_off_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_quality_records', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_quality_records', to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_records', to='prince2.workpackage')),
            ],
            options={
                'verbose_name': 'Quality Record',
                'verbose_name_plural': 'Quality Records',
                'ordering': ['-planned_date'],
            },
        ),
        
        # ProjectTolerance
        migrations.CreateModel(
            name='ProjectTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerance_type', models.CharField(choices=[('time', 'Time'), ('cost', 'Cost'), ('scope', 'Scope'), ('quality', 'Quality'), ('benefit', 'Benefit'), ('risk', 'Risk')], max_length=20)),
                ('description', models.TextField()),
                ('plus_tolerance', models.CharField(blank=True, max_length=100)),
                ('minus_tolerance', models.CharField(blank=True, max_length=100)),
                ('upper_limit', models.CharField(blank=True, max_length=100)),
                ('lower_limit', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(blank=True, max_length=255)),
                ('is_exceeded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_tolerances', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Tolerance',
                'verbose_name_plural': 'Project Tolerances',
                'unique_together': {('project', 'tolerance_type')},
            },
        ),
    ]
