# Generated by Django 5.2.6 on 2025-12-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0001_initial'),
        ('projects', '0007_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endstagereport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='endstagereport',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='issueregister',
            name='decision_by',
        ),
        migrations.RemoveField(
            model_name='issueregister',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='issueregister',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issueregister',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='issueregister',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='qualityregister',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qualityregister',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='qualityregister',
            name='signed_off_by',
        ),
        migrations.RemoveField(
            model_name='qualityregister',
            name='work_package',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='identified_by',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='project',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='businesscase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='businesscasebenefit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='businesscaserisk',
            options={},
        ),
        migrations.AlterModelOptions(
            name='endprojectreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='highlightreport',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterModelOptions(
            name='lessonslog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectboardmember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectbrief',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectinitiationdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projecttolerance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='stagegate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stageplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='projectboardmember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='businesscasebenefit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='benefits_expected_later',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='cost_variance',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='delivered_products',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='lessons_learned',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='original_planned_cost',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='original_planned_end',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='planned_products',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='post_project_recommendations',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='products_not_delivered',
        ),
        migrations.RemoveField(
            model_name='endprojectreport',
            name='project_objectives_achieved',
        ),
        migrations.RemoveField(
            model_name='highlightreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='highlightreport',
            name='lessons_this_period',
        ),
        migrations.RemoveField(
            model_name='highlightreport',
            name='products_completed',
        ),
        migrations.RemoveField(
            model_name='highlightreport',
            name='products_planned',
        ),
        migrations.RemoveField(
            model_name='highlightreport',
            name='tolerance_status',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='actionable',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='lessonslog',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='acceptance_criteria',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='background',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='cost_tolerance',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='delivery_approach',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='project_product_description',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='quality_expectations',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='scope_tolerance',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='time_tolerance',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='assumptions',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='desired_outcomes',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='project_plan_summary',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='project_scope',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='role_descriptions',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='tailoring_decisions',
        ),
        migrations.RemoveField(
            model_name='projectinitiationdocument',
            name='team_structure',
        ),
        migrations.RemoveField(
            model_name='projecttolerance',
            name='lower_limit',
        ),
        migrations.RemoveField(
            model_name='projecttolerance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='projecttolerance',
            name='upper_limit',
        ),
        migrations.RemoveField(
            model_name='stagegate',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='stagegate',
            name='business_case_notes',
        ),
        migrations.RemoveField(
            model_name='stagegate',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='stagegate',
            name='issues_escalated',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='budget_breakdown',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='external_dependencies',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='monitoring_approach',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='planning_assumptions',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='reporting_frequency',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='schedule_narrative',
        ),
        migrations.RemoveField(
            model_name='stageplan',
            name='tolerance_notes',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='approval_method',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='authorized_date',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='checkpoint_frequency',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='cost_tolerance',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='development_interfaces',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='escalation_process',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='problem_handling',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='techniques_processes',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='time_tolerance',
        ),
        migrations.AddField(
            model_name='businesscase',
            name='costs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='investment_appraisal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscasebenefit',
            name='measurable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='endprojectreport',
            name='achievements_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='endprojectreport',
            name='budget_variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='endprojectreport',
            name='performance_against_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='endprojectreport',
            name='schedule_variance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='endprojectreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonslog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonslog',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectboardmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='project_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='project_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='project_team_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinitiationdocument',
            name='baseline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinitiationdocument',
            name='success_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinitiationdocument',
            name='tailoring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='cost_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='time_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stageplan',
            name='assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageplan',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stageplan',
            name='dependencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageplan',
            name='quality_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='techniques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='tolerances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='business_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='development_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='executive_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='expected_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='expected_dis_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='major_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='net_present_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='ongoing_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='payback_period_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_business_cases', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='roi_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('updated', 'Updated')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='timescale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='businesscasebenefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('financial', 'Financial'), ('non_financial', 'Non-Financial'), ('intangible', 'Intangible')], default='financial', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesscasebenefit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businesscasebenefit',
            name='timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesscasebenefit',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesscaserisk',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businesscaserisk',
            name='impact',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesscaserisk',
            name='mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscaserisk',
            name='probability',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='benefits_achieved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='follow_on_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_end_reports', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='quality_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endprojectreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='budget_forecast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='budget_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='issues_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='overall_status',
            field=models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='risks_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_reports', to='prince2.stage'),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='status_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='work_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreport',
            name='work_planned_next_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='category',
            field=models.CharField(blank=True, choices=[('process', 'Process'), ('technology', 'Technology'), ('people', 'People'), ('supplier', 'Supplier'), ('communication', 'Communication'), ('quality', 'Quality'), ('risk', 'Risk')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='date_logged',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonslog',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prince2.stage'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='budget_authority',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='governance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='meeting_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectboardmember',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectboardmember',
            name='role',
            field=models.CharField(blank=True, choices=[('executive', 'Executive'), ('senior_user', 'Senior User'), ('senior_supplier', 'Senior Supplier'), ('project_manager', 'Project Manager'), ('project_assurance', 'Project Assurance'), ('change_authority', 'Change Authority'), ('project_support', 'Project Support')], default='project_support', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectboardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='outline_business_case',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_briefs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='project_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='project_definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectbrief',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='change_control_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='communication_management_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_pids', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='project_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='project_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='project_definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='project_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='quality_management_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='risk_management_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('baselined', 'Baselined'), ('updated', 'Updated')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectinitiationdocument',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttolerance',
            name='current_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projecttolerance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttolerance',
            name='minus_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttolerance',
            name='plus_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttolerance',
            name='tolerance_type',
            field=models.CharField(blank=True, choices=[('time', 'Time'), ('cost', 'Cost'), ('scope', 'Scope'), ('quality', 'Quality'), ('benefit', 'Benefit'), ('risk', 'Risk')], default='cost', max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stage',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stage',
            name='scope_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='decision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('conditional', 'Conditional'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='products_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='products_pending',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='prince2.stage'),
        ),
        migrations.AlterField(
            model_name='stagegate',
            name='stage_performance_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='plan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='resource_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='prince2.stage'),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('baselined', 'Baselined')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='product_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='reporting_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='prince2.stage'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='team_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='CheckpointReport',
        ),
        migrations.DeleteModel(
            name='EndStageReport',
        ),
        migrations.DeleteModel(
            name='IssueRegister',
        ),
        migrations.DeleteModel(
            name='QualityRegister',
        ),
        migrations.DeleteModel(
            name='RiskRegister',
        ),
        migrations.RemoveField(
            model_name='projectboardmember',
            name='appointed_date',
        ),
        migrations.RemoveField(
            model_name='projectboardmember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='cost_tolerance_minus',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='cost_tolerance_plus',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='planned_cost',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='quality_tolerance',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='risk_tolerance',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='time_tolerance_minus',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='time_tolerance_plus',
        ),
    ]
