# Generated by Django 5.2.6 on 2026-04-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbrief',
            old_name='project_definition',
            new_name='background',
        ),
    ]
