# Generated by Django 5.2.6 on 2026-04-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0004_rename_project_definition_projectbrief_background'),
        ('projects', '0009_project_portfolio_project_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
                ('products_completed', models.TextField(blank=True, help_text='Products completed during the reporting period.')),
                ('products_planned', models.TextField(blank=True, help_text='Products planned for the next reporting period.')),
                ('risks_issues_summary', models.TextField(blank=True, help_text='Risk and issue commentary for the period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_checkpoint_reports', to='projects.project')),
                ('team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_checkpoint_reports_authored', to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoint_reports', to='prince2.workpackage')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
