# Generated by Django 5.2.6 on 2026-06-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0008_workpackage_stage_plan_product_work_package'),
        ('projects', '0020_yanmar_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='prince2.workpackage'),
        ),
        migrations.CreateModel(
            name='Prince2Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('resource', 'Resource'), ('external', 'External'), ('schedule', 'Schedule')], default='technical', max_length=20)),
                ('probability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('response_type', models.CharField(choices=[('avoid', 'Avoid'), ('reduce', 'Reduce'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('share', 'Share'), ('exploit', 'Exploit')], default='reduce', max_length=20)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('managing', 'Managing'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('date_identified', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_risks', to='projects.project')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='prince2.workpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prince2Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('issue_type', models.CharField(choices=[('request_for_change', 'Request for Change'), ('off_specification', 'Off-Specification'), ('problem_concern', 'Problem / Concern')], default='problem_concern', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assessing', 'Assessing'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_owned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_issues', to='projects.project')),
                ('related_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='prince2.prince2risk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
