# Generated by Django 5.2.6 on 2026-06-04 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0009_workpackage_depends_on_prince2risk_prince2issue'),
        ('projects', '0020_yanmar_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prince2ExceptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cause', models.TextField(blank=True, default='', help_text='What caused the deviation / forecast breach')),
                ('consequences', models.TextField(blank=True, default='', help_text='Impact on the stage, project and Business Case')),
                ('options', models.TextField(blank=True, default='', help_text='Available response options')),
                ('recommendation', models.TextField(blank=True, default='', help_text="Project Manager's recommended option")),
                ('board_decision', models.TextField(blank=True, default='', help_text='Project Board decision / direction')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('board_decision', 'Board Decision'), ('closed', 'Closed')], default='open', max_length=20)),
                ('auto_generated', models.BooleanField(default=False)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breaching_tolerance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_reports', to='prince2.projecttolerance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_exception_reports', to='projects.project')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_raised_exceptions', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_reports', to='prince2.stage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
