# Generated by Django 5.2.6 on 2026-06-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0010_prince2exceptionreport'),
        ('projects', '0020_yanmar_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('action', 'Action'), ('event', 'Event'), ('observation', 'Observation'), ('informal_issue', 'Informal Issue'), ('decision', 'Decision')], default='action', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_daily_log', to='projects.project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_daily_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('rationale', models.TextField(blank=True, default='', help_text='Why this plan is needed (links to the exception)')),
                ('plan_description', models.TextField(blank=True, default='', help_text='The revised plan of action')),
                ('revised_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revised_end_date', models.DateField(blank=True, null=True)),
                ('revised_tolerances', models.TextField(blank=True, default='', help_text='New time/cost/scope tolerances agreed by the Board')),
                ('impact_on_business_case', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_approved_exception_plans', to=settings.AUTH_USER_MODEL)),
                ('exception_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_plans', to='prince2.prince2exceptionreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_exception_plans', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_plans', to='prince2.stage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', help_text='Free-text product name if no linked Product', max_length=255)),
                ('quality_method', models.CharField(choices=[('review', 'Quality Review'), ('test', 'Test'), ('inspection', 'Inspection'), ('audit', 'Audit'), ('approval', 'Approval')], default='review', max_length=20)),
                ('quality_criteria', models.TextField(blank=True, default='')),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='prince2.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_quality_register', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='prince2.workpackage')),
            ],
            options={
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_type', models.CharField(choices=[('risk', 'Risk Management Approach'), ('quality', 'Quality Management Approach'), ('communication', 'Communication Management Approach'), ('change_control', 'Change Control Approach')], max_length=20)),
                ('introduction', models.TextField(blank=True, default='', help_text='Purpose, objectives, scope of this approach')),
                ('procedure', models.TextField(blank=True, default='', help_text='The procedure / process steps to be followed')),
                ('roles_responsibilities', models.TextField(blank=True, default='')),
                ('tools_techniques', models.TextField(blank=True, default='')),
                ('reporting', models.TextField(blank=True, default='', help_text='Records, reports and their timing')),
                ('scales_definitions', models.TextField(blank=True, default='', help_text='e.g. risk probability/impact scales, priority scales')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('baselined', 'Baselined')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_approaches', to='projects.project')),
            ],
            options={
                'ordering': ['approach_type'],
                'unique_together': {('project', 'approach_type')},
            },
        ),
    ]
