# Generated by Django 5.2.6 on 2026-06-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0011_dailylog_exceptionplan_qualityregisterentry_and_more'),
        ('projects', '0020_yanmar_bigautofield_index_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prince2issue',
            name='change_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_ca_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prince2issue',
            name='change_authority_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prince2issue',
            name='change_authority_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred to Project Board')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prince2issue',
            name='change_authority_rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectinitiationdocument',
            name='tailoring_profile',
            field=models.CharField(choices=[('full', 'Full method'), ('simple', 'Simplified / lightweight')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='accepted_by_tm',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Prince2ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, default='', help_text='Configuration item reference, e.g. CI-001.', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(blank=True, default='', help_text='Type / classification of the item.', max_length=100)),
                ('version', models.CharField(blank=True, default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('approved', 'Approved'), ('baselined', 'Baselined'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('copy_holders', models.TextField(blank=True, default='', help_text='Who holds copies of this item.')),
                ('location', models.CharField(blank=True, default='', help_text='Where the item is stored.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_owned_config_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_items', to='prince2.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_config_items', to='projects.project')),
            ],
            options={
                'ordering': ['identifier', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Prince2LessonsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Lessons Report', max_length=200)),
                ('summary', models.TextField(blank=True, default='', help_text='Narrative overview of the lessons learned.')),
                ('what_went_well', models.TextField(blank=True, default='')),
                ('what_went_badly', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='', help_text='Recommendations for future projects / corporate.')),
                ('lessons_count', models.IntegerField(default=0, help_text='Number of Lessons Log entries compiled into this report.')),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_lessons_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_lessons_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
