# Generated by Django 5.2.6 on 2026-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prince2', '0012_prince2issue_change_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightreport',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='highlightreport',
            name='phase_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='highlightreport',
            name='project_manager',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='highlightreport',
            name='senior_supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='highlightreport',
            name='sponsor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
