# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMIGovernanceBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("steering_committee", "Steering Committee"),
                            ("program_board", "Program Board"),
                            ("review_meeting", "Review Meeting"),
                            ("gate_review", "Gate Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("attendees", models.JSONField(default=list)),
                ("agenda", models.TextField(blank=True)),
                ("decisions", models.JSONField(default=list)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("minutes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmi_governance_boards",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMI Governance Board",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="PMIComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("subsidiary_program", "Subsidiary Program"),
                            ("operational_activity", "Operational Activity"),
                        ],
                        default="project",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True, related_name="dependents", to="pmi.pmicomponent"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmi_components",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMI Component",
                "ordering": ["-created_at"],
            },
        ),
    ]
