# Generated by Django 5.2.6 on 2026-06-04 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0001_initial'),
        ('projects', '0021_task_product_task_work_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMIBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('analyzed', 'Analyzed'), ('planned', 'Planned'), ('realizing', 'Realizing'), ('realized', 'Realized'), ('sustained', 'Sustained')], default='identified', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('realized_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, help_text='The component that delivers this benefit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefits', to='pmi.pmicomponent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmi_owned_benefits', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmi_benefits', to='projects.project')),
            ],
            options={
                'verbose_name': 'PMI Benefit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMIGateDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('authorize', 'Authorize'), ('continue', 'Continue'), ('hold', 'Hold'), ('stop', 'Stop')], max_length=12)),
                ('gate', models.CharField(blank=True, help_text='Lifecycle gate / phase this decision applies at.', max_length=100)),
                ('rationale', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_decisions', to='pmi.pmigovernanceboard')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_decisions', to='pmi.pmicomponent')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmi_gate_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PMI Gate Decision',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PMIProgramCharter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vision', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pmi_charter', to='projects.project')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmi_sponsored_charters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PMI Program Charter',
            },
        ),
        migrations.CreateModel(
            name='PMIRoadmapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(blank=True, help_text='Life-cycle phase label.', max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmi_roadmap_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'PMI Roadmap Item',
                'ordering': ['sequence', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='PMIStakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('power', models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=10)),
                ('interest', models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=10)),
                ('engagement_strategy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmi_stakeholders', to='projects.project')),
            ],
            options={
                'verbose_name': 'PMI Stakeholder',
                'ordering': ['name'],
            },
        ),
    ]
