# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="LSSGreenMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("process_capability", "Process Capability"),
                            ("defect_rate", "Defect Rate"),
                            ("cycle_time", "Cycle Time"),
                            ("throughput", "Throughput"),
                            ("yield_rate", "Yield Rate"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cp",
                    models.FloatField(
                        blank=True, help_text="Process Capability Index", null=True
                    ),
                ),
                (
                    "cpk",
                    models.FloatField(
                        blank=True,
                        help_text="Process Capability Index (centered)",
                        null=True,
                    ),
                ),
                ("defects_per_million", models.FloatField(blank=True, null=True)),
                ("sigma_level", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_green_metrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "LSS Green Metric",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LSSGreenMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("define", "Define"),
                            ("measure", "Measure"),
                            ("analyze", "Analyze"),
                            ("improve", "Improve"),
                            ("control", "Control"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric", models.CharField(max_length=100)),
                ("baseline_value", models.FloatField(blank=True, null=True)),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("measurement_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_green_measurements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "LSS Green Measurement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DMAICPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("define", "Define"),
                            ("measure", "Measure"),
                            ("analyze", "Analyze"),
                            ("improve", "Improve"),
                            ("control", "Control"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objective", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_green_dmaic_phases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "DMAIC Phase",
                "verbose_name_plural": "DMAIC Phases",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
