# Generated by Django 4.2.28 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_company_b54bdb_idx',
            old_name='finance_inv_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_project_3dbefe_idx',
            old_name='finance_inv_project_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_program_565681_idx',
            old_name='finance_inv_program_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_project_19885e_idx',
            old_name='finance_inv_project_code_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_program_1d5072_idx',
            old_name='finance_inv_program_code_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_externa_b0237b_idx',
            old_name='finance_inv_external_id_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finance_inv_issue_d_3b7e1d_idx',
            old_name='finance_inv_issue_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='finance_ven_company_3efa49_idx',
            old_name='finance_ven_company_name_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='finance_ven_company_7d5e0b_idx',
            old_name='finance_ven_company_code_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='finance_ven_company_246c40_idx',
            old_name='finance_ven_company_vat_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID in the source system (Exact / AFAS / etc.) — used for idempotent imports.', max_length=128),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file_url',
            field=models.URLField(blank=True, help_text='PDF / file location.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(help_text="Vendor's invoice number (e.g. INV-2026-0042).", max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='program_code',
            field=models.CharField(blank=True, help_text='Programme code on the invoice — used to auto-match to a Program on import.', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_code',
            field=models.CharField(blank=True, help_text='Project code on the invoice — used to auto-match to a Project on import.', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=21, help_text='VAT/BTW rate as a percentage (21.00 = 21%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(blank=True, help_text='bank_transfer, credit_card, etc.', max_length=64),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chamber_of_commerce',
            field=models.CharField(blank=True, help_text='KvK / Chamber of Commerce registration number.', max_length=64),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 (NL, DE, ...).', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_category',
            field=models.CharField(blank=True, help_text="Default expense category for invoices from this vendor (e.g. 'Subcontractor').", max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Statutory name on contracts/invoices, if different from display name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Standard payment term in days.'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vat_id',
            field=models.CharField(blank=True, help_text='VAT / BTW number (e.g. NL123456789B01).', max_length=64),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='Vendor code in the financial admin (Exact, AFAS, etc.). Used for import matching.', max_length=64),
        ),
    ]
