# Generated by Django 5.2.6 on 2026-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_finance_inv_company_status_idx_finance_inv_company_b54bdb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Uploaded invoice document (PDF/scan).', null=True, upload_to='vendor_invoices/'),
        ),
    ]
