import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Eye, CheckCircle2, XCircle, Sparkles, Target, Layers, RefreshCw, Edit, Lightbulb, Info, Loader2, MonitorPlay } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { visualService, resolveVisualType } from '@/services/visualService';
import VisualTemplateRenderer from '@/components/visuals/VisualTemplateRenderer';


interface Visual {
  id: number;
  lesson_title: string;
  visual_id: string;
  ai_confidence: number;
  status: 'pending' | 'approved' | 'rejected';
  ai_concepts?: string[];
  ai_intent?: string;
  ai_methodology?: string;
  custom_keywords?: string;
  preview_image_url?: string;  // ← DALL-E preview URL
  created_at: string;
}

interface VisualPreviewModalProps {
  visual: Visual | null;
  isOpen: boolean;
  onClose: () => void;
  onApprove: (visualId: number) => void;
  onReject: (visualId: number) => void;
  onRegenerate?: (visualId: number, keywords: string) => void;
}

const VisualPreviewModal = ({
  visual,
  isOpen,
  onClose,
  onApprove,
  onReject,
  onRegenerate
}: VisualPreviewModalProps) => {

  const [customKeywords, setCustomKeywords] = useState('');
  const [isEditingKeywords, setIsEditingKeywords] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isGeneratingPreview, setIsGeneratingPreview] = useState(false);
  const [previewImageUrl, setPreviewImageUrl] = useState(visual?.preview_image_url || '');

  if (!visual) return null;

  const getStatusBadge = (status: string) => {
    const styles = {
      pending: { bg: '#f59e0b15', text: '#f59e0b', label: 'Pending' },
      approved: { bg: '#22c55e15', text: '#22c55e', label: 'Approved' },
      rejected: { bg: '#ef444415', text: '#ef4444', label: 'Rejected' },
    };
    const style = styles[status as keyof typeof styles] || styles.pending;

    return (
      <Badge style={{ backgroundColor: style.bg, color: style.text }} className="border-0">
        {style.label}
      </Badge>
    );
  };

  // Dynamic SVG placeholder
  const getSvgPlaceholder = (visualId: string, methodology?: string) => {
    const getColorFromId = (id: string) => {
      const hash = id.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
      const colors = [
        { start: '#8B5CF6', end: '#D946EF', name: 'Purple-Pink' },
        { start: '#3B82F6', end: '#8B5CF6', name: 'Blue-Purple' },
        { start: '#06B6D4', end: '#3B82F6', name: 'Cyan-Blue' },
        { start: '#10B981', end: '#06B6D4', name: 'Green-Cyan' },
        { start: '#F59E0B', end: '#EF4444', name: 'Orange-Red' },
      ];
      return colors[hash % colors.length];
    };

    const color = getColorFromId(visualId);
    const displayMethodology = methodology || 'Visual metadata generated by AI';

    const svgContent = `
      <svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" style="stop-color:${color.start};stop-opacity:1" />
            <stop offset="100%" style="stop-color:${color.end};stop-opacity:1" />
          </linearGradient>
        </defs>
        <rect width="100%" height="100%" fill="url(#grad1)"/>

        <rect x="40" y="40" width="720" height="60" fill="rgba(255,255,255,0.2)" rx="8"/>
        <text x="400" y="75" font-family="Arial, sans-serif" font-size="20" font-weight="bold" fill="white" text-anchor="middle">
          ${visualId.substring(0, 50)}
        </text>

        <rect x="40" y="460" width="720" height="100" fill="rgba(255,255,255,0.15)" rx="8"/>
        <text x="400" y="485" font-family="Arial, sans-serif" font-size="14" font-weight="bold" fill="white" text-anchor="middle">
          AI Methodology:
        </text>

        <text x="400" y="270" font-family="Arial, sans-serif" font-size="32" font-weight="bold" fill="white" text-anchor="middle">
          📊 Visual Specification
        </text>
        <text x="400" y="310" font-family="Arial, sans-serif" font-size="16" fill="rgba(255,255,255,0.9)" text-anchor="middle">
          Klik "Genereer Preview" voor DALL-E visual
        </text>
        <text x="400" y="335" font-family="Arial, sans-serif" font-size="14" fill="rgba(255,255,255,0.7)" text-anchor="middle">
          Color scheme: ${color.name}
        </text>

        ${displayMethodology.match(/.{1,80}/g)?.slice(0, 3).map((line, i) =>
          `<text x="400" y="${510 + (i * 20)}" font-family="Arial, sans-serif" font-size="11" fill="white" text-anchor="middle">${line.trim()}</text>`
        ).join('') || ''}
      </svg>
    `;
    return 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgContent)));
  };

  // Generate DALL-E preview
  const handleGeneratePreview = async () => {
  if (!visual) return;

  setIsGeneratingPreview(true);
  try {
    const response = await visualService.generatePreviewImage(visual.id);

    if (response.image_url) {
      setPreviewImageUrl(response.image_url);
    }
  } catch (error) {
    console.error('Failed to generate preview:', error);
    const errorMsg = error.response?.data?.error || error.message || 'Unknown error';
    alert(`Failed to generate DALL-E preview: ${errorMsg}`);
  } finally {
    setIsGeneratingPreview(false);
  }
};

  const handleRegenerateClick = async () => {
    if (onRegenerate && customKeywords.trim()) {
      setIsRegenerating(true);
      try {
        await onRegenerate(visual.id, customKeywords);
        setIsEditingKeywords(false);
        setCustomKeywords('');
        // Clear preview so user can regenerate it with new metadata
        setPreviewImageUrl('');
      } finally {
        setIsRegenerating(false);
      }
    }
  };

  const keywordExamples = [
    { label: 'Style', examples: 'animated, modern, professional, minimalist, infographic style' },
    { label: 'Colors', examples: 'blue and purple theme, corporate colors, vibrant, pastel' },
    { label: 'Format', examples: 'flowchart, timeline, diagram, interactive, step-by-step' },
    { label: 'Mood', examples: 'engaging, serious, playful, educational, inspiring' },
    { label: 'Elements', examples: 'icons, charts, 3D graphics, hand-drawn, vector art' },
  ];

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Eye className="w-5 h-5 text-purple-600" />
            Visual Preview
          </DialogTitle>
          <DialogDescription>
            Preview en customize AI-generated visual voor {visual.lesson_title}
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[70vh]">
          <div className="space-y-6">

            {/* Visual Display - DALL-E or Placeholder */}
            <Card>
              <CardContent className="p-0">
                <div className="relative bg-gradient-to-br from-purple-50 to-pink-50 rounded-lg overflow-hidden">

                  {previewImageUrl ? (
                    /* TOON DALL-E PREVIEW IMAGE */
                    <div className="relative">
                      <img
                        src={previewImageUrl}
                        alt={visual.visual_id}
                        className="w-full h-auto"
                        onError={() => setPreviewImageUrl('')}
                      />

                      {/* Regenerate Preview Button */}
                      <div className="absolute bottom-4 left-4">
                        <Button
                          size="sm"
                          onClick={handleGeneratePreview}
                          disabled={isGeneratingPreview}
                          className="bg-white/90 hover:bg-white text-blue-700 border border-blue-200"
                        >
                          <RefreshCw className={`w-4 h-4 mr-2 ${isGeneratingPreview ? 'animate-spin' : ''}`} />
                          {isGeneratingPreview ? 'Generating...' : 'Regenereer Preview'}
                        </Button>
                      </div>

                      {/* Customize Button */}
                      <div className="absolute bottom-4 right-4">
                        <Button
                          size="sm"
                          onClick={() => setIsEditingKeywords(!isEditingKeywords)}
                          className="bg-white/90 hover:bg-white text-purple-700 border border-purple-200"
                        >
                          <Edit className="w-4 h-4 mr-2" />
                          {isEditingKeywords ? 'Annuleer' : 'Customize Visual'}
                        </Button>
                      </div>
                    </div>
                  ) : (
                    /* TOON PLACEHOLDER + GENERATE BUTTON */
                    <div className="relative">
                      <img
                        src={getSvgPlaceholder(visual.visual_id, visual.ai_methodology)}
                        alt="Preview placeholder"
                        className="w-full h-auto"
                        key={visual.visual_id}
                      />

                      {/* Generate Preview Button (center overlay) */}
                      <div className="absolute inset-0 flex items-center justify-center bg-black/20">
                        <Button
                          size="lg"
                          onClick={handleGeneratePreview}
                          disabled={isGeneratingPreview}
                          className="bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-xl hover:shadow-2xl"
                        >
                          {isGeneratingPreview ? (
                            <>
                              <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                              AI Genereert DALL-E Preview...
                            </>
                          ) : (
                            <>
                              <Sparkles className="w-5 h-5 mr-2" />
                              Genereer AI Preview Image
                            </>
                          )}
                        </Button>
                      </div>

                      {/* Customize Button */}
                      <div className="absolute bottom-4 right-4">
                        <Button
                          size="sm"
                          onClick={() => setIsEditingKeywords(!isEditingKeywords)}
                          className="bg-white/90 hover:bg-white text-purple-700 border border-purple-200"
                        >
                          <Edit className="w-4 h-4 mr-2" />
                          {isEditingKeywords ? 'Annuleer' : 'Customize Visual'}
                        </Button>
                      </div>
                    </div>
                  )}

                  {/* Status Badge */}
                  <div className="absolute top-4 right-4">
                    {getStatusBadge(visual.status)}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Info Alert - Different for DALL-E vs Placeholder */}
            {previewImageUrl ? (
              <Alert className="bg-green-50 border-green-200">
                <Info className="w-4 h-4 text-green-600" />
                <AlertDescription className="ml-2 text-green-900">
                  <strong>✓ DALL-E Preview Generated</strong> - Dit is een AI-gegenereerde preview op basis van de visual metadata.
                  De definitieve video/animatie kan er anders uitzien maar volgt deze stijl en inhoud.
                </AlertDescription>
              </Alert>
            ) : (
              <Alert className="bg-blue-50 border-blue-200">
                <Info className="w-4 h-4 text-blue-600" />
                <AlertDescription className="ml-2 text-blue-900">
                  <strong>Dit is visual metadata</strong> - Klik "Genereer AI Preview Image" om een DALL-E preview te maken
                  op basis van de AI specs. De kleur toont het color scheme.
                </AlertDescription>
              </Alert>
            )}

            {/* Student View Preview — Shows the actual template the student sees */}
            <Card className="border-blue-200">
              <CardContent className="p-4">
                <div className="flex items-center gap-2 mb-4">
                  <MonitorPlay className="w-5 h-5 text-blue-600" />
                  <h4 className="font-semibold text-sm">Student View Preview</h4>
                  <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200 text-xs">
                    {resolveVisualType(visual.visual_id)}
                  </Badge>
                </div>
                <div className="border-2 border-dashed border-blue-200 rounded-xl p-4 bg-white dark:bg-gray-950">
                  <VisualTemplateRenderer
                    visualType={resolveVisualType(visual.visual_id)}
                    visualData={{
                      visual_id: visual.visual_id,
                      ai_concepts: visual.ai_concepts || [],
                      ai_intent: visual.ai_intent || '',
                      ai_methodology: visual.ai_methodology || '',
                      preview_image_url: previewImageUrl || undefined,
                      approved: visual.status === 'approved',
                    }}
                    content={visual.ai_intent || visual.lesson_title || ''}
                    isNL={true}
                    index={0}
                  />
                </div>
                <p className="text-xs text-muted-foreground mt-2">
                  Dit is exact wat de student ziet in de Course Player.
                </p>
              </CardContent>
            </Card>

            {/* Custom Keywords Editor */}
            {isEditingKeywords && (
              <Card className="border-purple-200 bg-purple-50">
                <CardContent className="p-4 space-y-4">
                  <div className="flex items-start gap-2 mb-3">
                    <Sparkles className="w-5 h-5 text-purple-600 mt-1" />
                    <div className="flex-1">
                      <h3 className="font-semibold text-purple-900 mb-1">
                        AI zal de visual opnieuw genereren met jouw specifieke wensen
                      </h3>
                      <p className="text-sm text-purple-700">
                        Beschrijf hoe je de visual wilt (stijl, kleuren, format, mood, elementen)
                      </p>
                    </div>
                  </div>

                  {/* Keyword Examples */}
                  <Alert className="bg-blue-50 border-blue-200">
                    <Lightbulb className="w-4 h-4 text-blue-600" />
                    <AlertDescription className="ml-2">
                      <p className="font-medium text-blue-900 mb-2">💡 Tips voor betere resultaten:</p>
                      <div className="space-y-1 text-sm text-blue-800">
                        {keywordExamples.map((example, idx) => (
                          <div key={idx}>
                            <strong>{example.label}:</strong> {example.examples}
                          </div>
                        ))}
                      </div>
                    </AlertDescription>
                  </Alert>

                  <div>
                    <Label className="mb-2 block">Jouw Custom Eisen</Label>
                    <Textarea
                      placeholder="Bijv: 'Modern animated flowchart with blue and purple colors, professional style, include icons for each step, timeline visualization, engaging and clear'"
                      value={customKeywords}
                      onChange={(e) => setCustomKeywords(e.target.value)}
                      rows={4}
                      className="resize-none"
                    />
                  </div>

                  <div className="flex gap-2">
                    <Button
                      onClick={handleRegenerateClick}
                      disabled={!customKeywords.trim() || isRegenerating}
                      className="bg-gradient-to-r from-purple-600 to-pink-600 text-white"
                    >
                      {isRegenerating ? (
                        <>
                          <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                          AI Genereert...
                        </>
                      ) : (
                        <>
                          <RefreshCw className="w-4 h-4 mr-2" />
                          Laat AI Opnieuw Genereren
                        </>
                      )}
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => {
                        setIsEditingKeywords(false);
                        setCustomKeywords('');
                      }}
                      disabled={isRegenerating}
                    >
                      Annuleer
                    </Button>
                  </div>

                  {previewImageUrl && (
                    <Alert className="bg-orange-50 border-orange-200">
                      <Info className="w-4 h-4 text-orange-600" />
                      <AlertDescription className="ml-2 text-orange-900 text-sm">
                        Na regeneratie moet je de DALL-E preview opnieuw genereren om de nieuwe visual te zien!
                      </AlertDescription>
                    </Alert>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Metadata Grid */}
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Layers className="w-4 h-4 text-gray-500" />
                    <h4 className="font-semibold text-sm">Lesson</h4>
                  </div>
                  <p className="text-sm text-gray-700">{visual.lesson_title}</p>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Sparkles className="w-4 h-4 text-purple-600" />
                    <h4 className="font-semibold text-sm">AI Confidence</h4>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-gradient-to-r from-purple-600 to-pink-600 h-2 rounded-full transition-all"
                        style={{ width: `${visual.ai_confidence}%` }}
                      />
                    </div>
                    <span className="text-sm font-medium">
                      {visual.ai_confidence}%
                    </span>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* AI Intent */}
            {visual.ai_intent && (
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="w-4 h-4 text-blue-600" />
                    <h4 className="font-semibold text-sm">Learning Intent</h4>
                  </div>
                  <p className="text-sm text-gray-700">{visual.ai_intent}</p>
                </CardContent>
              </Card>
            )}

            {/* AI Methodology */}
            {visual.ai_methodology && (
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-4 h-4 text-green-600" />
                    <h4 className="font-semibold text-sm">Visual Approach</h4>
                  </div>
                  <p className="text-sm text-gray-700">{visual.ai_methodology}</p>
                </CardContent>
              </Card>
            )}

            {/* AI Concepts */}
            {visual.ai_concepts && visual.ai_concepts.length > 0 && (
              <Card>
                <CardContent className="p-4">
                  <h4 className="font-semibold text-sm mb-3">Key Concepts</h4>
                  <div className="flex flex-wrap gap-2">
                    {visual.ai_concepts.map((concept, idx) => (
                      <Badge
                        key={idx}
                        variant="outline"
                        className="bg-purple-50 text-purple-700 border-purple-200"
                      >
                        {concept}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Current Custom Keywords */}
            {visual.custom_keywords && (
              <Card className="border-orange-200 bg-orange-50">
                <CardContent className="p-4">
                  <h4 className="font-semibold text-sm mb-2 text-orange-700">Huidige Custom Keywords</h4>
                  <p className="text-sm text-gray-700">{visual.custom_keywords}</p>
                </CardContent>
              </Card>
            )}

            {/* Visual ID */}
            <Card>
              <CardContent className="p-4">
                <h4 className="font-semibold text-sm mb-2">Visual ID</h4>
                <code className="text-xs bg-gray-100 px-2 py-1 rounded">
                  {visual.visual_id}
                </code>
              </CardContent>
            </Card>
          </div>
        </ScrollArea>

        {/* Action Buttons */}
        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>

          {visual.status === 'pending' && (
            <>
              <Button
                variant="destructive"
                onClick={() => {
                  onReject(visual.id);
                  onClose();
                }}
                className="bg-red-600 hover:bg-red-700"
              >
                <XCircle className="w-4 h-4 mr-2" />
                Reject
              </Button>
              <Button
                onClick={() => {
                  onApprove(visual.id);
                  onClose();
                }}
                className="bg-gradient-to-r from-purple-600 to-pink-600 text-white"
              >
                <CheckCircle2 className="w-4 h-4 mr-2" />
                Approve
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default VisualPreviewModal;