# Generated by Django 5.2.6 on 2026-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_meeting'),
        ('projects', '0012_manualmitigation_attachments_risk_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='+', to='projects.upload'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='+', to='projects.upload'),
        ),
    ]
