# Generated by Django 5.2.6 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_meeting_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meetingactionitem',
            new_name='meeting_act_meeting_10a47a_idx',
            old_name='meeting_acti_meeting_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingactionitem',
            new_name='meeting_act_source__c00e38_idx',
            old_name='meeting_acti_source_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingattendee',
            new_name='meeting_att_meeting_cd6846_idx',
            old_name='meeting_atte_meeting_presence_idx',
        ),
        migrations.AlterField(
            model_name='meetingactionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingattendee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
