# Generated by Django 5.2.6 on 2026-06-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_generatedstatusreport'),
        ('projects', '0023_riskforecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology', models.CharField(choices=[('scrum', 'Scrum'), ('kanban', 'Kanban'), ('agile', 'Agile'), ('waterfall', 'Waterfall'), ('lss-green', 'Lean Six Sigma — Green Belt'), ('lss-black', 'Lean Six Sigma — Black Belt'), ('hybrid', 'Hybrid')], max_length=20)),
                ('report_type', models.CharField(choices=[('sprint_report', 'Sprint Report'), ('service_delivery_review', 'Service Delivery Review'), ('iteration_report', 'Iteration Report'), ('phase_gate_report', 'Phase Gate Report'), ('tollgate_report', 'DMAIC Tollgate Report'), ('phase_report', 'Phase Report')], max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('scope_ref', models.CharField(blank=True, default='', max_length=200)),
                ('overall_rag', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('rag_scope', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('rag_schedule', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('rag_cost', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('rag_risk', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=5)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('auto_generated', models.BooleanField(default=True)),
                ('model_used', models.CharField(default='deterministic', max_length=64)),
                ('original_ai_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodology_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_reports', to='projects.project')),
            ],
            options={
                'db_table': 'methodology_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'methodology', '-created_at'], name='methodology_project_0bb9b2_idx')],
            },
        ),
    ]
