from rest_framework import serializers
from .models import (
    StatusReport, TrainingMaterial, ReportingItem, Meeting,
    GeneratedStatusReport, MethodologyReport,
)


class MethodologyReportSerializer(serializers.ModelSerializer):
    project_name = serializers.CharField(source="project.name", read_only=True)
    created_by_name = serializers.CharField(source="created_by.username", read_only=True)
    report_type_display = serializers.CharField(source="get_report_type_display", read_only=True)
    methodology_display = serializers.CharField(source="get_methodology_display", read_only=True)

    class Meta:
        model = MethodologyReport
        fields = [
            "id", "project", "project_name", "methodology", "methodology_display",
            "report_type", "report_type_display", "title", "period_start",
            "period_end", "scope_ref", "overall_rag", "rag_scope", "rag_schedule",
            "rag_cost", "rag_risk", "executive_summary", "highlights", "blockers",
            "next_steps", "metrics", "payload", "auto_generated", "model_used",
            "original_ai_response", "created_by", "created_by_name",
            "created_at", "updated_at",
        ]
        read_only_fields = [
            "created_by", "created_at", "updated_at", "model_used",
            "original_ai_response",
        ]


class GeneratedStatusReportSerializer(serializers.ModelSerializer):
    project_name = serializers.CharField(source="project.name", read_only=True)
    created_by_name = serializers.CharField(source="created_by.username", read_only=True)

    class Meta:
        model = GeneratedStatusReport
        fields = [
            "id", "project", "project_name", "period_start", "period_end",
            "metrics", "overall_rag", "rag_scope", "rag_schedule", "rag_cost",
            "rag_risk", "executive_summary", "highlights", "blockers",
            "next_steps", "model_used", "original_ai_response",
            "created_by", "created_by_name", "created_at",
        ]
        read_only_fields = fields

class StatusReportSerializer(serializers.ModelSerializer):
    id = serializers.CharField(read_only=True)  # String ID to match frontend
    
    class Meta:
        model = StatusReport
        fields = ['id', 'project', 'status', 'progress', 'last_updated', 'created_at', 'updated_at']
        read_only_fields = ['created_at', 'updated_at']
    
    def validate_progress(self, value):
        if value < 0 or value > 100:
            raise serializers.ValidationError("Progress must be between 0 and 100!")
        return value
    
    def to_representation(self, instance):
        """Convert the model instance to JSON representation"""
        representation = super().to_representation(instance)
        # Convert the integer ID to string to match frontend expectation
        representation['id'] = str(instance.id)
        return representation
    
    def create(self, validated_data):
        # The ID will be auto-generated by Django as an integer
        # but will be converted to string in to_representation
        return StatusReport.objects.create(**validated_data)

# Training Material Serializer
class TrainingMaterialSerializer(serializers.ModelSerializer):
    id = serializers.CharField(read_only=True)

    class Meta:
        model = TrainingMaterial
        fields = [
            'id',
            'project',
            'name',
            'audience',
            'format',
            'status',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['created_at', 'updated_at']

    def to_representation(self, instance):
        data = super().to_representation(instance)
        data['id'] = str(instance.id)
        return data
    
# Report Serializer
class ReportingItemSerializer(serializers.ModelSerializer):
    id = serializers.CharField(read_only=True)
    document = serializers.FileField(required=False, allow_null=True)

    class Meta:
        model = ReportingItem
        fields = [
            'id', 'project', 'name', 'frequency', 'type', 'start_date', 'view',
            'document', 'created_at', 'updated_at'
        ]
        read_only_fields = ['created_at', 'updated_at']

    def to_representation(self, instance):
        data = super().to_representation(instance)
        data['id'] = str(instance.id)
        request = self.context.get('request')
        if instance.document and request:
            data['document'] = request.build_absolute_uri(instance.document.url)
        return data
    

# Meeting Serializer
class MeetingSerializer(serializers.ModelSerializer):
    id = serializers.CharField(read_only=True)
    # Yanmar Meeting Minutes — nested read (MM-01 attendees, MM-02 action items).
    attendees = serializers.SerializerMethodField(read_only=True)
    action_items = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = Meeting
        fields = [
            'id', 'project', 'name', 'type', 'frequency',
            'date', 'time', 'location', 'agenda', 'participants',
            'status', 'created_at', 'updated_at',
            # Yanmar Meeting Minutes template — MM-04 / MM-05
            'customer_supplier', 'yanmar_meeting_room',
            'discussion_notes', 'conclusions',
            # MM-01 / MM-02 nested
            'attendees', 'action_items', 'previous_meeting',
        ]
        read_only_fields = ['created_at', 'updated_at']

    def get_attendees(self, obj):
        return MeetingAttendeeSerializer(obj.attendees.all(), many=True).data

    def get_action_items(self, obj):
        return MeetingActionItemSerializer(obj.action_items.all(), many=True).data

    def to_representation(self, instance):
        data = super().to_representation(instance)
        data['id'] = str(instance.id)
        return data


class MeetingOccurrenceSerializer(serializers.Serializer):
    # Derived “calendar rows”
    id = serializers.CharField()
    name = serializers.CharField()
    type = serializers.CharField()
    frequency = serializers.CharField()
    date = serializers.DateField()   # occurrence date
    time = serializers.TimeField()
    location = serializers.CharField(allow_blank=True)
    agenda = serializers.ListField(child=serializers.CharField())
    participants = serializers.ListField(child=serializers.CharField())
    status = serializers.CharField()



# ── Yanmar Meeting Minutes sub-resources (MM-01 / MM-02) ─────────────────
from .models import MeetingAttendee, MeetingActionItem


class MeetingAttendeeSerializer(serializers.ModelSerializer):
    user_name = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = MeetingAttendee
        fields = [
            "id", "meeting", "user", "user_name", "name_text",
            "position", "contact_info", "presence", "created_at",
        ]
        read_only_fields = ["created_at"]

    def get_user_name(self, obj):
        if obj.user:
            full = obj.user.get_full_name() if hasattr(obj.user, "get_full_name") else ""
            return full or getattr(obj.user, "username", "") or getattr(obj.user, "email", "")
        return obj.name_text


class MeetingActionItemSerializer(serializers.ModelSerializer):
    pic_name = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = MeetingActionItem
        fields = [
            "id", "meeting", "source_meeting", "no", "subject",
            "pic_user", "pic_name", "pic_text", "action_due",
            "status", "notes", "created_at", "updated_at",
        ]
        read_only_fields = ["created_at", "updated_at"]

    def get_pic_name(self, obj):
        if obj.pic_user:
            full = obj.pic_user.get_full_name() if hasattr(obj.pic_user, "get_full_name") else ""
            return full or getattr(obj.pic_user, "username", "") or getattr(obj.pic_user, "email", "")
        return obj.pic_text
