import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, TrendingUp, TrendingDown, Minus, AlertTriangle, Lightbulb } from "lucide-react";

interface ReportData {
  title: string;
  date: string;
  executive_summary: string;
  sections: { heading: string; content: string }[];
  recommendations: string[];
  risk_highlights: string[];
  kpis: { name: string; value: string; trend: string }[];
}

interface ReportModalProps {
  open: boolean;
  onClose: () => void;
  report: ReportData | null;
  loading: boolean;
}

const ReportModal: React.FC<ReportModalProps> = ({ open, onClose, report, loading }) => {
  const handleDownloadPDF = () => {
    if (!report) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html><html><head><title>${report.title}</title>
      <style>
        body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;padding:40px;color:#1a1a2e;line-height:1.6}
        h1{color:#7c3aed;font-size:28px;border-bottom:3px solid #7c3aed;padding-bottom:12px}
        h2{color:#4c1d95;font-size:20px;margin-top:28px;border-left:4px solid #7c3aed;padding-left:12px}
        .summary{background:#f5f3ff;padding:20px;border-radius:8px;margin:20px 0;border-left:4px solid #7c3aed}
        .kpi-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0}
        .kpi{background:#f9fafb;padding:16px;border-radius:8px;text-align:center;border:1px solid #e5e7eb}
        .kpi-name{font-size:12px;color:#6b7280;text-transform:uppercase}
        .kpi-value{font-size:24px;font-weight:bold;color:#7c3aed}
        .recommendations{background:#ecfdf5;padding:20px;border-radius:8px;margin:20px 0}
        .recommendations h2{color:#065f46;border-color:#10b981}
        .risks{background:#fff7ed;padding:20px;border-radius:8px;margin:20px 0}
        .risks h2{color:#9a3412;border-color:#f97316}
        ul{padding-left:20px}li{margin:8px 0}
        .footer{margin-top:40px;padding-top:20px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px;text-align:center}
      </style></head><body>
      <h1>${report.title}</h1>
      <div class="summary"><h2 style="margin-top:0">Executive Summary</h2><p>${report.executive_summary}</p></div>
      ${report.kpis?.length ? `<div class="kpi-grid">${report.kpis.map(k => `<div class="kpi"><div class="kpi-name">${k.name}</div><div class="kpi-value">${k.value}</div><div>${k.trend === 'up' ? '↑' : k.trend === 'down' ? '↓' : '→'} ${k.trend}</div></div>`).join('')}</div>` : ''}
      ${(report.sections || []).map(s => `<h2>${s.heading}</h2><p>${s.content}</p>`).join('')}
      ${report.recommendations?.length ? `<div class="recommendations"><h2 style="margin-top:0">Recommendations</h2><ul>${report.recommendations.map(r => `<li>${r}</li>`).join('')}</ul></div>` : ''}
      ${report.risk_highlights?.length ? `<div class="risks"><h2 style="margin-top:0">Risk Highlights</h2><ul>${report.risk_highlights.map(r => `<li>${r}</li>`).join('')}</ul></div>` : ''}
      <div class="footer">Generated by ProjeXtPal AI - ${new Date().toLocaleDateString()}</div>
      </body></html>`);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  const getTrendIcon = (trend: string) => {
    if (trend === 'up') return <TrendingUp className="w-4 h-4 text-green-500" />;
    if (trend === 'down') return <TrendingDown className="w-4 h-4 text-red-500" />;
    return <Minus className="w-4 h-4 text-gray-400" />;
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 space-y-4">
            <div className="w-16 h-16 rounded-full border-4 border-purple-200 border-t-purple-600 animate-spin" />
            <p className="text-lg font-semibold text-purple-700">Generating AI Report...</p>
            <p className="text-sm text-gray-500">Analyzing data and creating insights</p>
          </div>
        ) : report ? (
          <>
            <DialogHeader>
              <div className="flex items-center justify-between">
                <DialogTitle className="text-2xl bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                  {report.title}
                </DialogTitle>
                <Button onClick={handleDownloadPDF} className="bg-gradient-to-r from-purple-600 to-pink-600 text-white">
                  <Download className="w-4 h-4 mr-2" /> Download PDF
                </Button>
              </div>
              <DialogDescription>Generated: {new Date().toLocaleDateString()}</DialogDescription>
            </DialogHeader>

            <div className="space-y-6 mt-4">
              <div className="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-6 border border-purple-200 dark:border-purple-800">
                <h3 className="font-bold text-lg text-purple-800 dark:text-purple-300 mb-2">Executive Summary</h3>
                <p className="text-gray-700 dark:text-gray-300 whitespace-pre-line">{report.executive_summary}</p>
              </div>

              {report.kpis?.length > 0 && (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {report.kpis.map((kpi, i) => (
                    <div key={i} className="bg-white dark:bg-gray-800 rounded-lg p-4 border shadow-sm text-center">
                      <p className="text-xs text-gray-500 uppercase tracking-wider">{kpi.name}</p>
                      <p className="text-2xl font-bold text-purple-700 dark:text-purple-400 mt-1">{kpi.value}</p>
                      <div className="flex items-center justify-center gap-1 mt-1">
                        {getTrendIcon(kpi.trend)}
                        <span className="text-xs capitalize">{kpi.trend}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {report.sections?.map((section, i) => (
                <div key={i} className="space-y-2">
                  <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200 border-l-4 border-purple-500 pl-3">
                    {section.heading}
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400 whitespace-pre-line pl-3">{section.content}</p>
                </div>
              ))}

              {report.recommendations?.length > 0 && (
                <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-lg p-6 border border-emerald-200 dark:border-emerald-800">
                  <h3 className="font-bold text-lg text-emerald-800 dark:text-emerald-300 mb-3 flex items-center gap-2">
                    <Lightbulb className="w-5 h-5" /> Recommendations
                  </h3>
                  <ul className="space-y-2">
                    {report.recommendations.map((rec, i) => (
                      <li key={i} className="flex items-start gap-2 text-gray-700 dark:text-gray-300">
                        <span className="text-emerald-500 font-bold mt-0.5">•</span>{rec}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {report.risk_highlights?.length > 0 && (
                <div className="bg-orange-50 dark:bg-orange-900/20 rounded-lg p-6 border border-orange-200 dark:border-orange-800">
                  <h3 className="font-bold text-lg text-orange-800 dark:text-orange-300 mb-3 flex items-center gap-2">
                    <AlertTriangle className="w-5 h-5" /> Risk Highlights
                  </h3>
                  <ul className="space-y-2">
                    {report.risk_highlights.map((risk, i) => (
                      <li key={i} className="flex items-start gap-2 text-gray-700 dark:text-gray-300">
                        <span className="text-orange-500 font-bold mt-0.5">⚠</span>{risk}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="text-center text-xs text-gray-400 pt-4 border-t">
                Generated by ProjeXtPal AI • {new Date().toISOString().split('T')[0]}
              </div>
            </div>
          </>
        ) : null}
      </DialogContent>
    </Dialog>
  );
};

export default ReportModal;
