# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="SPCChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("x_bar_r", "X-bar R Chart"),
                            ("x_bar_s", "X-bar S Chart"),
                            ("i_mr", "Individual Moving Range"),
                            ("p_chart", "P Chart"),
                            ("np_chart", "NP Chart"),
                            ("c_chart", "C Chart"),
                            ("u_chart", "U Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ucl", models.FloatField(help_text="Upper Control Limit")),
                ("center_line", models.FloatField(help_text="Center Line / Mean")),
                ("lcl", models.FloatField(help_text="Lower Control Limit")),
                (
                    "usl",
                    models.FloatField(
                        blank=True, help_text="Upper Specification Limit", null=True
                    ),
                ),
                (
                    "lsl",
                    models.FloatField(
                        blank=True, help_text="Lower Specification Limit", null=True
                    ),
                ),
                ("data_points", models.JSONField(blank=True, default=list)),
                ("subgroup_size", models.IntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_black_spc_charts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "SPC Chart",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HypothesisTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("t_test", "T-Test"),
                            ("z_test", "Z-Test"),
                            ("chi_square", "Chi-Square"),
                            ("anova", "ANOVA"),
                            ("f_test", "F-Test"),
                            ("mann_whitney", "Mann-Whitney U"),
                            ("kruskal_wallis", "Kruskal-Wallis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("null_hypothesis", models.TextField()),
                ("alternative_hypothesis", models.TextField()),
                ("alpha", models.FloatField(default=0.05)),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("test_statistic", models.FloatField(blank=True, null=True)),
                ("conclusion", models.TextField(blank=True)),
                ("reject_null", models.BooleanField(blank=True, null=True)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_black_hypothesis_tests",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hypothesis Test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignOfExperiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("experiment_name", models.CharField(max_length=200)),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("full_factorial", "Full Factorial"),
                            ("fractional_factorial", "Fractional Factorial"),
                            ("taguchi", "Taguchi"),
                            ("response_surface", "Response Surface"),
                            ("plackett_burman", "Plackett-Burman"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=list, help_text="List of experimental factors"
                    ),
                ),
                ("levels", models.IntegerField(default=2)),
                ("response_variable", models.CharField(blank=True, max_length=200)),
                ("objective", models.TextField(blank=True)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("conclusion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_black_doe",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design of Experiment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("process_step", models.CharField(max_length=200)),
                ("control_method", models.CharField(max_length=200)),
                ("measurement_frequency", models.CharField(max_length=100)),
                ("specification_limits", models.CharField(blank=True, max_length=200)),
                ("reaction_plan", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lss_black_control_plans",
                        to="projects.project",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Plan",
                "ordering": ["-created_at"],
            },
        ),
    ]
