# Generated by Django 5.2.6 on 2026-06-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lss_black', '0002_lssblacktask_responsibles'),
        ('sixsigma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designofexperiment',
            name='improves_solution',
            field=models.ForeignKey(blank=True, help_text='The Improve-phase Solution this DOE optimises', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_experiments', to='sixsigma.solution'),
        ),
    ]
