# Generated by Django 5.2.6 on 2025-12-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionOfDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_dod', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_backlog', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('goal', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('team_capacity', models.IntegerField(blank=True, help_text='Total story points capacity', null=True)),
                ('went_well', models.TextField(blank=True, null=True)),
                ('to_improve', models.TextField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_sprints', to='projects.project')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DailyStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('blockers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='scrum.sprint')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('user_story', 'User Story'), ('bug', 'Bug'), ('task', 'Task'), ('spike', 'Spike'), ('epic', 'Epic')], default='user_story', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('removed', 'Removed')], default='new', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_assigned_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scrum.backlogitem')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_reported_items', to=settings.AUTH_USER_MODEL)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scrum.productbacklog')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='scrum.sprint')),
            ],
            options={
                'ordering': ['order', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('went_well', models.TextField(blank=True, null=True)),
                ('to_improve', models.TextField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True, null=True)),
                ('team_morale', models.IntegerField(blank=True, help_text='1-5 scale', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='scrum.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='SprintReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('demo_notes', models.TextField(blank=True, null=True)),
                ('stakeholder_feedback', models.TextField(blank=True, null=True)),
                ('accepted_items', models.TextField(blank=True, null=True)),
                ('rejected_items', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scrum.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='StandupUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday', models.TextField(blank=True, null=True)),
                ('today', models.TextField(blank=True, null=True)),
                ('blockers', models.TextField(blank=True, null=True)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='scrum.dailystandup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_points', models.IntegerField(default=0)),
                ('completed_points', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_velocity', to='projects.project')),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='velocity', to='scrum.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('product_owner', 'Product Owner'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('stakeholder', 'Stakeholder')], default='developer', max_length=20)),
                ('capacity_per_sprint', models.IntegerField(blank=True, help_text='Story points per sprint', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_team', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SprintBurndown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_points', models.IntegerField(default=0)),
                ('completed_points', models.IntegerField(default=0)),
                ('ideal_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_data', to='scrum.sprint')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('sprint', 'date')},
            },
        ),
    ]
