# Generated by Django 5.2.6 on 2026-04-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_alter_definitionofdone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoDChecklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dod_completions_marked', to=settings.AUTH_USER_MODEL)),
                ('dod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scrum.definitionofdone')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dod_entries', to='scrum.sprint')),
            ],
            options={
                'ordering': ['sprint', 'dod_item__order'],
                'unique_together': {('dod_item', 'sprint')},
            },
        ),
    ]
