# Generated by Django 5.2.6 on 2025-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='execution_stakeholder_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of execution stakeholder IDs'),
        ),
    ]
