# Generated by Django 5.2.6 on 2025-10-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('newsletters', '0002_newsletter_execution_stakeholder_ids'),
        ('projects', '0004_add_health_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='recipient_type',
            field=models.CharField(choices=[('project_team', 'Project Team'), ('stakeholders', 'All Stakeholders'), ('steering_committee', 'Steering Committee'), ('custom', 'Custom Recipients'), ('mailing_list', 'Mailing Lists')], default='project_team', max_length=50),
        ),
        migrations.CreateModel(
            name='ExternalSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_subscribers', to='accounts.company')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('list_type', models.CharField(choices=[('external', 'External Subscribers'), ('project_team', 'Project Team'), ('project_stakeholders', 'Project Stakeholders'), ('custom', 'Custom List')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mailing_lists', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='newsletters.mailinglist'),
        ),
        migrations.CreateModel(
            name='MailingListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('external_subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_memberships', to='newsletters.externalsubscriber')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='newsletters.mailinglist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='externalsubscriber',
            index=models.Index(fields=['company', 'is_subscribed'], name='newsletters_company_955f9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalsubscriber',
            unique_together={('email', 'company')},
        ),
        migrations.AddIndex(
            model_name='mailinglist',
            index=models.Index(fields=['company', 'is_active'], name='newsletters_company_621e87_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglist',
            index=models.Index(fields=['company', 'list_type'], name='newsletters_company_c93c46_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglistmember',
            index=models.Index(fields=['mailing_list', 'added_at'], name='newsletters_mailing_4dc878_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailinglistmember',
            unique_together={('mailing_list', 'external_subscriber'), ('mailing_list', 'user')},
        ),
    ]
