# Generated by Django 5.2.6 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletter_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='crm_users',
            field=models.JSONField(blank=True, default=list, help_text='List of CRM users (from external API) with email, first_name, last_name'),
        ),
    ]
