# Generated by Django 5.2.6 on 2025-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletter_crm_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='project_recipients',
            field=models.JSONField(blank=True, default=list, help_text="List of project recipients in format [{'project_id': 1, 'type': 'team'}, {'project_id': 1, 'type': 'stakeholders'}]"),
        ),
    ]
