# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgileReleaseTrain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("team_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safe_arts",
                        to="projects.project",
                    ),
                ),
                (
                    "rte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Release Train Engineer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_arts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agile Release Train",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramIncrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("iteration_count", models.IntegerField(default=5)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("pi_planning_date", models.DateField(blank=True, null=True)),
                ("innovation_sprint", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safe_pis",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Increment",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PIObjective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "business_value",
                    models.IntegerField(default=0, help_text="Business value 1-10"),
                ),
                ("committed", models.BooleanField(default=True)),
                ("achieved", models.BooleanField(default=False)),
                ("team", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="safe.programincrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "PI Objective",
                "ordering": ["-business_value"],
            },
        ),
        migrations.CreateModel(
            name="ARTSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("attendees", models.JSONField(default=list)),
                ("decisions", models.JSONField(default=list)),
                ("impediments", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncs",
                        to="safe.agilereleasetrain",
                    ),
                ),
            ],
            options={
                "verbose_name": "ART Sync",
                "ordering": ["-meeting_date"],
            },
        ),
    ]
