# Generated by Django 5.2.6 on 2026-04-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_portfolio'),
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agilereleasetrain',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_arts', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='programincrement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_pis', to='programs.program'),
        ),
    ]
