# Generated by Django 5.2.6 on 2026-06-04 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        ('safe', '0002_alter_agilereleasetrain_program_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='piobjective',
            name='actual_value',
            field=models.IntegerField(default=0, help_text='Actual delivered value 1-10 (scored at PI end)'),
        ),
        migrations.AddField(
            model_name='piobjective',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_pi_objectives', to='programs.programteam'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('benefit_hypothesis', models.TextField(blank=True, help_text='Why this feature delivers value.')),
                ('business_value', models.IntegerField(default=1, help_text='WSJF: user/business value')),
                ('time_criticality', models.IntegerField(default=1, help_text='WSJF: time criticality')),
                ('risk_reduction', models.IntegerField(default=1, help_text='WSJF: risk reduction / opportunity enablement')),
                ('job_size', models.IntegerField(default=1, help_text='WSJF: job size (denominator)')),
                ('state', models.CharField(choices=[('funnel', 'Funnel'), ('analyzing', 'Analyzing'), ('backlog', 'Program Backlog'), ('implementing', 'Implementing'), ('validating', 'Validating'), ('done', 'Done')], default='funnel', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='safe.agilereleasetrain')),
                ('pi', models.ForeignKey(blank=True, help_text='The PI this feature is planned into (null = still in the funnel/backlog).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='safe.programincrement')),
            ],
            options={
                'verbose_name': 'SAFe Feature',
                'ordering': ['order', '-business_value'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('roam', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('owned', 'Owned'), ('accepted', 'Accepted'), ('mitigated', 'Mitigated')], help_text='ROAM disposition. Blank = not yet triaged.', max_length=12)),
                ('needed_by_iteration', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_dependencies', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='safe.programincrement')),
                ('source_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='safe.feature')),
                ('target_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='safe.feature')),
            ],
            options={
                'verbose_name': 'SAFe Dependency',
                'verbose_name_plural': 'SAFe Dependencies',
                'ordering': ['needed_by_iteration', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectAdapt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('predictability', models.IntegerField(blank=True, help_text='PI predictability %, snapshotted at the event.', null=True)),
                ('problems', models.JSONField(blank=True, default=list, help_text='Problem-solving workshop items.')),
                ('improvement_items', models.JSONField(blank=True, default=list, help_text='Improvement backlog items for the next PI.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspect_adapt', to='safe.programincrement')),
            ],
            options={
                'verbose_name': 'Inspect & Adapt',
                'verbose_name_plural': 'Inspect & Adapt',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('story_points', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('done', 'Done')], default='backlog', max_length=20)),
                ('iteration', models.IntegerField(blank=True, help_text='Iteration (sprint) number within the PI.', null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='safe.feature')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_stories', to='programs.programteam')),
            ],
            options={
                'verbose_name': 'SAFe Story',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iteration', models.IntegerField(default=1, help_text='Iteration number within the PI.')),
                ('demo_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features_demoed', models.ManyToManyField(blank=True, related_name='demos', to='safe.feature')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_demos', to='safe.programincrement')),
            ],
            options={
                'verbose_name': 'System Demo',
                'ordering': ['iteration'],
            },
        ),
    ]
