import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'nl' | 'fr';

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      features: 'Features',
      pricing: 'Pricing',
      contact: 'Contact',
      login: 'Log In',
      logout: 'Logout',
      openApp: 'Open App',
      website: 'Website',
      dashboard: 'Dashboard',
      projects: 'Projects',
      programs: 'Programs',
      team: 'Team',
      settings: 'Settings',
      academy: {
        title: 'Academy',
        comingSoon: 'Coming Soon',
        new: 'New',
        marketplace: 'Training Marketplace',
        marketplaceDesc: '100+ courses & certificates',
        methodologies: 'Management Methodologies',
        methodologiesDesc: 'Scrum, Kanban, PRINCE2, SAFe & more',
        pricing: 'Academy Pricing',
        pricingDesc: 'Subscriptions & certifications',
        requestQuote: 'Request Quote',
        requestQuoteDesc: 'For teams & companies',
      }
    },
    hero: {
      badge: 'Next-Gen Project Management',
      title1: 'Master Your Projects',
      title2: 'with AI-Powered Intelligence',
      subtitle: 'The all-in-one platform for program & project management. Powered by AI, built for teams that want to achieve more.',
      programManagement: 'Program Management',
      projectTracking: 'Project Tracking',
      aiInsights: 'AI Insights',
      timeManagement: 'Time Management',
      getStarted: 'Get Started Free',
      watchDemo: 'Watch Demo',
      aiGreeting: "Hi! I'm your AI project assistant. I can help you with:",
      aiCapabilities: [
        'Creating project plans & timelines',
        'Risk analysis & mitigation',
        'Status reports & dashboards',
        'Team capacity planning',
      ],
      askPlaceholder: 'Ask me anything about your projects...',
      stats: {
        projects: 'Projects Managed',
        programs: 'Active Programs',
        hours: 'Hours Tracked',
        success: 'Success Rate',
      },
      aiPowered: 'AI-Powered',
      sales: 'Sales',
      online: 'Online',
      welcome: '👋 Welcome to ProjeXtPal! I\'m happy to help with:',
      capabilities: [
        'Explanation of our AI features',
        'Pricing and subscriptions',
        'Scheduling a demo',
        'Technical questions'
      ],
      poweredBy: 'Powered by AI • Average response: 2 sec',
      quickPrompts: [
        'What can ProjeXtPal do for me?',
        'How does AI improve my projects?',
        'Is there a free trial?',
        'What does ProjeXtPal cost?'
      ],
      chatPlaceholder: '💬 Ask your question about ProjeXtPal...',
      safePrivate: 'Safe & private',
      instantResponse: 'Instant response',
    },
    about: {
      badge: 'Why ProjeXtPal',
      title1: 'Everything You Need',
      title2: 'In One Platform',
      description: "ProjeXtPal combines powerful project management with intelligent AI assistance. Whether you're managing a single project or an entire portfolio, we've got you covered.",
      capabilities: [
        'Multi-methodology support (Agile, Scrum, PRINCE2, SAFe)',
        'Real-time collaboration & communication',
        'Automated reporting & insights',
        'Integrated time tracking',
        'AI-powered recommendations',
      ],
      getStarted: 'Get Started',
      programs: 'Programs',
      programsDesc: 'Manage portfolios and complex programs with ease.',
      projects: 'Projects',
      projectsDesc: 'Track tasks, timelines, and deliverables efficiently.',
      aiPowered: 'AI-Powered',
      aiPoweredDesc: 'Get intelligent insights and recommendations powered by advanced AI.',
      smartEntry: 'Smart Data Entry',
      aiReports: 'AI Reports',
      methodologyAdvisor: 'Methodology Advisor',
      pillars: [
        { title: 'Projects', desc: 'AI-powered project management' },
        { title: 'Programs', desc: 'Portfolio & programs' },
        { title: 'Trainings', desc: '118+ learning modules' },
        { title: 'AI', desc: 'Intelligent assistance' }
      ]
    },
    features: {
      badge: 'Powerful Features',
      title1: 'Tools That',
      title2: 'Empower Your Team',
      items: [
        { title: 'Program Management', desc: 'Oversee multiple projects with portfolio dashboards and strategic alignment.' },
        { title: 'Project Tracking', desc: 'Gantt charts, Kanban boards, and milestone tracking all in one place.' },
        { title: 'AI Assistant', desc: 'Get instant answers, generate reports, and receive smart recommendations.' },
        { title: 'Time Tracking', desc: 'Log hours, track productivity, and manage team capacity effortlessly.' },
        { title: 'Team Collaboration', desc: 'Real-time updates, comments, and notifications keep everyone aligned.' },
        { title: 'Smart Automation', desc: 'Automate repetitive tasks and focus on what matters most.' },
        { title: 'Analytics & Reports', desc: 'Beautiful dashboards and exportable reports at your fingertips.' },
        { title: 'Risk Management', desc: 'Identify, assess, and mitigate risks before they become issues.' },
        { title: 'Resource Planning', desc: 'Optimize team allocation and prevent burnout with smart planning.' },
      ],
      startUsing: 'Start Using ProjeXtPal',
    },
    demo: {
      badge: 'See It In Action',
      title1: 'Experience',
      title2: 'The Power of ProjeXtPal',
      aiOnline: 'AI Online',
      aiInsight: 'AI Insight',
      aiInsightText: 'Project "Digital Transformation" is 15% ahead of schedule. Consider reallocating resources to the delayed "CRM Integration" project.',
      tryIt: 'Try It Yourself',
    },
    app: {
      totalPrograms: 'Total Programs',
      totalProjects: 'Total Projects',
      dashboardTitle: 'Portfolio Dashboard',
      dashboardSubtitle: 'Your complete project & program overview',
      aiSummary: 'AI Summary',
      programsStatus: 'Programs Status',
      projectsStatus: 'Projects Status',
      active: 'Active',
      inProgress: 'In Progress',
      atRisk: 'At Risk',
      budget: 'Budget',
      totalBudget: 'Total Budget',
      avgProgress: 'Avg Progress',
      newProgram: 'New Program',
      newProject: 'New Project',
      viewAll: 'View All',
      name: 'Name',
      methodology: 'Methodology',
      progress: 'Progress',
      status: 'Status',
      health: 'Health',
      dueDate: 'Due Date',
      planning: 'Planning',
      pending: 'Pending',
      quickActions: 'Quick Actions',
      aiAssistant: 'AI Assistant',
      programsOverview: 'Programs Overview',
      projectsOverview: 'Projects Overview',
      completed: 'Completed',
      framework: 'Framework',
      programName: 'Program Name',
      projects: 'Projects',
      requiresAttention: 'Requires Attention',
      total: 'Total',
      totalAllocated: 'Total Allocated',
      activePrograms: 'Active Programs',
      activeProjects: 'Active Projects',
      onHold: 'On Hold',
    },
    timeTracking: {
      title: 'Time Tracking',
      subtitle: 'Track your time across projects and tasks',
      aiInsights: 'AI Insights',
      smartEntry: 'Smart Entry',
      aiReport: 'AI Report',
      newTimeEntry: 'New Time Entry',
      today: 'Today',
      thisWeek: 'This Week',
      activeTimer: 'Active Timer',
      project: 'Project',
      task: 'Task',
      startTimer: 'Start Timer',
      stopSave: 'Stop & Save',
      timeReports: 'Time Reports',
      weekly: 'Weekly',
      monthly: 'Monthly',
      dailyHours: 'Daily Hours',
      weeklyHours: 'Weekly Hours',
      projectDistribution: 'Project Distribution',
      totalHours: 'Total Hours',
      totalEntries: 'Total Entries',
      projects: 'Projects',
      dailyAverage: 'Daily Average',
      recentEntries: 'Recent Time Entries',
      filters: 'Filters',
      clearFilters: 'Clear Filters',
      allProjects: 'All projects',
      allMembers: 'All members',
      teamMember: 'Team Member',
      startDate: 'Start Date',
      endDate: 'End Date',
      showing: 'Showing',
      of: 'of',
      entries: 'entries',
      noEntries: 'No time entries match the current filters',
      clearAllFilters: 'Clear all filters',
      logTimeEntry: 'Log Time Entry',
      selectProject: 'Select project',
      selectTask: 'Select task',
      date: 'Date',
      hours: 'Hours',
      minutes: 'Minutes',
      description: 'Description (optional)',
      saveTimeEntry: 'Save Time Entry',
      aiProductivityInsights: 'AI Productivity Insights',
      aiInsightsDesc: 'AI-powered analysis of your time tracking patterns.',
      analyzeMyTime: 'Analyze My Time',
      analyzingPatterns: 'Analyzing your productivity patterns...',
      refreshAnalysis: 'Refresh Analysis',
      close: 'Close',
      aiSmartEntry: 'AI Smart Time Entry',
      aiSmartEntryDesc: 'Describe your work and AI will create the time entry.',
      generateEntry: 'Generate Entry',
      processing: 'Processing...',
      addEntry: 'Add Entry',
      tryAgain: 'Try Again',
      aiSuggestion: 'AI Suggestion',
      duration: 'Duration',
      aiWeeklyReport: 'AI Weekly Report',
      aiReportDesc: 'Generate a professional time report summary.',
      generateReport: 'Generate Report',
      generatingReport: 'Generating your report...',
      copyReport: 'Copy Report',
      regenerate: 'Regenerate',
    },
    programs: {
      title: 'Programs',
      subtitle: 'Manage your program portfolio',
      totalPrograms: 'Total Programs',
      totalProjects: 'Total Projects',
      newProgram: 'New Program',
      createProgram: 'Create Program',
      createNewProgram: 'Create New Program',
      editProgram: 'Edit Program',
      deleteProgram: 'Delete Program',
      programDetails: 'Program Details',
      programName: 'Program Name',
      programNameRequired: 'Program name is required',
      description: 'Description',
      strategicObjective: 'Strategic Objective',
      departments: 'Departments',
      departmentsPlaceholder: 'Enter departments',
      budget: 'Budget',
      budgetPlaceholder: 'Enter budget',
      totalBudget: 'Total Budget',
      spent: 'Spent',
      duration: 'Duration',
      durationPlaceholder: 'Duration in months',
      months: 'months',
      startDate: 'Start Date',
      planning: 'Planning',
      active: 'Active',
      completed: 'Completed',
      atRisk: 'At Risk',
      health: 'Health',
      projects: 'Projects',
      unassigned: 'Unassigned',
      allStatus: 'All Status',
      allMethods: 'All Methodologies',
      searchPlaceholder: 'Search programs...',
      noPrograms: 'No programs found',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      updateDetails: 'Update Details',
      deleteConfirm: 'Are you sure you want to delete this program?',
      createDescription: 'Create a new program to manage multiple related projects',
      manual: 'Manual Entry',
      aiAssistant: 'AI Assistant',
      aiAssistantDesc: 'Let AI help you set up your program',
      describeProgram: 'Describe Your Program',
      describeProgramHint: 'Tell us about your program goals and scope',
      ideaPlaceholder: 'E.g., Digital transformation initiative for modernizing our customer service platforms...',
      ideaTip: 'The more details you provide, the better AI can help',
      analyzeRecommend: 'Analyze & Recommend',
      analyzing: 'Analyzing your program...',
      recommendedMethodology: 'Recommended Methodology',
      match: 'Match',
      orChooseAnother: 'Or choose another methodology',
      recommendationHint: 'Based on your program description',
      reviewProgram: 'Review Program Details',
      reviewDetails: 'Review the generated details and make adjustments',
      reviewHint: 'You can edit any field before creating',
      back: 'Back',
      creatingProgram: 'Creating program...',
      settingUp: 'Setting up your program...',
      generateWithAI: 'Generate with AI',
      review: 'Review',
      methodologies: {
        safe: 'SAFe',
        safeDesc: 'Scaled Agile Framework for enterprise-wide agile transformation',
        msp: 'MSP',
        mspDesc: 'Managing Successful Programmes - governance-focused approach',
        pmi: 'PMI Program Management',
        pmiDesc: 'PMI standard for program management with benefits realization focus',
        prince2: 'PRINCE2 Programme',
        prince2Desc: 'PRINCE2 methodology adapted for programme management',
        hybrid: 'Hybrid',
        hybridDesc: 'Flexible combination of methodologies',
      },
    },
    pricing: {
      badge: 'Simple Pricing',
      title1: 'Choose The Plan',
      title2: 'That Fits Your Needs',
      popular: 'Most Popular',
      monthly: '/month',
      getStarted: 'Get Started',
      contactUs: 'Contact Us',
      plans: [
        {
          name: 'Basic',
          desc: 'Perfect for small teams getting started.',
          price: '€25',
          features: ['Up to 5 users', 'Up to 10 projects', '5 GB storage', 'Basic AI assistance', 'Email support'],
          academy: 'optional',
        },
        {
          name: 'Professional',
          desc: 'For growing teams that need more power.',
          price: '€75',
          features: ['Up to 25 users', 'Up to 50 projects', '25 GB storage', 'Advanced AI features', 'Priority support', 'Custom reports'],
          academy: 'optional',
        },
        {
          name: 'Enterprise',
          desc: 'For large organizations with complex needs.',
          price: '€200',
          features: ['Unlimited users', 'Unlimited projects', 'Unlimited storage', 'SSO & advanced security', 'Dedicated manager', 'Custom integrations', '✓ Learning Academy included'],
          academy: 'included',
        },
        {
          name: 'Custom+',
          desc: 'Tailored solution for your organization.',
          price: 'Quote',
          features: ['Everything in Enterprise', 'On-premise deployment', 'Custom SLA', 'Dedicated infrastructure', 'White-label options', '24/7 support'],
          academy: 'optional',
        },
      ],
    },
    contact: {
      badge: 'Get In Touch',
      title: "Let's Talk",
      letsTalk: "We'd Love To Hear From You",
      description: 'Questions about ProjeXtPal? Want to schedule a demo? Our team is here to help.',
      name: 'Your Name',
      email: 'Your Email',
      message: 'Your Message',
      send: 'Send Message',
    },
    faq: {
      title: 'Frequently Asked Questions',
      items: [
        { q: 'What methodologies does ProjeXtPal support?', a: 'ProjeXtPal supports Agile, Scrum, Kanban, PRINCE2, SAFe, Lean Six Sigma, and traditional Waterfall methodologies.' },
        { q: 'Is there a free trial?', a: 'Yes! Our Basic plan includes core features to get you started. No credit card required.' },
        { q: 'Can I import data from other tools?', a: 'Absolutely. We support imports from Jira, Asana, Monday, Trello, MS Project, and Excel.' },
        { q: 'How does the AI assistant work?', a: 'Our AI is trained on project management best practices and your project data to provide contextual recommendations and automate routine tasks.' },
      ],
    },
    footer: {
      description: 'AI-powered project management for modern teams.',
      product: 'Product',
      company: 'Company',
      legal: 'Legal',
      rights: 'All rights reserved.',
      cta: {
        title1: 'Ready to Transform',
        title2: 'Your Project Management?',
      },
      demo: 'Demo',
      privacy: 'Privacy',
      terms: 'Terms',
      academy: {
        courses: 'Courses',
        methodologies: 'Methodologies',
        pricing: 'Pricing',
      }
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      loading: 'Loading...',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      close: 'Close',
      success: 'Success',
      error: 'Error',
      retry: 'Retry',
      projectDeleted: 'Project deleted successfully',
      projectCreated: 'Project created successfully!',
      projectUpdated: 'Project updated successfully',
      programDeleted: 'Program deleted successfully',
      programCreated: 'Program created successfully!',
      programUpdated: 'Program updated successfully',
      deleteFailed: 'Delete failed',
      saveFailed: 'Save failed',
      createFailed: 'Create failed',
      updateFailed: 'Update failed',
      describeFirst: 'Please describe your idea first',
      nameRequired: 'Name is required',
      aiUnavailable: 'AI temporarily unavailable. Please try manually.',
      aiAnalysisFailed: 'AI analysis failed. Please try again.',
      detailsGenerated: 'Details generated! Review and adjust as needed.',
      descriptionGenerated: 'Description generated!',
      objectiveGenerated: 'Strategic objective generated!',
      generateFailed: 'Could not generate content',
      teamMemberAdded: 'Team member added',
      teamMemberRemoved: 'Team member removed',
      addFailed: 'Add failed',
      removeFailed: 'Remove failed',
      titleAmountRequired: 'Title and amount are required',
      expenseDeleted: 'Expense deleted',
      passwordMinLength: 'Password must be at least 8 characters',
      passwordsMismatch: 'Passwords do not match',
      passwordReset: 'Password reset! You can now log in.',
    },
    sidebar: {
      dashboard: "Dashboard",
      aiAssistant: "AI Chat",
      programs: "Programs",
      allProjects: "Projects",
      timeTracking: "Time Tracking",
      team: "Team",
      surveys: "Surveys",
      postProject: "Post Project",
      adminPortal: "Admin Portal",
      governance: "Governance",
      portfolios: "Portfolios",
      boards: "Boards",
      stakeholders: "Stakeholders",
      reports: "Reports",
      profile: "Profile",
      settings: "Settings",
      academy: "Academy",
      content: "Content",
      notes: "Notes",
      resources: "Resources",
      questions: "Questions",
      skills: "Skills",
      simulation: "Simulation",
      practice: "Practice",
      exam: "Exam",
      certificate: "Certificate",
      quiz: "Quiz",
      upgradeRequired: "Upgrade Required",
      upgradeDescription: "is available with a paid subscription.",
      viewPlans: "View Plans",
      currentPlan: "Current Plan",
      managePlan: "Manage Plan",
    },
    methodologyTerms: {
      // Common
      "Dashboard": "Dashboard",
      "Overview": "Overview",
      "Team": "Team",
      "Budget": "Budget",
      "Governance": "Governance",
      "Risks": "Risks",
      "Resources": "Resources",
      "Roadmap": "Roadmap",
      "Milestones": "Milestones",
      "Benefits": "Benefits",
      "Stakeholders": "Stakeholders",
      "Communications": "Communications",
      "Projects": "Projects",
      "Reports": "Reports",
      "Management": "Management",
      "Execution": "Execution",
      "Planning": "Planning",
      "Schedule": "Schedule",
      "Charter": "Charter",
      // PRINCE2
      "Project Initiation": "Project Initiation",
      "Stage Management": "Stage Management",
      "Project Closure": "Project Closure",
      "Business Case": "Business Case",
      "Project Brief": "Project Brief",
      "Stage Plan": "Stage Plan",
      "Work Packages": "Work Packages",
      "Stage Gates": "Stage Gates",
      "Tolerances": "Tolerances",
      "Project Board": "Project Board",
      "Highlight Reports": "Highlight Reports",
      "Issues & Risks": "Issues & Risks",
      "Change Control": "Change Control",
      "Closure Checklist": "Closure Checklist",
      "End Project Report": "End Project Report",
      "Lessons Log": "Lessons Log",
      "Benefits Review": "Benefits Review",
      "Exception Reports": "Exception Reports",
      // Scrum
      "Scrum Setup": "Scrum Setup",
      "Definition of Done": "Definition of Done",
      "Product Backlog": "Product Backlog",
      "Backlog": "Backlog",
      "Sprint Management": "Sprint Management",
      "Sprint Board": "Sprint Board",
      "Velocity": "Velocity",
      "Increments": "Increments",
      "Scrum Events": "Scrum Events",
      "Daily Standup": "Daily Standup",
      "Retrospective": "Retrospective",
      "Sprint Planning": "Sprint Planning",
      "Sprint Review": "Sprint Review",
      // Kanban
      "Kanban Setup": "Kanban Setup",
      "Board Configuration": "Board Configuration",
      "WIP Limits": "WIP Limits",
      "Work Policies": "Work Policies",
      "Kanban Board": "Kanban Board",
      "Work Items": "Work Items",
      "Board View": "Board View",
      "Blocked Items": "Blocked Items",
      "Flow Metrics": "Flow Metrics",
      "Metrics Dashboard": "Metrics Dashboard",
      "Cumulative Flow": "Cumulative Flow",
      "Continuous Improvement": "Continuous Improvement",
      "Kaizen": "Kaizen",
      // Agile
      "Foundation": "Foundation",
      "Discovery": "Discovery",
      "Product Vision": "Product Vision",
      "User Personas": "User Personas",
      "Release Planning": "Release Planning",
      "Iteration Board": "Iteration Board",
      "Daily Progress": "Daily Progress",
      "Review": "Review",
      // Waterfall
      "Requirements": "Requirements",
      "Gantt Chart": "Gantt Chart",
      "Phases": "Phases",
      "Design": "Design",
      "Development": "Development",
      "Testing": "Testing",
      "Deployment": "Deployment",
      "Maintenance": "Maintenance",
      "Control": "Control",
      "Change Requests": "Change Requests",
      "Phase Gates": "Phase Gates",
      "Baselines": "Baselines",
      "Issues": "Issues",
      "Deliverables": "Deliverables",
      // Lean Six Sigma
      "Define": "Define",
      "Measure": "Measure",
      "Analyze": "Analyze",
      "Improve": "Improve",
      "Project Charter": "Project Charter",
      "SIPOC": "SIPOC",
      "Voice of Customer": "Voice of Customer",
      "Data Collection": "Data Collection",
      "Process Map": "Process Map",
      "Baseline Metrics": "Baseline Metrics",
      "MSA Report": "MSA Report",
      "Root Cause Analysis": "Root Cause Analysis",
      "Fishbone Diagram": "Fishbone Diagram",
      "Pareto Chart": "Pareto Chart",
      "Hypothesis Tests": "Hypothesis Tests",
      "Regression Analysis": "Regression Analysis",
      "Solution Design": "Solution Design",
      "FMEA": "FMEA",
      "Pilot Plan": "Pilot Plan",
      "Implementation": "Implementation",
      "Control Plan": "Control Plan",
      "SPC Charts": "SPC Charts",
      "Monitoring": "Monitoring",
      "Tollgate Review": "Tollgate Review",
      "Closure": "Closure",
      // SAFe
      "Program Overview": "Program Overview",
      "ART Overview": "ART Overview",
      "Program Increments": "Program Increments",
      "Current PI": "Current PI",
      "PI Planning": "PI Planning",
      "PI Objectives": "PI Objectives",
      "Features": "Features",
      "System Demo": "System Demo",
      "Inspect & Adapt": "Inspect & Adapt",
      // MSP
      "Programme Overview": "Programme Overview",
      "Blueprint": "Blueprint",
      "Benefits Management": "Benefits Management",
      "Benefits Map": "Benefits Map",
      "Benefits Profiles": "Benefits Profiles",
      "Realization Plan": "Realization Plan",
      "Tranches": "Tranches",
      "Tranche Plan": "Tranche Plan",
      "Transitions": "Transitions",
      "Stakeholder Engagement": "Stakeholder Engagement",
      "Stakeholder Map": "Stakeholder Map",
      "Programme Board": "Programme Board",
      "Risks & Issues": "Risks & Issues",
      // PMI
      "Program Lifecycle": "Program Lifecycle",
      "Benefits Realization": "Benefits Realization",
      "Benefits Register": "Benefits Register",
      "KPIs": "KPIs",
      "Program Management": "Program Management",
      // PRINCE2 Programme
      "Tranche Management": "Tranche Management",
      // Hybrid
      "Project Foundation": "Project Foundation",
      "Workflow": "Workflow",
      "Planning & Design": "Planning & Design",
      "Timeline": "Timeline",
      "Tasks": "Tasks",
      "RACI": "RACI",
      "Dependencies": "Dependencies",
      "Calendar": "Calendar",
      "Workflow Diagram": "Workflow Diagram",
      "System Integration": "System Integration",
      "Execution & Governance": "Execution & Governance",
      "Communication": "Communication",
      "Newsletters": "Newsletters",
      "Status Reporting": "Status Reporting",
      "Meeting": "Meeting",
      "Reporting": "Reporting",
      "Deployment Strategy": "Deployment Strategy",
      "Monitoring & Closure": "Monitoring & Closure",
      "Document Library": "Document Library",
      "All Documents": "All Documents",
      "Stages": "Stages",
      "Training": "Training",
      "Lessons Learned & Surveys": "Lessons Learned & Surveys",
    },
  },
  nl: {
    nav: {
      home: 'Home',
      about: 'Over Ons',
      features: 'Functies',
      pricing: 'Prijzen',
      contact: 'Contact',
      login: 'Inloggen',
      logout: 'Uitloggen',
      openApp: 'Open App',
      website: 'Website',
      dashboard: 'Dashboard',
      projects: 'Projecten',
      programs: "Programma's",
      team: 'Team',
      settings: 'Instellingen',
      academy: {
        title: 'Academy',
        comingSoon: 'Binnenkort',
        new: 'Nieuw',
        marketplace: 'Training Marketplace',
        marketplaceDesc: '100+ cursussen & certificaten',
        methodologies: 'Management Methodieken',
        methodologiesDesc: 'Scrum, Kanban, PRINCE2, SAFe & meer',
        pricing: 'Academy Prijzen',
        pricingDesc: 'Abonnementen & certificeringen',
        requestQuote: 'Offerte Aanvragen',
        requestQuoteDesc: 'Voor teams & bedrijven',
      }
    },
    hero: {
      badge: 'Next-Gen Projectmanagement',
      title1: 'Beheers Je Projecten',
      title2: 'met AI-Powered Intelligentie',
      subtitle: 'Het alles-in-één platform voor programma- en projectmanagement. Aangedreven door AI, gebouwd voor teams die meer willen bereiken.',
      programManagement: 'Programmamanagement',
      projectTracking: 'Projecttracking',
      aiInsights: 'AI Inzichten',
      timeManagement: 'Tijdregistratie',
      getStarted: 'Gratis Starten',
      watchDemo: 'Bekijk Demo',
      aiGreeting: 'Hoi! Ik ben je AI projectassistent. Ik kan je helpen met:',
      aiCapabilities: [
        'Projectplannen & tijdlijnen maken',
        'Risicoanalyse & mitigatie',
        'Statusrapporten & dashboards',
        'Team capaciteitsplanning',
      ],
      askPlaceholder: 'Vraag me alles over je projecten...',
      stats: {
        projects: 'Projecten Beheerd',
        programs: "Actieve Programma's",
        hours: 'Uren Geregistreerd',
        success: 'Succesratio',
      },
      aiPowered: 'AI-Powered',
      sales: 'Sales',
      online: 'Online',
      welcome: '👋 Welkom bij ProjeXtPal! Ik help je graag met:',
      capabilities: [
        'Uitleg over onze AI-functies',
        'Prijzen en abonnementen',
        'Een demo inplannen',
        'Technische vragen'
      ],
      poweredBy: 'Powered by AI • Gemiddelde responstijd: 2 sec',
      quickPrompts: [
        'Wat kan ProjeXtPal voor mij doen?',
        'Hoe verbetert AI mijn projecten?',
        'Is er een gratis proefversie?',
        'Wat kost ProjeXtPal?'
      ],
      chatPlaceholder: '💬 Stel je vraag over ProjeXtPal...',
      safePrivate: 'Veilig & privé',
      instantResponse: 'Direct antwoord',
    },
    about: {
      badge: 'Waarom ProjeXtPal',
      title1: 'Alles Wat Je Nodig Hebt',
      title2: 'In Één Platform',
      description: 'ProjeXtPal combineert krachtig projectmanagement met intelligente AI-assistentie. Of je nu één project beheert of een complete portfolio, wij hebben je gedekt.',
      capabilities: [
        'Multi-methodologie ondersteuning (Agile, Scrum, PRINCE2, SAFe)',
        'Real-time samenwerking & communicatie',
        'Geautomatiseerde rapportage & inzichten',
        'Geïntegreerde tijdregistratie',
        'AI-powered aanbevelingen',
      ],
      getStarted: 'Aan de Slag',
      programs: "Programma's",
      programsDesc: "Beheer portfolio's en complexe programma's met gemak.",
      projects: 'Projecten',
      projectsDesc: 'Volg taken, tijdlijnen en deliverables efficiënt.',
      aiPowered: 'AI-Powered',
      aiPoweredDesc: 'Krijg intelligente inzichten en aanbevelingen aangedreven door geavanceerde AI.',
      smartEntry: 'Slimme Data Invoer',
      aiReports: 'AI Rapporten',
      methodologyAdvisor: 'Methodologie Adviseur',
      pillars: [
        { title: 'Projecten', desc: 'Projectmanagement met AI' },
        { title: "Programma's", desc: "Portfolio & programma's" },
        { title: 'Trainingen', desc: '118+ leermodules' },
        { title: 'AI', desc: 'Intelligente assistentie' }
      ]
    },
    features: {
      badge: 'Krachtige Functies',
      title1: 'Tools Die',
      title2: 'Je Team Versterken',
      items: [
        { title: 'Programmamanagement', desc: 'Overzicht over meerdere projecten met portfolio dashboards en strategische afstemming.' },
        { title: 'Projecttracking', desc: 'Gantt charts, Kanban borden en milestone tracking allemaal op één plek.' },
        { title: 'AI Assistent', desc: 'Krijg directe antwoorden, genereer rapporten en ontvang slimme aanbevelingen.' },
        { title: 'Tijdregistratie', desc: 'Log uren, volg productiviteit en beheer teamcapaciteit moeiteloos.' },
        { title: 'Team Samenwerking', desc: 'Real-time updates, comments en notificaties houden iedereen op de hoogte.' },
        { title: 'Slimme Automatisering', desc: 'Automatiseer repetitieve taken en focus op wat er echt toe doet.' },
        { title: 'Analytics & Rapporten', desc: 'Mooie dashboards en exporteerbare rapporten binnen handbereik.' },
        { title: 'Risicomanagement', desc: "Identificeer, beoordeel en mitigeer risico's voordat ze problemen worden." },
        { title: 'Resource Planning', desc: 'Optimaliseer teamallocatie en voorkom burnout met slimme planning.' },
      ],
      startUsing: 'Start Met ProjeXtPal',
    },
    demo: {
      badge: 'Zie Het In Actie',
      title1: 'Ervaar',
      title2: 'De Kracht van ProjeXtPal',
      aiOnline: 'AI Online',
      aiInsight: 'AI Inzicht',
      aiInsightText: 'Project "Digitale Transformatie" loopt 15% voor op schema. Overweeg resources te verplaatsen naar het vertraagde "CRM Integratie" project.',
      tryIt: 'Probeer Het Zelf',
    },
    app: {
      totalPrograms: "Totaal Programma's",
      totalProjects: 'Totaal Projecten',
      dashboardTitle: 'Portfolio Dashboard',
      dashboardSubtitle: 'Je complete project & programma overzicht',
      aiSummary: 'AI Samenvatting',
      programsStatus: 'Programma Status',
      projectsStatus: 'Project Status',
      active: 'Actief',
      inProgress: 'In Uitvoering',
      atRisk: 'Risico',
      budget: 'Budget',
      totalBudget: 'Totaal Budget',
      avgProgress: 'Gem. Voortgang',
      newProgram: 'Nieuw Programma',
      newProject: 'Nieuw Project',
      viewAll: 'Bekijk Alle',
      name: 'Naam',
      methodology: 'Methodologie',
      progress: 'Voortgang',
      status: 'Status',
      health: 'Gezondheid',
      dueDate: 'Deadline',
      planning: 'Planning',
      pending: 'In Afwachting',
      quickActions: 'Snelle Acties',
      aiAssistant: 'AI Assistent',
      programsOverview: 'Programma Overzicht',
      projectsOverview: 'Project Overzicht',
      completed: 'Voltooid',
      framework: 'Framework',
      programName: 'Programma Naam',
      projects: 'Projecten',
      requiresAttention: 'Vereist Aandacht',
      total: 'Totaal',
      totalAllocated: 'Totaal Toegewezen',
      activePrograms: 'Actieve Programma\'s',
      activeProjects: 'Actieve Projecten',
      onHold: 'In de Wacht',
    },
    timeTracking: {
      title: 'Tijdregistratie',
      subtitle: 'Registreer je tijd per project en taak',
      aiInsights: 'AI Inzichten',
      smartEntry: 'Slimme Invoer',
      aiReport: 'AI Rapport',
      newTimeEntry: 'Nieuwe Tijdregistratie',
      today: 'Vandaag',
      thisWeek: 'Deze Week',
      activeTimer: 'Actieve Timer',
      project: 'Project',
      task: 'Taak',
      startTimer: 'Start Timer',
      stopSave: 'Stop & Opslaan',
      timeReports: 'Tijdrapporten',
      weekly: 'Wekelijks',
      monthly: 'Maandelijks',
      dailyHours: 'Dagelijkse Uren',
      weeklyHours: 'Wekelijkse Uren',
      projectDistribution: 'Project Verdeling',
      totalHours: 'Totaal Uren',
      totalEntries: 'Totaal Registraties',
      projects: 'Projecten',
      dailyAverage: 'Dagelijks Gemiddelde',
      recentEntries: 'Recente Tijdregistraties',
      filters: 'Filters',
      clearFilters: 'Wis Filters',
      allProjects: 'Alle projecten',
      allMembers: 'Alle leden',
      teamMember: 'Teamlid',
      startDate: 'Startdatum',
      endDate: 'Einddatum',
      showing: 'Tonen',
      of: 'van',
      entries: 'registraties',
      noEntries: 'Geen tijdregistraties gevonden',
      clearAllFilters: 'Wis alle filters',
      logTimeEntry: 'Tijd Registreren',
      selectProject: 'Selecteer project',
      selectTask: 'Selecteer taak',
      date: 'Datum',
      hours: 'Uren',
      minutes: 'Minuten',
      description: 'Omschrijving (optioneel)',
      saveTimeEntry: 'Registratie Opslaan',
      aiProductivityInsights: 'AI Productiviteit Inzichten',
      aiInsightsDesc: 'AI-analyse van je tijdregistratie patronen.',
      analyzeMyTime: 'Analyseer Mijn Tijd',
      analyzingPatterns: 'Je productiviteitspatronen analyseren...',
      refreshAnalysis: 'Ververs Analyse',
      close: 'Sluiten',
      aiSmartEntry: 'AI Slimme Tijdregistratie',
      aiSmartEntryDesc: 'Beschrijf je werk en AI maakt de registratie.',
      generateEntry: 'Genereer Registratie',
      processing: 'Verwerken...',
      addEntry: 'Voeg Toe',
      tryAgain: 'Probeer Opnieuw',
      aiSuggestion: 'AI Suggestie',
      duration: 'Duur',
      aiWeeklyReport: 'AI Weekrapport',
      aiReportDesc: 'Genereer een professioneel tijdrapport.',
      generateReport: 'Genereer Rapport',
      generatingReport: 'Je rapport genereren...',
      copyReport: 'Kopieer Rapport',
      regenerate: 'Regenereer',
    },
    programs: {
      title: 'Programma\'s',
      subtitle: 'Beheer je programma portfolio',
      totalPrograms: 'Totaal Programma\'s',
      totalProjects: 'Totaal Projecten',
      newProgram: 'Nieuw Programma',
      createProgram: 'Programma Maken',
      createNewProgram: 'Nieuw Programma Maken',
      editProgram: 'Programma Bewerken',
      deleteProgram: 'Programma Verwijderen',
      programDetails: 'Programma Details',
      programName: 'Programma Naam',
      programNameRequired: 'Programma naam is verplicht',
      description: 'Omschrijving',
      strategicObjective: 'Strategisch Doel',
      departments: 'Afdelingen',
      departmentsPlaceholder: 'Voer afdelingen in',
      budget: 'Budget',
      budgetPlaceholder: 'Voer budget in',
      totalBudget: 'Totaal Budget',
      spent: 'Uitgegeven',
      duration: 'Duur',
      durationPlaceholder: 'Duur in maanden',
      months: 'maanden',
      startDate: 'Startdatum',
      planning: 'Planning',
      active: 'Actief',
      completed: 'Voltooid',
      atRisk: 'Risico',
      health: 'Gezondheid',
      projects: 'Projecten',
      unassigned: 'Niet toegewezen',
      allStatus: 'Alle Status',
      allMethods: 'Alle Methodologieën',
      searchPlaceholder: 'Zoek programma\'s...',
      noPrograms: 'Geen programma\'s gevonden',
      view: 'Bekijken',
      edit: 'Bewerken',
      delete: 'Verwijderen',
      cancel: 'Annuleren',
      saveChanges: 'Wijzigingen Opslaan',
      saving: 'Opslaan...',
      updateDetails: 'Details Bijwerken',
      deleteConfirm: 'Weet je zeker dat je dit programma wilt verwijderen?',
      createDescription: 'Maak een nieuw programma om meerdere gerelateerde projecten te beheren',
      manual: 'Handmatige Invoer',
      aiAssistant: 'AI Assistent',
      aiAssistantDesc: 'Laat AI je helpen bij het opzetten van je programma',
      describeProgram: 'Beschrijf Je Programma',
      describeProgramHint: 'Vertel ons over je programma doelen en scope',
      ideaPlaceholder: 'Bijv., Digitale transformatie initiatief voor modernisering van onze klantenservice platforms...',
      ideaTip: 'Hoe meer details je geeft, hoe beter AI kan helpen',
      analyzeRecommend: 'Analyseren & Aanbevelen',
      analyzing: 'Je programma analyseren...',
      recommendedMethodology: 'Aanbevolen Methodologie',
      match: 'Match',
      orChooseAnother: 'Of kies een andere methodologie',
      recommendationHint: 'Gebaseerd op je programma beschrijving',
      reviewProgram: 'Programma Details Bekijken',
      reviewDetails: 'Bekijk de gegenereerde details en maak aanpassingen',
      reviewHint: 'Je kunt elk veld bewerken voordat je aanmaakt',
      back: 'Terug',
      creatingProgram: 'Programma aanmaken...',
      settingUp: 'Je programma opzetten...',
      generateWithAI: 'Genereren met AI',
      review: 'Beoordelen',
      methodologies: {
        safe: 'SAFe',
        safeDesc: 'Scaled Agile Framework voor bedrijfsbrede agile transformatie',
        msp: 'MSP',
        mspDesc: 'Managing Successful Programmes - governance-gerichte aanpak',
        pmi: 'PMI Program Management',
        pmiDesc: 'PMI standaard voor programma management met voordelen realisatie focus',
        prince2: 'PRINCE2 Programme',
        prince2Desc: 'PRINCE2 methodologie aangepast voor programma management',
        hybrid: 'Hybride',
        hybridDesc: 'Flexibele combinatie van methodologieën',
      },
    },
    pricing: {
      badge: 'Eenvoudige Prijzen',
      title1: 'Kies Het Plan',
      title2: 'Dat Bij Je Past',
      popular: 'Meest Populair',
      monthly: '/maand',
      getStarted: 'Aan de Slag',
      contactUs: 'Neem Contact Op',
      plans: [
        {
          name: 'Basic',
          desc: 'Perfect voor kleine teams die beginnen.',
          price: '€25',
          features: ['Tot 5 gebruikers', 'Tot 10 projecten', '5 GB opslag', 'Basis AI assistentie', 'Email support'],
          academy: 'optional',
        },
        {
          name: 'Professional',
          desc: 'Voor groeiende teams die meer power nodig hebben.',
          price: '€75',
          features: ['Tot 25 gebruikers', 'Tot 50 projecten', '25 GB opslag', 'Geavanceerde AI functies', 'Prioriteit support', 'Custom rapporten'],
          academy: 'optional',
        },
        {
          name: 'Enterprise',
          desc: 'Voor grote organisaties met complexe behoeften.',
          price: '€200',
          features: ['Onbeperkt gebruikers', 'Onbeperkt projecten', 'Onbeperkt opslag', 'SSO & geavanceerde beveiliging', 'Dedicated manager', 'Custom integraties', '✓ Learning Academy inbegrepen'],
          academy: 'included',
        },
        {
          name: 'Custom+',
          desc: 'Oplossing op maat voor uw organisatie.',
          price: 'Offerte',
          features: ['Alles in Enterprise', 'On-premise deployment', 'Custom SLA', 'Dedicated infrastructuur', 'White-label opties', '24/7 support'],
          academy: 'optional',
        },
      ],
    },
    contact: {
      badge: 'Neem Contact Op',
      title: 'Laten We Praten',
      letsTalk: 'We Horen Graag Van Je',
      description: 'Vragen over ProjeXtPal? Wil je een demo inplannen? Ons team staat voor je klaar.',
      name: 'Je Naam',
      email: 'Je Email',
      message: 'Je Bericht',
      send: 'Verstuur Bericht',
    },
    faq: {
      title: 'Veelgestelde Vragen',
      items: [
        { q: 'Welke methodologieën ondersteunt ProjeXtPal?', a: 'ProjeXtPal ondersteunt Agile, Scrum, Kanban, PRINCE2, SAFe, Lean Six Sigma en traditionele Waterfall methodologieën.' },
        { q: 'Is er een gratis proefperiode?', a: 'Ja! Ons Basic plan bevat kernfuncties om te starten. Geen creditcard nodig.' },
        { q: 'Kan ik data importeren uit andere tools?', a: 'Absoluut. We ondersteunen imports vanuit Jira, Asana, Monday, Trello, MS Project en Excel.' },
        { q: 'Hoe werkt de AI assistent?', a: 'Onze AI is getraind op projectmanagement best practices en je projectdata om contextuele aanbevelingen te geven en routinetaken te automatiseren.' },
      ],
    },
    footer: {
      description: 'AI-powered projectmanagement voor moderne teams.',
      product: 'Product',
      company: 'Bedrijf',
      legal: 'Juridisch',
      rights: 'Alle rechten voorbehouden.',
      cta: {
        title1: 'Klaar Om Je',
        title2: 'Projectmanagement Te Transformeren?',
      },
      demo: 'Demo',
      privacy: 'Privacy',
      terms: 'Voorwaarden',
      academy: {
        courses: 'Cursussen',
        methodologies: 'Methodieken',
        pricing: 'Prijzen',
      }
    },
    common: {
      save: 'Opslaan',
      cancel: 'Annuleren',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      add: 'Toevoegen',
      search: 'Zoeken',
      loading: 'Laden...',
      confirm: 'Bevestigen',
      back: 'Terug',
      next: 'Volgende',
      close: 'Sluiten',
      success: 'Succes',
      error: 'Fout',
      retry: 'Opnieuw',
      projectDeleted: 'Project succesvol verwijderd',
      projectCreated: 'Project succesvol aangemaakt!',
      projectUpdated: 'Project succesvol bijgewerkt',
      programDeleted: 'Programma succesvol verwijderd',
      programCreated: 'Programma succesvol aangemaakt!',
      programUpdated: 'Programma succesvol bijgewerkt',
      deleteFailed: 'Verwijderen mislukt',
      saveFailed: 'Opslaan mislukt',
      createFailed: 'Aanmaken mislukt',
      updateFailed: 'Bijwerken mislukt',
      describeFirst: 'Beschrijf eerst je idee',
      nameRequired: 'Naam is verplicht',
      aiUnavailable: 'AI tijdelijk niet beschikbaar. Probeer het handmatig.',
      aiAnalysisFailed: 'AI-analyse mislukt. Probeer het opnieuw.',
      detailsGenerated: 'Details gegenereerd! Bekijk en pas aan waar nodig.',
      descriptionGenerated: 'Beschrijving gegenereerd!',
      objectiveGenerated: 'Strategisch doel gegenereerd!',
      generateFailed: 'Kon inhoud niet genereren',
      teamMemberAdded: 'Teamlid toegevoegd',
      teamMemberRemoved: 'Teamlid verwijderd',
      addFailed: 'Toevoegen mislukt',
      removeFailed: 'Verwijderen mislukt',
      titleAmountRequired: 'Titel en bedrag zijn verplicht',
      expenseDeleted: 'Uitgave verwijderd',
      passwordMinLength: 'Wachtwoord moet minimaal 8 tekens zijn',
      passwordsMismatch: 'Wachtwoorden komen niet overeen',
      passwordReset: 'Wachtwoord gereset! Je kunt nu inloggen.',
    },
    sidebar: {
      dashboard: "Dashboard",
      aiAssistant: "AI Chat",
      programs: "Programma's",
      allProjects: "Projecten",
      timeTracking: "Tijdregistratie",
      team: "Team",
      surveys: "Enquêtes",
      postProject: "Post Project",
      adminPortal: "Admin Portaal",
      governance: "Governance",
      portfolios: "Portfolio's",
      boards: "Besturen",
      stakeholders: "Stakeholders",
      reports: "Rapportages",
      profile: "Profiel",
      settings: "Instellingen",
      academy: "Academy",
      content: "Inhoud",
      notes: "Notities",
      resources: "Bronnen",
      questions: "Vragen",
      skills: "Vaardigheden",
      simulation: "Simulatie",
      practice: "Praktijk",
      exam: "Examen",
      certificate: "Certificaat",
      quiz: "Quiz",
      upgradeRequired: "Upgrade Vereist",
      upgradeDescription: "is beschikbaar met een betaald abonnement.",
      viewPlans: "Bekijk Plannen",
      currentPlan: "Huidig Abonnement",
      managePlan: "Abonnement Beheren",
    },
    methodologyTerms: {
      // Common
      "Dashboard": "Dashboard",
      "Overview": "Overzicht",
      "Team": "Team",
      "Budget": "Budget",
      "Governance": "Governance",
      "Risks": "Risico\'s",
      "Resources": "Middelen",
      "Roadmap": "Routekaart",
      "Milestones": "Mijlpalen",
      "Benefits": "Baten",
      "Stakeholders": "Stakeholders",
      "Communications": "Communicatie",
      "Projects": "Projecten",
      "Reports": "Rapportages",
      "Management": "Management",
      "Execution": "Uitvoering",
      "Planning": "Planning",
      "Schedule": "Planning",
      "Charter": "Charter",
      // PRINCE2
      "Project Initiation": "Projectinitiatie",
      "Stage Management": "Fasebeheer",
      "Project Closure": "Projectafsluiting",
      "Business Case": "Business Case",
      "Project Brief": "Projectvoorstel",
      "Stage Plan": "Faseplan",
      "Work Packages": "Werkpakketten",
      "Stage Gates": "Fasepoorten",
      "Tolerances": "Toleranties",
      "Project Board": "Projectbestuur",
      "Highlight Reports": "Voortgangsrapporten",
      "Issues & Risks": "Problemen & Risico\'s",
      "Change Control": "Wijzigingsbeheer",
      "Closure Checklist": "Afsluitchecklist",
      "End Project Report": "Eindrapport",
      "Lessons Log": "Geleerde Lessen",
      "Benefits Review": "Batenbeoordeling",
      "Exception Reports": "Uitzonderingsrapporten",
      // Scrum
      "Scrum Setup": "Scrum Inrichting",
      "Definition of Done": "Definition of Done",
      "Product Backlog": "Product Backlog",
      "Backlog": "Backlog",
      "Sprint Management": "Sprint Beheer",
      "Sprint Board": "Sprint Bord",
      "Velocity": "Velocity",
      "Increments": "Incrementen",
      "Scrum Events": "Scrum Gebeurtenissen",
      "Daily Standup": "Dagelijkse Stand-up",
      "Retrospective": "Retrospectief",
      "Sprint Planning": "Sprint Planning",
      "Sprint Review": "Sprint Review",
      // Kanban
      "Kanban Setup": "Kanban Inrichting",
      "Board Configuration": "Bord Configuratie",
      "WIP Limits": "WIP Limieten",
      "Work Policies": "Werkafspraken",
      "Kanban Board": "Kanban Bord",
      "Work Items": "Werkitems",
      "Board View": "Bordweergave",
      "Blocked Items": "Geblokkeerde Items",
      "Flow Metrics": "Flow Metrieken",
      "Metrics Dashboard": "Metrieken Dashboard",
      "Cumulative Flow": "Cumulatieve Flow",
      "Continuous Improvement": "Continue Verbetering",
      "Kaizen": "Kaizen",
      // Agile
      "Foundation": "Basis",
      "Discovery": "Ontdekking",
      "Product Vision": "Productvisie",
      "User Personas": "Gebruikersprofielen",
      "Release Planning": "Release Planning",
      "Iteration Board": "Iteratie Bord",
      "Daily Progress": "Dagelijkse Voortgang",
      "Review": "Review",
      // Waterfall
      "Requirements": "Vereisten",
      "Gantt Chart": "Gantt Diagram",
      "Phases": "Fasen",
      "Design": "Ontwerp",
      "Development": "Ontwikkeling",
      "Testing": "Testen",
      "Deployment": "Implementatie",
      "Maintenance": "Onderhoud",
      "Control": "Beheersing",
      "Change Requests": "Wijzigingsverzoeken",
      "Phase Gates": "Fasepoorten",
      "Baselines": "Baselines",
      "Issues": "Problemen",
      "Deliverables": "Opleverpunten",
      // Lean Six Sigma
      "Define": "Definieer",
      "Measure": "Meet",
      "Analyze": "Analyseer",
      "Improve": "Verbeter",
      "Project Charter": "Projectcharter",
      "SIPOC": "SIPOC",
      "Voice of Customer": "Klantbehoeften",
      "Data Collection": "Dataverzameling",
      "Process Map": "Proceskaart",
      "Baseline Metrics": "Basislijnmetrieken",
      "MSA Report": "MSA Rapport",
      "Root Cause Analysis": "Oorzaakanalyse",
      "Fishbone Diagram": "Visgraatdiagram",
      "Pareto Chart": "Pareto Diagram",
      "Hypothesis Tests": "Hypothesetests",
      "Regression Analysis": "Regressieanalyse",
      "Solution Design": "Oplossingsontwerp",
      "FMEA": "FMEA",
      "Pilot Plan": "Pilotplan",
      "Implementation": "Implementatie",
      "Control Plan": "Beheersplan",
      "SPC Charts": "SPC Grafieken",
      "Monitoring": "Monitoring",
      "Tollgate Review": "Tollgate Review",
      "Closure": "Afsluiting",
      // SAFe
      "Program Overview": "Programma Overzicht",
      "ART Overview": "ART Overzicht",
      "Program Increments": "Programma Incrementen",
      "Current PI": "Huidig PI",
      "PI Planning": "PI Planning",
      "PI Objectives": "PI Doelstellingen",
      "Features": "Features",
      "System Demo": "Systeem Demo",
      "Inspect & Adapt": "Inspecteer & Pas aan",
      // MSP
      "Programme Overview": "Programma Overzicht",
      "Blueprint": "Blauwdruk",
      "Benefits Management": "Batenbeheer",
      "Benefits Map": "Batenkaart",
      "Benefits Profiles": "Batenprofielen",
      "Realization Plan": "Realisatieplan",
      "Tranches": "Tranches",
      "Tranche Plan": "Trancheplan",
      "Transitions": "Transities",
      "Stakeholder Engagement": "Stakeholderbetrokkenheid",
      "Stakeholder Map": "Stakeholderkaart",
      "Programme Board": "Programmabestuur",
      "Risks & Issues": "Risico\'s & Problemen",
      // PMI
      "Program Lifecycle": "Programma Levenscyclus",
      "Benefits Realization": "Batenrealisatie",
      "Benefits Register": "Batenregister",
      "KPIs": "KPI\'s",
      "Program Management": "Programmabeheer",
      // PRINCE2 Programme
      "Tranche Management": "Tranchebeheer",
      // Hybrid
      "Project Foundation": "Projectbasis",
      "Workflow": "Werkstroom",
      "Planning & Design": "Planning & Ontwerp",
      "Timeline": "Tijdlijn",
      "Tasks": "Taken",
      "RACI": "RACI",
      "Dependencies": "Afhankelijkheden",
      "Calendar": "Kalender",
      "Workflow Diagram": "Werkstroomdiagram",
      "System Integration": "Systeemintegratie",
      "Execution & Governance": "Uitvoering & Governance",
      "Communication": "Communicatie",
      "Newsletters": "Nieuwsbrieven",
      "Status Reporting": "Statusrapportage",
      "Meeting": "Vergadering",
      "Reporting": "Rapportage",
      "Deployment Strategy": "Implementatiestrategie",
      "Monitoring & Closure": "Monitoring & Afsluiting",
      "Document Library": "Documentbibliotheek",
      "All Documents": "Alle Documenten",
      "Stages": "Fasen",
      "Training": "Training",
      "Lessons Learned & Surveys": "Geleerde Lessen & Enquêtes",
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      features: 'Fonctionnalités',
      pricing: 'Tarifs',
      contact: 'Contact',
      login: 'Connexion',
      logout: 'Déconnexion',
      openApp: 'Ouvrir l\'App',
      website: 'Site Web',
      dashboard: 'Tableau de Bord',
      projects: 'Projets',
      programs: 'Programmes',
      team: 'Équipe',
      settings: 'Paramètres',
      academy: {
        title: 'Académie',
        comingSoon: 'Bientôt Disponible',
        new: 'Nouveau',
        marketplace: 'Marketplace de Formation',
        marketplaceDesc: '100+ cours & certificats',
        methodologies: 'Méthodologies de Management',
        methodologiesDesc: 'Scrum, Kanban, PRINCE2, SAFe & plus',
        pricing: 'Tarifs Académie',
        pricingDesc: 'Abonnements & certifications',
        requestQuote: 'Demander un Devis',
        requestQuoteDesc: 'Pour équipes & entreprises',
      }
    },
    hero: {
      badge: 'Gestion de Projet Nouvelle Génération',
      title1: 'Maîtrisez Vos Projets',
      title2: 'avec l\'Intelligence Artificielle',
      subtitle: 'La plateforme tout-en-un pour la gestion de programmes et de projets. Propulsée par l\'IA, conçue pour les équipes qui veulent accomplir plus.',
      programManagement: 'Gestion de Programme',
      projectTracking: 'Suivi de Projet',
      aiInsights: 'Analyses IA',
      timeManagement: 'Gestion du Temps',
      getStarted: 'Commencer Gratuitement',
      watchDemo: 'Voir la Démo',
      aiGreeting: 'Bonjour ! Je suis votre assistant IA de projet. Je peux vous aider avec :',
      aiCapabilities: [
        'Création de plans de projet & calendriers',
        'Analyse des risques & atténuation',
        'Rapports de statut & tableaux de bord',
        'Planification de la capacité de l\'équipe',
      ],
      askPlaceholder: 'Posez-moi des questions sur vos projets...',
      stats: {
        projects: 'Projets Gérés',
        programs: 'Programmes Actifs',
        hours: 'Heures Suivies',
        success: 'Taux de Réussite',
      },
      aiPowered: 'Propulsé par l\'IA',
      sales: 'Ventes',
      online: 'En Ligne',
      welcome: '👋 Bienvenue sur ProjeXtPal ! Je suis ravi de vous aider avec :',
      capabilities: [
        'Explication de nos fonctionnalités IA',
        'Tarifs et abonnements',
        'Planifier une démo',
        'Questions techniques'
      ],
      poweredBy: 'Propulsé par l\'IA • Temps de réponse moyen : 2 sec',
      quickPrompts: [
        'Que peut faire ProjeXtPal pour moi ?',
        'Comment l\'IA améliore-t-elle mes projets ?',
        'Y a-t-il un essai gratuit ?',
        'Combien coûte ProjeXtPal ?'
      ],
      chatPlaceholder: '💬 Posez votre question sur ProjeXtPal...',
      safePrivate: 'Sûr & privé',
      instantResponse: 'Réponse instantanée',
    },
    about: {
      badge: 'Pourquoi ProjeXtPal',
      title1: 'Tout Ce Dont Vous Avez Besoin',
      title2: 'Sur Une Seule Plateforme',
      description: 'ProjeXtPal combine une gestion de projet puissante avec une assistance IA intelligente. Que vous gériez un seul projet ou un portfolio complet, nous avons ce qu\'il vous faut.',
      capabilities: [
        'Support multi-méthodologie (Agile, Scrum, PRINCE2, SAFe)',
        'Collaboration & communication en temps réel',
        'Rapports & analyses automatisés',
        'Suivi du temps intégré',
        'Recommandations propulsées par l\'IA',
      ],
      getStarted: 'Commencer',
      programs: 'Programmes',
      programsDesc: 'Gérez les portfolios et programmes complexes facilement.',
      projects: 'Projets',
      projectsDesc: 'Suivez les tâches, les calendriers et les livrables efficacement.',
      aiPowered: 'Propulsé par l\'IA',
      aiPoweredDesc: 'Obtenez des analyses et recommandations intelligentes propulsées par une IA avancée.',
      smartEntry: 'Saisie Intelligente',
      aiReports: 'Rapports IA',
      methodologyAdvisor: 'Conseiller en Méthodologie',
      pillars: [
        { title: 'Projets', desc: 'Gestion de projet propulsée par l\'IA' },
        { title: 'Programmes', desc: 'Portfolio & programmes' },
        { title: 'Formations', desc: '118+ modules d\'apprentissage' },
        { title: 'IA', desc: 'Assistance intelligente' }
      ]
    },
    features: {
      badge: 'Fonctionnalités Puissantes',
      title1: 'Des Outils Qui',
      title2: 'Renforcent Votre Équipe',
      items: [
        { title: 'Gestion de Programme', desc: 'Supervisez plusieurs projets avec des tableaux de bord de portfolio et un alignement stratégique.' },
        { title: 'Suivi de Projet', desc: 'Diagrammes de Gantt, tableaux Kanban et suivi des jalons, tout en un seul endroit.' },
        { title: 'Assistant IA', desc: 'Obtenez des réponses instantanées, générez des rapports et recevez des recommandations intelligentes.' },
        { title: 'Suivi du Temps', desc: 'Enregistrez les heures, suivez la productivité et gérez la capacité de l\'équipe sans effort.' },
        { title: 'Collaboration d\'Équipe', desc: 'Mises à jour en temps réel, commentaires et notifications pour garder tout le monde aligné.' },
        { title: 'Automatisation Intelligente', desc: 'Automatisez les tâches répétitives et concentrez-vous sur l\'essentiel.' },
        { title: 'Analyses & Rapports', desc: 'De beaux tableaux de bord et des rapports exportables à portée de main.' },
        { title: 'Gestion des Risques', desc: 'Identifiez, évaluez et atténuez les risques avant qu\'ils ne deviennent des problèmes.' },
        { title: 'Planification des Ressources', desc: 'Optimisez l\'allocation des équipes et prévenez l\'épuisement avec une planification intelligente.' },
      ],
      startUsing: 'Commencer avec ProjeXtPal',
    },
    demo: {
      badge: 'Voir en Action',
      title1: 'Découvrez',
      title2: 'La Puissance de ProjeXtPal',
      aiOnline: 'IA En Ligne',
      aiInsight: 'Analyse IA',
      aiInsightText: 'Le projet "Transformation Digitale" est en avance de 15%. Envisagez de réaffecter des ressources au projet "Intégration CRM" en retard.',
      tryIt: 'Essayez-le Vous-même',
    },
    app: {
      totalPrograms: 'Total Programmes',
      totalProjects: 'Total Projets',
      dashboardTitle: 'Tableau de Bord Portfolio',
      dashboardSubtitle: 'Votre aperçu complet des projets & programmes',
      aiSummary: 'Résumé IA',
      programsStatus: 'Statut des Programmes',
      projectsStatus: 'Statut des Projets',
      active: 'Actif',
      inProgress: 'En Cours',
      atRisk: 'À Risque',
      budget: 'Budget',
      totalBudget: 'Budget Total',
      avgProgress: 'Progression Moy.',
      newProgram: 'Nouveau Programme',
      newProject: 'Nouveau Projet',
      viewAll: 'Voir Tout',
      name: 'Nom',
      methodology: 'Méthodologie',
      progress: 'Progression',
      status: 'Statut',
      health: 'Santé',
      dueDate: 'Date d\'Échéance',
      planning: 'Planification',
      pending: 'En Attente',
      quickActions: 'Actions Rapides',
      aiAssistant: 'Assistant IA',
      programsOverview: 'Aperçu des Programmes',
      projectsOverview: 'Aperçu des Projets',
      completed: 'Terminé',
      framework: 'Framework',
      programName: 'Nom du Programme',
      projects: 'Projets',
      requiresAttention: 'Nécessite une Attention',
      total: 'Total',
      totalAllocated: 'Total Alloué',
      activePrograms: 'Programmes Actifs',
      activeProjects: 'Projets Actifs',
      onHold: 'En Pause',
    },
    timeTracking: {
      title: 'Suivi du Temps',
      subtitle: 'Suivez votre temps sur les projets et tâches',
      aiInsights: 'Analyses IA',
      smartEntry: 'Saisie Intelligente',
      aiReport: 'Rapport IA',
      newTimeEntry: 'Nouvelle Saisie de Temps',
      today: 'Aujourd\'hui',
      thisWeek: 'Cette Semaine',
      activeTimer: 'Minuteur Actif',
      project: 'Projet',
      task: 'Tâche',
      startTimer: 'Démarrer le Minuteur',
      stopSave: 'Arrêter & Enregistrer',
      timeReports: 'Rapports de Temps',
      weekly: 'Hebdomadaire',
      monthly: 'Mensuel',
      dailyHours: 'Heures Quotidiennes',
      weeklyHours: 'Heures Hebdomadaires',
      projectDistribution: 'Distribution par Projet',
      totalHours: 'Total Heures',
      totalEntries: 'Total Saisies',
      projects: 'Projets',
      dailyAverage: 'Moyenne Quotidienne',
      recentEntries: 'Saisies de Temps Récentes',
      filters: 'Filtres',
      clearFilters: 'Effacer les Filtres',
      allProjects: 'Tous les projets',
      allMembers: 'Tous les membres',
      teamMember: 'Membre de l\'Équipe',
      startDate: 'Date de Début',
      endDate: 'Date de Fin',
      showing: 'Affichage',
      of: 'de',
      entries: 'saisies',
      noEntries: 'Aucune saisie de temps ne correspond aux filtres actuels',
      clearAllFilters: 'Effacer tous les filtres',
      logTimeEntry: 'Enregistrer une Saisie de Temps',
      selectProject: 'Sélectionner un projet',
      selectTask: 'Sélectionner une tâche',
      date: 'Date',
      hours: 'Heures',
      minutes: 'Minutes',
      description: 'Description (optionnel)',
      saveTimeEntry: 'Enregistrer la Saisie',
      aiProductivityInsights: 'Analyses de Productivité IA',
      aiInsightsDesc: 'Analyse de vos habitudes de suivi du temps par l\'IA.',
      analyzeMyTime: 'Analyser Mon Temps',
      analyzingPatterns: 'Analyse de vos habitudes de productivité...',
      refreshAnalysis: 'Actualiser l\'Analyse',
      close: 'Fermer',
      aiSmartEntry: 'Saisie Intelligente IA',
      aiSmartEntryDesc: 'Décrivez votre travail et l\'IA créera la saisie de temps.',
      generateEntry: 'Générer la Saisie',
      processing: 'Traitement...',
      addEntry: 'Ajouter la Saisie',
      tryAgain: 'Réessayer',
      aiSuggestion: 'Suggestion IA',
      duration: 'Durée',
      aiWeeklyReport: 'Rapport Hebdomadaire IA',
      aiReportDesc: 'Générer un résumé professionnel de rapport de temps.',
      generateReport: 'Générer le Rapport',
      generatingReport: 'Génération de votre rapport...',
      copyReport: 'Copier le Rapport',
      regenerate: 'Régénérer',
    },
    programs: {
      title: 'Programmes',
      subtitle: 'Gérez votre portfolio de programmes',
      totalPrograms: 'Total Programmes',
      totalProjects: 'Total Projets',
      newProgram: 'Nouveau Programme',
      createProgram: 'Créer un Programme',
      createNewProgram: 'Créer un Nouveau Programme',
      editProgram: 'Modifier le Programme',
      deleteProgram: 'Supprimer le Programme',
      programDetails: 'Détails du Programme',
      programName: 'Nom du Programme',
      programNameRequired: 'Le nom du programme est obligatoire',
      description: 'Description',
      strategicObjective: 'Objectif Stratégique',
      departments: 'Départements',
      departmentsPlaceholder: 'Entrer les départements',
      budget: 'Budget',
      budgetPlaceholder: 'Entrer le budget',
      totalBudget: 'Budget Total',
      spent: 'Dépensé',
      duration: 'Durée',
      durationPlaceholder: 'Durée en mois',
      months: 'mois',
      startDate: 'Date de Début',
      planning: 'Planification',
      active: 'Actif',
      completed: 'Terminé',
      atRisk: 'À Risque',
      health: 'Santé',
      projects: 'Projets',
      unassigned: 'Non assigné',
      allStatus: 'Tous les Statuts',
      allMethods: 'Toutes les Méthodologies',
      searchPlaceholder: 'Rechercher des programmes...',
      noPrograms: 'Aucun programme trouvé',
      view: 'Voir',
      edit: 'Modifier',
      delete: 'Supprimer',
      cancel: 'Annuler',
      saveChanges: 'Enregistrer les Modifications',
      saving: 'Enregistrement...',
      updateDetails: 'Mettre à Jour les Détails',
      deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce programme ?',
      createDescription: 'Créer un nouveau programme pour gérer plusieurs projets liés',
      manual: 'Saisie Manuelle',
      aiAssistant: 'Assistant IA',
      aiAssistantDesc: 'Laissez l\'IA vous aider à configurer votre programme',
      describeProgram: 'Décrivez Votre Programme',
      describeProgramHint: 'Parlez-nous des objectifs et de la portée de votre programme',
      ideaPlaceholder: 'Ex., Initiative de transformation digitale pour moderniser nos plateformes de service client...',
      ideaTip: 'Plus vous fournissez de détails, mieux l\'IA peut vous aider',
      analyzeRecommend: 'Analyser & Recommander',
      analyzing: 'Analyse de votre programme...',
      recommendedMethodology: 'Méthodologie Recommandée',
      match: 'Correspondance',
      orChooseAnother: 'Ou choisir une autre méthodologie',
      recommendationHint: 'Basé sur la description de votre programme',
      reviewProgram: 'Examiner les Détails du Programme',
      reviewDetails: 'Examinez les détails générés et faites des ajustements',
      reviewHint: 'Vous pouvez modifier chaque champ avant la création',
      back: 'Retour',
      creatingProgram: 'Création du programme...',
      settingUp: 'Configuration de votre programme...',
      generateWithAI: 'Générer avec l\'IA',
      review: 'Examiner',
      methodologies: {
        safe: 'SAFe',
        safeDesc: 'Scaled Agile Framework pour la transformation agile à l\'échelle de l\'entreprise',
        msp: 'MSP',
        mspDesc: 'Managing Successful Programmes - approche axée sur la gouvernance',
        pmi: 'PMI Program Management',
        pmiDesc: 'Standard PMI pour la gestion de programme avec focus sur la réalisation des bénéfices',
        prince2: 'PRINCE2 Programme',
        prince2Desc: 'Méthodologie PRINCE2 adaptée à la gestion de programme',
        hybrid: 'Hybride',
        hybridDesc: 'Combinaison flexible de méthodologies',
      },
    },
    pricing: {
      badge: 'Tarifs Simples',
      title1: 'Choisissez Le Plan',
      title2: 'Qui Vous Convient',
      popular: 'Le Plus Populaire',
      monthly: '/mois',
      getStarted: 'Commencer',
      contactUs: 'Contactez-Nous',
      plans: [
        {
          name: 'Basic',
          desc: 'Parfait pour les petites équipes qui débutent.',
          price: '€25',
          features: ['Jusqu\'à 5 utilisateurs', 'Jusqu\'à 10 projets', '5 Go de stockage', 'Assistance IA basique', 'Support par email'],
          academy: 'optional',
        },
        {
          name: 'Professional',
          desc: 'Pour les équipes en croissance qui ont besoin de plus de puissance.',
          price: '€75',
          features: ['Jusqu\'à 25 utilisateurs', 'Jusqu\'à 50 projets', '25 Go de stockage', 'Fonctionnalités IA avancées', 'Support prioritaire', 'Rapports personnalisés'],
          academy: 'optional',
        },
        {
          name: 'Enterprise',
          desc: 'Pour les grandes organisations avec des besoins complexes.',
          price: '€200',
          features: ['Utilisateurs illimités', 'Projets illimités', 'Stockage illimité', 'SSO & sécurité avancée', 'Manager dédié', 'Intégrations personnalisées', '✓ Learning Academy incluse'],
          academy: 'included',
        },
        {
          name: 'Custom+',
          desc: 'Solution sur mesure pour votre organisation.',
          price: 'Devis',
          features: ['Tout dans Enterprise', 'Déploiement sur site', 'SLA personnalisé', 'Infrastructure dédiée', 'Options marque blanche', 'Support 24/7'],
          academy: 'optional',
        },
      ],
    },
    contact: {
      badge: 'Contactez-Nous',
      title: 'Parlons-en',
      letsTalk: 'Nous Serions Ravis de Vous Entendre',
      description: 'Des questions sur ProjeXtPal ? Vous souhaitez planifier une démo ? Notre équipe est là pour vous aider.',
      name: 'Votre Nom',
      email: 'Votre Email',
      message: 'Votre Message',
      send: 'Envoyer le Message',
    },
    faq: {
      title: 'Questions Fréquemment Posées',
      items: [
        { q: 'Quelles méthodologies ProjeXtPal supporte-t-il ?', a: 'ProjeXtPal supporte Agile, Scrum, Kanban, PRINCE2, SAFe, Lean Six Sigma et les méthodologies Waterfall traditionnelles.' },
        { q: 'Y a-t-il un essai gratuit ?', a: 'Oui ! Notre plan Basic inclut les fonctionnalités essentielles pour démarrer. Aucune carte de crédit requise.' },
        { q: 'Puis-je importer des données depuis d\'autres outils ?', a: 'Absolument. Nous supportons les imports depuis Jira, Asana, Monday, Trello, MS Project et Excel.' },
        { q: 'Comment fonctionne l\'assistant IA ?', a: 'Notre IA est formée aux meilleures pratiques de gestion de projet et à vos données de projet pour fournir des recommandations contextuelles et automatiser les tâches routinières.' },
      ],
    },
    footer: {
      description: 'Gestion de projet propulsée par l\'IA pour les équipes modernes.',
      product: 'Produit',
      company: 'Entreprise',
      legal: 'Mentions Légales',
      rights: 'Tous droits réservés.',
      cta: {
        title1: 'Prêt à Transformer',
        title2: 'Votre Gestion de Projet ?',
      },
      demo: 'Démo',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      academy: {
        courses: 'Cours',
        methodologies: 'Méthodologies',
        pricing: 'Tarifs',
      }
    },
    common: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      add: 'Ajouter',
      search: 'Rechercher',
      loading: 'Chargement...',
      confirm: 'Confirmer',
      back: 'Retour',
      next: 'Suivant',
      close: 'Fermer',
      success: 'Succès',
      error: 'Erreur',
      retry: 'Réessayer',
      projectDeleted: 'Projet supprimé avec succès',
      projectCreated: 'Projet créé avec succès !',
      projectUpdated: 'Projet mis à jour avec succès',
      programDeleted: 'Programme supprimé avec succès',
      programCreated: 'Programme créé avec succès !',
      programUpdated: 'Programme mis à jour avec succès',
      deleteFailed: 'Échec de la suppression',
      saveFailed: 'Échec de l\'enregistrement',
      createFailed: 'Échec de la création',
      updateFailed: 'Échec de la mise à jour',
      describeFirst: 'Veuillez d\'abord décrire votre idée',
      nameRequired: 'Le nom est obligatoire',
      aiUnavailable: 'IA temporairement indisponible. Veuillez essayer manuellement.',
      aiAnalysisFailed: 'L\'analyse IA a échoué. Veuillez réessayer.',
      detailsGenerated: 'Détails générés ! Examinez et ajustez si nécessaire.',
      descriptionGenerated: 'Description générée !',
      objectiveGenerated: 'Objectif stratégique généré !',
      generateFailed: 'Impossible de générer le contenu',
      teamMemberAdded: 'Membre de l\'équipe ajouté',
      teamMemberRemoved: 'Membre de l\'équipe supprimé',
      addFailed: 'Échec de l\'ajout',
      removeFailed: 'Échec de la suppression',
      titleAmountRequired: 'Le titre et le montant sont obligatoires',
      expenseDeleted: 'Dépense supprimée',
      passwordMinLength: 'Le mot de passe doit comporter au moins 8 caractères',
      passwordsMismatch: 'Les mots de passe ne correspondent pas',
      passwordReset: 'Mot de passe réinitialisé ! Vous pouvez maintenant vous connecter.',
    },
    sidebar: {
      dashboard: "Tableau de Bord",
      aiAssistant: "Chat IA",
      programs: "Programmes",
      allProjects: "Projets",
      timeTracking: "Suivi du Temps",
      team: "Équipe",
      surveys: "Enquêtes",
      postProject: "Post Projet",
      adminPortal: "Portail Admin",
      governance: "Gouvernance",
      portfolios: "Portfolios",
      boards: "Comités",
      stakeholders: "Parties Prenantes",
      reports: "Rapports",
      profile: "Profil",
      settings: "Paramètres",
      academy: "Académie",
      content: "Contenu",
      notes: "Notes",
      resources: "Ressources",
      questions: "Questions",
      skills: "Compétences",
      simulation: "Simulation",
      practice: "Pratique",
      exam: "Examen",
      certificate: "Certificat",
      quiz: "Quiz",
      upgradeRequired: "Mise à Niveau Requise",
      upgradeDescription: "est disponible avec un abonnement payant.",
      viewPlans: "Voir les Plans",
      currentPlan: "Plan Actuel",
      managePlan: "Gérer le Plan",
    },
    methodologyTerms: {
      // Common
      "Dashboard": "Tableau de Bord",
      "Overview": "Aperçu",
      "Team": "Équipe",
      "Budget": "Budget",
      "Governance": "Gouvernance",
      "Risks": "Risques",
      "Resources": "Ressources",
      "Roadmap": "Feuille de Route",
      "Milestones": "Jalons",
      "Benefits": "Bénéfices",
      "Stakeholders": "Parties Prenantes",
      "Communications": "Communications",
      "Projects": "Projets",
      "Reports": "Rapports",
      "Management": "Management",
      "Execution": "Exécution",
      "Planning": "Planification",
      "Schedule": "Calendrier",
      "Charter": "Charte",
      // PRINCE2
      "Project Initiation": "Initiation du Projet",
      "Stage Management": "Gestion des Étapes",
      "Project Closure": "Clôture du Projet",
      "Business Case": "Cas d'Affaires",
      "Project Brief": "Note de Cadrage",
      "Stage Plan": "Plan d'Étape",
      "Work Packages": "Lots de Travaux",
      "Stage Gates": "Portes d'Étape",
      "Tolerances": "Tolérances",
      "Project Board": "Comité de Projet",
      "Highlight Reports": "Rapports d'Avancement",
      "Issues & Risks": "Problèmes & Risques",
      "Change Control": "Contrôle des Changements",
      "Closure Checklist": "Liste de Contrôle de Clôture",
      "End Project Report": "Rapport de Fin de Projet",
      "Lessons Log": "Journal des Leçons",
      "Benefits Review": "Revue des Bénéfices",
      "Exception Reports": "Rapports d'Exception",
      // Scrum
      "Scrum Setup": "Configuration Scrum",
      "Definition of Done": "Définition de Terminé",
      "Product Backlog": "Backlog Produit",
      "Backlog": "Backlog",
      "Sprint Management": "Gestion des Sprints",
      "Sprint Board": "Tableau Sprint",
      "Velocity": "Vélocité",
      "Increments": "Incréments",
      "Scrum Events": "Événements Scrum",
      "Daily Standup": "Mêlée Quotidienne",
      "Retrospective": "Rétrospective",
      "Sprint Planning": "Planification de Sprint",
      "Sprint Review": "Revue de Sprint",
      // Kanban
      "Kanban Setup": "Configuration Kanban",
      "Board Configuration": "Configuration du Tableau",
      "WIP Limits": "Limites WIP",
      "Work Policies": "Politiques de Travail",
      "Kanban Board": "Tableau Kanban",
      "Work Items": "Éléments de Travail",
      "Board View": "Vue Tableau",
      "Blocked Items": "Éléments Bloqués",
      "Flow Metrics": "Métriques de Flux",
      "Metrics Dashboard": "Tableau de Bord des Métriques",
      "Cumulative Flow": "Flux Cumulatif",
      "Continuous Improvement": "Amélioration Continue",
      "Kaizen": "Kaizen",
      // Agile
      "Foundation": "Fondation",
      "Discovery": "Découverte",
      "Product Vision": "Vision Produit",
      "User Personas": "Personas Utilisateurs",
      "Release Planning": "Planification de Release",
      "Iteration Board": "Tableau d'Itération",
      "Daily Progress": "Progression Quotidienne",
      "Review": "Revue",
      // Waterfall
      "Requirements": "Exigences",
      "Gantt Chart": "Diagramme de Gantt",
      "Phases": "Phases",
      "Design": "Conception",
      "Development": "Développement",
      "Testing": "Tests",
      "Deployment": "Déploiement",
      "Maintenance": "Maintenance",
      "Control": "Contrôle",
      "Change Requests": "Demandes de Changement",
      "Phase Gates": "Portes de Phase",
      "Baselines": "Lignes de Base",
      "Issues": "Problèmes",
      "Deliverables": "Livrables",
      // Lean Six Sigma
      "Define": "Définir",
      "Measure": "Mesurer",
      "Analyze": "Analyser",
      "Improve": "Améliorer",
      "Project Charter": "Charte de Projet",
      "SIPOC": "SIPOC",
      "Voice of Customer": "Voix du Client",
      "Data Collection": "Collecte de Données",
      "Process Map": "Cartographie des Processus",
      "Baseline Metrics": "Métriques de Base",
      "MSA Report": "Rapport MSA",
      "Root Cause Analysis": "Analyse des Causes Racines",
      "Fishbone Diagram": "Diagramme d'Ishikawa",
      "Pareto Chart": "Diagramme de Pareto",
      "Hypothesis Tests": "Tests d'Hypothèses",
      "Regression Analysis": "Analyse de Régression",
      "Solution Design": "Conception de Solution",
      "FMEA": "AMDEC",
      "Pilot Plan": "Plan Pilote",
      "Implementation": "Mise en Œuvre",
      "Control Plan": "Plan de Contrôle",
      "SPC Charts": "Graphiques SPC",
      "Monitoring": "Surveillance",
      "Tollgate Review": "Revue de Jalon",
      "Closure": "Clôture",
      // SAFe
      "Program Overview": "Aperçu du Programme",
      "ART Overview": "Aperçu ART",
      "Program Increments": "Incréments de Programme",
      "Current PI": "PI Actuel",
      "PI Planning": "Planification PI",
      "PI Objectives": "Objectifs PI",
      "Features": "Fonctionnalités",
      "System Demo": "Démo Système",
      "Inspect & Adapt": "Inspecter & Adapter",
      // MSP
      "Programme Overview": "Aperçu du Programme",
      "Blueprint": "Plan Directeur",
      "Benefits Management": "Gestion des Bénéfices",
      "Benefits Map": "Carte des Bénéfices",
      "Benefits Profiles": "Profils des Bénéfices",
      "Realization Plan": "Plan de Réalisation",
      "Tranches": "Tranches",
      "Tranche Plan": "Plan de Tranche",
      "Transitions": "Transitions",
      "Stakeholder Engagement": "Engagement des Parties Prenantes",
      "Stakeholder Map": "Carte des Parties Prenantes",
      "Programme Board": "Comité de Programme",
      "Risks & Issues": "Risques & Problèmes",
      // PMI
      "Program Lifecycle": "Cycle de Vie du Programme",
      "Benefits Realization": "Réalisation des Bénéfices",
      "Benefits Register": "Registre des Bénéfices",
      "KPIs": "KPIs",
      "Program Management": "Gestion de Programme",
      // PRINCE2 Programme
      "Tranche Management": "Gestion des Tranches",
      // Hybrid
      "Project Foundation": "Fondation du Projet",
      "Workflow": "Flux de Travail",
      "Planning & Design": "Planification & Conception",
      "Timeline": "Chronologie",
      "Tasks": "Tâches",
      "RACI": "RACI",
      "Dependencies": "Dépendances",
      "Calendar": "Calendrier",
      "Workflow Diagram": "Diagramme de Flux",
      "System Integration": "Intégration Système",
      "Execution & Governance": "Exécution & Gouvernance",
      "Communication": "Communication",
      "Newsletters": "Bulletins d'Information",
      "Status Reporting": "Rapport de Statut",
      "Meeting": "Réunion",
      "Reporting": "Reporting",
      "Deployment Strategy": "Stratégie de Déploiement",
      "Monitoring & Closure": "Surveillance & Clôture",
      "Document Library": "Bibliothèque de Documents",
      "All Documents": "Tous les Documents",
      "Stages": "Étapes",
      "Training": "Formation",
      "Lessons Learned & Surveys": "Leçons Apprises & Enquêtes",
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'projextpal_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return (saved === 'en' || saved === 'nl' || saved === 'fr') ? saved : 'nl';
  });
  const t = translations[language];

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'en', setLanguage: () => {}, t: translations['en'] } as LanguageContextType;
  }
  return context;
}

export const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
] as const;