# Generated by Django 4.2.28 on 2026-03-01 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0009_project_portfolio_project_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseMethodology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phase", models.CharField(max_length=100)),
                ("methodology", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_phase_methodologies",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase Methodology",
                "verbose_name_plural": "Phase Methodologies",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HybridConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_methodology", models.CharField(max_length=50)),
                ("secondary_methodologies", models.JSONField(default=list)),
                ("approach_description", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_configs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hybrid Configuration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HybridArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("source_methodology", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hybrid_artifacts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hybrid Artifact",
                "ordering": ["-created_at"],
            },
        ),
    ]
