# Generated by Django 5.2.6 on 2026-06-04 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybrid', '0002_phasemethodology_dates_hybridtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phasemethodology',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='dod_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='entry_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='exit_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='gate_status',
            field=models.CharField(choices=[('open', 'Open'), ('signed_off', 'Signed Off'), ('complete', 'Complete')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phasemethodology',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hybrid_signed_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phasemethodology',
            name='methodology',
            field=models.CharField(default='waterfall', max_length=50),
        ),
    ]
