# Generated by Django 5.2.6 on 2026-06-04 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0002_fix_program_fk'),
        ('programs', '0006_alter_program_methodology_alter_programteam_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mspbenefit',
            name='baseline_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting measurement the benefit improves from.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mspbenefit',
            name='benefit_type',
            field=models.CharField(choices=[('financial', 'Financial'), ('non_financial', 'Non-Financial')], default='financial', max_length=20),
        ),
        migrations.AddField(
            model_name='msptranche',
            name='boundary_review_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msptranche',
            name='boundary_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='msptranche',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MSPBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vision', models.TextField(blank=True, help_text='The compelling future-state vision statement.')),
                ('processes', models.TextField(blank=True, help_text='Future-state business processes / ways of working.')),
                ('organisation', models.TextField(blank=True, help_text='Future-state structure, roles, skills, culture.')),
                ('technology', models.TextField(blank=True, help_text='Future-state technology, tools, infrastructure.')),
                ('information', models.TextField(blank=True, help_text='Future-state data / information requirements.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msp_blueprint', to='programs.program')),
            ],
            options={
                'verbose_name': 'MSP Blueprint',
            },
        ),
        migrations.CreateModel(
            name='MSPTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('embedded', 'Embedded'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bcm', models.ForeignKey(blank=True, help_text='Business Change Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msp_business_change_transitions', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msp_transitions', to='programs.program')),
                ('tranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='msp.msptranche')),
            ],
            options={
                'verbose_name': 'MSP Transition',
                'ordering': ['planned_date', '-created_at'],
            },
        ),
    ]
