# Generated by Django 5.2.6 on 2025-10-20 14:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_document_trainingmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Workflow', help_text='Name of the workflow diagram', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(help_text='The project this workflow diagram belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_diagram', to='projects.project')),
            ],
            options={
                'verbose_name': 'Workflow Diagram',
                'verbose_name_plural': 'Workflow Diagrams',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(help_text='Unique identifier for this edge within the workflow', max_length=100)),
                ('source_node_id', models.CharField(help_text='ID of the source node', max_length=100)),
                ('target_node_id', models.CharField(help_text='ID of the target node', max_length=100)),
                ('source_handle', models.CharField(blank=True, help_text="Source handle position (e.g., 'bottom', 'right')", max_length=50, null=True)),
                ('target_handle', models.CharField(blank=True, help_text="Target handle position (e.g., 'top', 'left')", max_length=50, null=True)),
                ('label', models.CharField(blank=True, help_text='Label text on the edge', max_length=100)),
                ('animated', models.BooleanField(default=False, help_text='Whether the edge should be animated')),
                ('stroke_color', models.CharField(default='#374151', help_text='Edge stroke color (hex code)', max_length=50)),
                ('stroke_width', models.IntegerField(default=2, help_text='Edge stroke width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('marker_type', models.CharField(choices=[('arrowclosed', 'Arrow Closed'), ('arrow', 'Arrow Open')], default='arrowclosed', max_length=50)),
                ('marker_color', models.CharField(default='#374151', help_text='Marker/arrow color (hex code)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflow.workflowdiagram')),
            ],
            options={
                'verbose_name': 'Workflow Edge',
                'verbose_name_plural': 'Workflow Edges',
                'ordering': ['workflow', 'created_at'],
                'unique_together': {('workflow', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='Unique identifier for this node within the workflow', max_length=100)),
                ('node_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('snipRectangle', 'Snip Rectangle'), ('roundedRectangle', 'Rounded Rectangle'), ('diamond', 'Diamond'), ('circle', 'Circle'), ('parallelogram', 'Parallelogram'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('octagon', 'Octagon'), ('decagon', 'Decagon'), ('triangle', 'Triangle'), ('equilateralTriangle', 'Equilateral Triangle'), ('star', '5-Point Star'), ('sixStar', '6-Point Star'), ('fourStar', '4-Point Star'), ('sixteenStar', '16-Point Star'), ('thirtyTwoStar', '32-Point Star'), ('noSymbol', 'No Symbol'), ('can', 'Can/Cylinder'), ('arrow', 'Arrow'), ('cylinder', 'Database/Cylinder'), ('document', 'Document')], default='rectangle', max_length=50)),
                ('label', models.CharField(help_text='Text label displayed on the node', max_length=255)),
                ('position_x', models.FloatField(default=0, help_text='X coordinate position')),
                ('position_y', models.FloatField(default=0, help_text='Y coordinate position')),
                ('color', models.CharField(default='#1e40af', help_text='Background color (hex code)', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex code)', max_length=50)),
                ('font_size', models.IntegerField(default=12, help_text='Font size in pixels', validators=[django.core.validators.MinValueValidator(8)])),
                ('order_index', models.IntegerField(default=0, help_text='Order of creation/display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflowdiagram')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['workflow', 'order_index'],
                'unique_together': {('workflow', 'node_id')},
            },
        ),
    ]
